/**
 * Regenerates the DASwords dictionary (apps/game-server/src/rooms/words/data/dascade-words.txt).
 *
 * Sources (download once, then point this script at them):
 *  - ENABLE2K word list, public domain:  https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt
 *  - SCOWL via the `wordlist-english` npm tarball (SCOWL licence, see data/LICENSE.md):
 *      https://registry.npmjs.org/wordlist-english/-/wordlist-english-1.2.1.tgz  (extract; use its package/ dir)
 *
 * Usage:
 *   pnpm exec tsx scripts/words/build-dictionary.ts <enable1.txt> <wordlist-english/package>
 *
 * Plus a small hand-written supplement of everyday modern words (SUPPLEMENT below, tier 1).
 *
 * Output: lowercase a–z words of 3–15 letters in three tiers (see packages/game-core/src/words/dictionary.ts),
 * with the office-safe blocklist (packages/game-core/src/words/blocklist.ts) removed.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isBlockedWord } from '../../packages/game-core/src/words/blocklist.ts';
import { MAX_WORD_LENGTH, MIN_WORD_LENGTH } from '../../packages/game-core/src/words/dictionary.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../../apps/game-server/src/rooms/words/data/dascade-words.txt');

const [enablePath, scowlDir] = process.argv.slice(2);
if (!enablePath || !scowlDir) {
  console.error('usage: tsx scripts/words/build-dictionary.ts <enable1.txt> <wordlist-english/package>');
  process.exit(1);
}

/** Internet-slang / fragment entries in SCOWL that make poor game words. */
const SCOWL_EXCLUDE = new Set(['pwn', 'pwns', 'pwned', 'pwning', 'hims', 'hos', 'mes', 'mys', 'yous', 'yeps', 'yest', 'meg', 'megs', 'mkay', 'non', 'thees', 'scotchs', 'hepper']);

/**
 * DASwords supplement: everyday modern words (tier 1) that neither source lists. Hand-written for
 * DASwords; generic words only (no trademarks).
 */
const SUPPLEMENT = `app apps wifi offline touchscreen touchscreens kombucha chai americano americanos macchiato macchiatos lassi
  mocktail mocktails slushie slushies ramen pho churro churros sweetcorn clementine clementines dragonfruit dragonfruits
  passionfruit passionfruits seahorse seahorses pufferfish hoverfly hoverflies woodlouse woodlice hashbrown hashbrowns
  placemat placemats paperclip paperclips whiteboard whiteboards netball taekwondo pickleball bouldering paddleboarding
  kitesurfing bobsleigh bobsleighs cufflink cufflinks flipflop flipflops sideburn sideburns heatwave heatwaves deckchair
  deckchairs rockpool rockpools beachball beachballs laundromat laundromats hairdryer hairdryers multimeter multimeters
  rockstar rockstars playdough yoyo yoyos pogo emoji emojis selfie selfies podcast podcasts livestream livestreams
  smartwatch smartwatches earbud earbuds hashtag hashtags`
  .split(/\s+/)
  .filter(Boolean);

const shape = (w: string) => /^[a-z]+$/.test(w) && w.length >= MIN_WORD_LENGTH && w.length <= MAX_WORD_LENGTH;

const enable = new Set(
  readFileSync(enablePath, 'utf8')
    .split(/\r?\n/)
    .map((w) => w.trim().toLowerCase())
    .filter(shape),
);

const scowlLevel = new Map<string, number>();
for (const level of [10, 20, 35, 40, 50]) {
  for (const variant of ['english', 'american', 'british']) {
    const list = JSON.parse(readFileSync(path.join(scowlDir, `${variant}-words-${level}.json`), 'utf8')) as string[];
    for (const w of list) {
      if (!shape(w) || SCOWL_EXCLUDE.has(w)) continue;
      scowlLevel.set(w, Math.min(scowlLevel.get(w) ?? 99, level));
    }
  }
}

for (const w of SUPPLEMENT) if (shape(w)) scowlLevel.set(w, Math.min(scowlLevel.get(w) ?? 99, 10));

const tiers: [string[], string[], string[]] = [[], [], []];
let blocked = 0;
for (const w of new Set([...enable, ...scowlLevel.keys()])) {
  if (isBlockedWord(w)) {
    blocked++;
    continue;
  }
  const level = scowlLevel.get(w);
  const tier = level === undefined ? 3 : level <= 35 ? 1 : 2;
  tiers[tier - 1].push(w);
}
for (const t of tiers) t.sort();

const header = [
  '# DASwords dictionary — generated by scripts/words/build-dictionary.ts. Do not edit by hand.',
  '# Sources: ENABLE2K (public domain) + SCOWL levels 10-50 (Copyright 2000-2016 Kevin Atkinson; see LICENSE.md) + DASwords supplement.',
  '# Tiers: [1] everyday (SCOWL <= 35)  [2] familiar (SCOWL 40-50)  [3] rare (ENABLE only). Office-safe blocklist removed.',
];
const body = tiers.map((list, i) => `[${i + 1}]\n${list.join('\n')}`).join('\n');
writeFileSync(OUT, `${header.join('\n')}\n${body}\n`);
console.log(`wrote ${OUT}: tier1=${tiers[0].length} tier2=${tiers[1].length} tier3=${tiers[2].length} blocked=${blocked}`);
