/**
 * Corporate Desktop '98 — somebody installed an unauthorised arcade suite on every computer in the
 * office in 1998. Grey bevelled chrome, navy title bars, a teal company wallpaper, taskbar-style
 * persistent controls and tooltip-yellow notifications. A LIGHT theme: body ink is near-black on
 * grey "window face" panels; the wallpaper only ever carries decoration (the skin frames every
 * screen as an application window, see apps/web/src/themes/corporate-98/skin.css).
 *
 * Original interpretation of late-90s office software — no vendor assets, names or logos.
 */
import type { ThemeDefinition } from '../types.ts';

/** Window-face grey and its bevel partners (reused by the skin as --c98-* locals). */
const FACE = '#c4c4bf';
const HI = '#ffffff';
const LO = '#86868a';
const DK = '#1a1a1d';
const NAVY = '#0b2c7a';
const NAVY_2 = '#2a6fd0';

const BEVEL_OUT = `inset -1px -1px 0 ${DK}, inset 1px 1px 0 ${HI}, inset -2px -2px 0 ${LO}, inset 2px 2px 0 #e4e4df`;

export const CORPORATE_98: ThemeDefinition = {
  id: 'corporate-98',
  name: "Corporate Desktop '98",
  description:
    'Grey bevelled windows, navy title bars and a teal company wallpaper. Someone installed an arcade on every PC in the office, and IT has not noticed yet.',
  meta: {
    era: '1998 · Office workstation',
    tagline: 'Someone installed an arcade on every PC in the office.',
    swatches: ['#3f7f82', FACE, NAVY, '#ffffe1'],
    family: 'retro-desktop',
  },
  effects: { surface: 'bevel', crt: 0.1, grain: 0, analog: 0, ambient: 'none', visualizer: 'blocks', transition: 'boot' },
  colorScheme: 'light',
  metaThemeColor: '#3f7f82',
  copy: {
    'arcade.tagline': 'Workgroup Edition · Licensed to: All Employees',
    'arcade.status': 'LAN: CONNECTED|{cabinets} APPLICATIONS INSTALLED|IT DEPT. HAS NOT NOTICED|PRODUCTIVITY: 3%',
    'arcade.badge': 'WORKGROUP EDITION',
    'cabinet.heading': 'Select an application',
    'lobby.title': 'Meeting Room',
    'lobby.players': 'Attendees',
    'results.title': 'Session Report',
    'tournament.title': 'Tournament Manager 98',
    'tournament.subtitle': 'Enterprise Bracket Administration Console · Authorized personnel only',
    'settings.title': 'Control Panel',
    'jukebox.title': 'Media Player (Approved by IT)',
    'state.loading': 'Please wait…',
    'state.connecting': 'Dialing the office network…',
    'state.empty': 'This folder is empty.',
    'state.error': 'This application has encountered a problem',
  },
  tokens: {
    '--theme-color-scheme': 'light',
    // Greys run dark → light so "raised" surfaces (bg-4/5) read lighter, as on a bevelled desktop.
    '--bg-0': '#a4a49f',
    '--bg-1': '#b2b2ad',
    '--bg-2': FACE,
    '--bg-3': '#cfcfca',
    '--bg-4': '#dadad5',
    '--bg-5': '#e6e6e1',
    '--glass': FACE,
    '--glass-strong': FACE,
    '--glass-light': 'rgba(255, 255, 255, 0.35)',
    '--line': 'rgba(0, 0, 0, 0.16)',
    '--line-strong': 'rgba(0, 0, 0, 0.32)',
    '--line-bright': 'rgba(0, 0, 0, 0.55)',
    '--text-0': '#0e0e12',
    '--text-1': '#23232a',
    '--text-2': '#404047',
    '--text-3': '#4c4c53',
    '--text-inverse': '#ffffff',
    // Clip-art primaries, deep enough to read as text on grey.
    '--pink': '#b8156f',
    '--cyan': '#00707e',
    '--yellow': '#d9a300',
    '--green': '#157a36',
    '--orange': '#c25500',
    '--purple': '#5d36b5',
    '--red': '#c01616',
    '--blue': '#1c49c8',
    '--lime': '#4f8a00',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': '#9a6a00',
    '--danger': 'var(--red)',
    '--info': 'var(--blue)',
    '--accent': '#1f52b8',
    '--accent-2': '#008080',
    '--accent-deep': '#b9c8e4',
    '--accent-ink': '#ffffff',
    '--page-bg': '#3f7f82',
    '--page-fg': '#0e0e12',
    '--focus-ring': '#000000',
    '--scrollbar-thumb': '#a4a49f',
    '--font-display': "'DASCADE Digits', Tahoma, Verdana, 'Segoe UI', 'Inter Variable', system-ui, sans-serif",
    '--font-pixel': "Tahoma, Verdana, 'Segoe UI', 'Inter Variable', system-ui, sans-serif",
    '--font-ui': "Tahoma, Verdana, 'Segoe UI', 'Inter Variable', system-ui, sans-serif",
    '--font-tech': "'Lucida Console', 'Courier New', ui-monospace, monospace",
    '--font-num': "Tahoma, Verdana, 'Space Grotesk Variable', system-ui, sans-serif",
    '--heading-tracking': '0',
    '--label-tracking': '0.04em',
    '--px': '2px',
    '--radius-sm': '0px',
    '--radius': '0px',
    '--radius-lg': '0px',
    '--shadow-1': '1px 1px 0 rgba(0, 0, 0, 0.45)',
    '--shadow-2': '2px 2px 0 rgba(0, 0, 0, 0.35)',
    '--shadow-3': '4px 4px 0 rgba(0, 0, 0, 0.3)',
    '--glow-sm-full': '0 0 0 transparent',
    '--glow-md-full': '0 0 0 transparent',
    '--glow-lg-full': '0 0 0 transparent',
    '--text-glow-full': 'none',
    '--glow-sm-soft': '0 0 0 transparent',
    '--glow-md-soft': '0 0 0 transparent',
    '--glow-lg-soft': '0 0 0 transparent',
    '--text-glow-soft': 'none',
    '--ease-out': 'cubic-bezier(0.3, 0.7, 0.3, 1)',
    '--ease-in-out': 'cubic-bezier(0.5, 0, 0.5, 1)',
    '--ease-spring': 'cubic-bezier(0.3, 0.7, 0.3, 1)',
    '--motion-1': '60ms',
    '--motion-2': '110ms',
    '--motion-3': '200ms',
    '--motion-4': '320ms',
    '--surface-sunken': '#ffffff',
    '--surface-sunken-soft': '#ecece7',
    '--surface-raised': '#d2d2cd',
    '--surface-hover': 'rgba(11, 44, 122, 0.12)',
    '--panel-bg': FACE,
    '--panel-bg-solid': FACE,
    '--panel-bg-opaque': FACE,
    '--panel-sheen': 'none',
    '--panel-border': DK,
    '--panel-border-width': '1px',
    '--panel-radius': '0px',
    '--panel-shadow': `inset 1px 1px 0 ${HI}, inset -1px -1px 0 ${LO}, inset 2px 2px 0 #e4e4df, 2px 2px 0 rgba(0, 0, 0, 0.28)`,
    '--panel-blur': 'none',
    '--panel-divider': LO,
    '--titlebar-bg': `linear-gradient(90deg, ${NAVY}, ${NAVY_2})`,
    '--titlebar-fg': '#ffffff',
    '--titlebar-font': "Tahoma, Verdana, 'Segoe UI', 'Inter Variable', system-ui, sans-serif",
    '--titlebar-size': 'var(--fs-sm)',
    '--titlebar-tracking': '0.01em',
    '--titlebar-transform': 'none',
    '--titlebar-marker-size': '0px',
    '--bracket-size': '0px',
    '--bracket-width': '0px',
    '--overlay-scrim': 'rgba(10, 30, 40, 0.38)',
    '--overlay-blur': 'none',
    '--button-font': "Tahoma, Verdana, 'Segoe UI', 'Inter Variable', system-ui, sans-serif",
    '--button-tracking': '0.01em',
    '--button-radius': '0px',
    '--button-edge-width': '1px',
    '--button-bevel-hi': HI,
    '--button-bevel-lo': LO,
    '--button-hover-filter': 'brightness(1.04)',
    '--button-press-offset': '1px',
    '--button-bg': '#d0d0cb',
    '--button-bg-2': FACE,
    '--button-fg': '#0e0e12',
    '--button-edge': DK,
    '--button-danger-bg': '#cf3a32',
    '--button-danger-bg-2': '#a51f1a',
    '--button-danger-fg': '#ffffff',
    '--button-danger-edge': '#2a0504',
    '--button-success-bg': '#2f8f45',
    '--button-success-bg-2': '#1d6d31',
    '--button-success-fg': '#ffffff',
    '--button-success-edge': '#06200c',
    '--button-gold-bg': '#ffe98a',
    '--button-gold-bg-2': '#f2cf4a',
    '--button-gold-fg': '#1a1300',
    '--button-gold-edge': '#3a2c00',
    '--input-bg': '#ffffff',
    '--input-fg': '#0e0e12',
    '--input-border': LO,
    '--input-border-hover': '#44444a',
    '--input-radius': '0px',
    '--input-inset': `inset 1px 1px 0 ${LO}, inset 2px 2px 0 #404044`,
    '--input-placeholder': '#62626a',
    '--control-track': '#ffffff',
    '--control-track-edge': LO,
    '--shell-bar-bg': FACE,
    '--shell-bar-border': DK,
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '1',
    '--shell-bar-solid': FACE,
    '--shell-dock-bg': FACE,
    '--shell-dock-border': HI,
    '--shell-dock-shadow': `inset 0 1px 0 ${HI}, 0 -1px 0 ${LO}`,
    '--shell-dock-blur': 'none',
    '--toast-bg': '#ffffe1',
    '--toast-shadow': '2px 2px 0 rgba(0, 0, 0, 0.35)',
    '--hud-bg': FACE,
    '--hud-bg-strong': '#b8b8b3',
    '--hud-border': DK,
    '--hud-fg': '#0e0e12',
    '--hud-muted': '#3a3a40',
    '--hud-radius': '0px',
    '--hud-shadow': BEVEL_OUT,
    '--hud-blur': 'none',
    '--arcade-floor-bg': '#3f7f82',
    '--cabinet-body': '#d8d1bc',
    '--cabinet-body-2': '#a39c86',
    '--cabinet-edge': 'rgba(0, 0, 0, 0.4)',
    '--cabinet-bezel': '#3b3a35',
    '--cabinet-screen-bg': '#000',
    '--cabinet-glass': 'linear-gradient(122deg, rgba(255, 255, 255, 0.14) 0%, rgba(255, 255, 255, 0.04) 28%, transparent 29%)',
    '--cabinet-screen-inset': 'inset 0 0 0 2px #1d1d1b',
    '--cabinet-shadow': '6px 8px 0 rgba(0, 0, 0, 0.25)',
    '--marquee-font': 'var(--font-display)',
    '--marquee-ink': '#ffffff',
    '--marquee-outline': NAVY,
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 45%)',
    '--marquee-tracking': '0.02em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.12)',
    '--scanline-pitch': '2px',
    '--scanline-opacity-full': '0.25',
    '--scanline-opacity-soft': '0.1',
    '--grid-ink': 'transparent',
    '--grid-size': '24px',
    '--noise-opacity': '0',
    '--vignette-edge': 'rgba(0, 0, 0, 0)',
  },
  overrides: {
    '--title-shadow': 'none',
    '--button-primary-bg': '#2a62c8',
    '--button-primary-bg-2': NAVY,
    '--button-primary-fg': '#ffffff',
    '--button-primary-edge': '#000000',
    '--button-primary-glow': 'transparent',
    '--button-secondary-edge': DK,
    '--bracket-color': 'transparent',
    '--titlebar-marker': '#ffffff',
    '--panel-glow-border': DK,
    '--panel-glow-shadow': `inset 1px 1px 0 ${HI}, inset -1px -1px 0 ${LO}, inset 2px 2px 0 #e4e4df, 2px 2px 0 rgba(0, 0, 0, 0.28)`,
    '--control-accent': NAVY,
    '--control-accent-ink': '#ffffff',
    '--input-focus-ring': '0 0 0 1px #000',
    '--game-backdrop': 'linear-gradient(180deg, #9d9d98, #92928d)',
    '--shell-bar-rule': `linear-gradient(90deg, ${LO}, ${LO})`,
  },
  renderer: {
    background: '#9d9d98',
    surface: FACE,
    text: '#0e0e12',
    textMuted: '#404047',
    line: '#000000',
    accent: '#2a62c8',
    accent2: '#008080',
    gridAlpha: 0.14,
    scanlines: 0.06,
    scanlinesSoft: 0.03,
    glow: 0.15,
    glowSoft: 0.05,
  },
  materials: {
    // Desk blotter green on grey plastic.
    felt: '#2f6f4c',
    feltDeep: '#1f5236',
    feltLine: '#5f9a78',
    rail: '#8c8c86',
    railHighlight: '#dcdcd7',
    // Spreadsheet-grey and slate-navy squares, highlighter yellow.
    boardLight: '#e4e4de',
    boardDark: '#5a739e',
    boardFrame: '#8f8f8a',
    boardHighlight: '#ffe45c',
    pieceLight: '#ffffff',
    pieceDark: '#17171d',
    pieceEdge: '#000000',
    water: '#1f5c9e',
    waterDeep: '#123a68',
    gridLine: '#a8c8ec',
    radar: '#35d06a',
    // Clip-art golf.
    grass: '#4c9e47',
    grassDeep: '#387d35',
    sand: '#e8d79c',
    hazard: '#3b7fd4',
    wall: '#8c8c86',
    wallTop: '#d8d8d3',
    sky: '#8fc3e8',
    skyHorizon: '#dcedf8',
    ground: '#5e8f3a',
    groundDeep: '#3f6a28',
    groundEdge: '#9cc76a',
    asphalt: '#56565a',
    asphaltLine: '#f2f2ee',
    curbA: '#d02a2a',
    curbB: '#f2f2ee',
    offroad: '#5f9a48',
    cardFace: '#ffffff',
    cardInk: '#101014',
    cardBack: '#1d4fae',
    cardBackInk: '#9dbcf2',
    paper: '#ffffff',
    paperInk: '#101014',
    paperEdge: '#86868a',
    // Presentation-software stage: a pale slide (the theme's ink is dark, so stages stay light).
    stage: '#dfe5ef',
    stageLight: '#ffffff',
    podium: FACE,
    screen: '#000000',
    screenGlow: '#4fd06a',
    bezel: '#d8d1bc',
    metal: '#a8a8a3',
    metalHighlight: '#f2f2ee',
    led: '#2fdc4a',
    ledOff: '#2c4a31',
  },
  gameMaterials: {
    // "Corporate training software": the party games play on a pale slide.
    survey: { stage: '#e4e9f3', podium: '#d6d6d1' },
    trivia: { stage: '#e4e9f3', podium: '#d6d6d1' },
    // Putt on the office carpet-tile green, played in a window on the teal company desktop.
    putt: { grass: '#4a8f5a', grassDeep: '#3a7348', sky: '#3f7f82', stage: '#3f7f82' },
  },
};
