/**
 * Delta Neon — the shipped DASCADE look: deep violet-black glass, neon accents, pixel bevels,
 * restrained CRT textures. These values MUST equal the :root layers of styles/tokens.css
 * (theme.test.ts enforces it); tokens.css is what paints the page before any script runs.
 */
import type { ThemeDefinition } from '../types.ts';

export const DELTA_NEON: ThemeDefinition = {
  id: 'delta-neon',
  name: 'Delta Neon',
  description: 'The DASCADE house style: deep violet-black glass, neon accents, pixel bevels and restrained CRT textures.',
  colorScheme: 'dark',
  metaThemeColor: '#05040b',
  tokens: {
    '--theme-color-scheme': 'dark',
    '--bg-0': '#05040b',
    '--bg-1': '#0a0816',
    '--bg-2': '#110e22',
    '--bg-3': '#19152f',
    '--bg-4': '#231e42',
    '--bg-5': '#2e2856',
    '--glass': 'rgba(17, 14, 34, 0.74)',
    '--glass-strong': 'rgba(12, 10, 26, 0.92)',
    '--glass-light': 'rgba(255, 255, 255, 0.04)',
    '--line': 'rgba(190, 176, 255, 0.12)',
    '--line-strong': 'rgba(190, 176, 255, 0.24)',
    '--line-bright': 'rgba(220, 212, 255, 0.42)',
    '--text-0': '#f8f6ff',
    '--text-1': '#d3cdf0',
    '--text-2': '#9d95c4',
    '--text-3': '#8e87b8',
    '--text-inverse': '#07050f',
    '--pink': '#ff4fd8',
    '--cyan': '#22d3ee',
    '--yellow': '#ffd23f',
    '--green': '#2de38f',
    '--orange': '#ff8a3d',
    '--purple': '#a78bfa',
    '--red': '#ff5a5f',
    '--blue': '#60a5fa',
    '--lime': '#a3e635',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': 'var(--cyan)',
    '--accent-2': 'var(--pink)',
    '--accent-deep': '#061520',
    '--accent-ink': '#04030a',
    '--page-bg': 'var(--bg-0)',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': 'var(--yellow)',
    '--scrollbar-thumb': 'var(--bg-5)',
    '--font-display': "'DASCADE Digits', 'Tiny5', 'Silkscreen', ui-monospace, 'SFMono-Regular', monospace",
    '--font-pixel': "'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--font-ui': "'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    '--font-tech': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-num': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.01em',
    '--label-tracking': '0.12em',
    '--px': '3px',
    '--radius-sm': '4px',
    '--radius': '8px',
    '--radius-lg': '14px',
    '--shadow-1': '0 2px 0 rgba(0, 0, 0, 0.35), 0 8px 22px rgba(0, 0, 0, 0.35)',
    '--shadow-2': '0 3px 0 rgba(0, 0, 0, 0.4), 0 18px 44px rgba(0, 0, 0, 0.5)',
    '--shadow-3': '0 30px 80px rgba(0, 0, 0, 0.6)',
    '--glow-sm-full': '0 0 10px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--glow-md-full':
      '0 0 18px color-mix(in srgb, var(--accent) 50%, transparent), 0 0 42px color-mix(in srgb, var(--accent) 22%, transparent)',
    '--glow-lg-full':
      '0 0 24px color-mix(in srgb, var(--accent) 60%, transparent), 0 0 80px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--text-glow-full': '0 0 12px color-mix(in srgb, var(--accent) 70%, transparent)',
    '--glow-sm-soft': '0 0 10px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--glow-md-soft': '0 0 10px color-mix(in srgb, var(--accent) 35%, transparent)',
    '--glow-lg-soft': '0 0 16px color-mix(in srgb, var(--accent) 40%, transparent)',
    '--text-glow-soft': '0 0 6px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--ease-out': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    '--ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
    '--ease-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    '--motion-1': '120ms',
    '--motion-2': '220ms',
    '--motion-3': '420ms',
    '--motion-4': '700ms',
    '--surface-sunken': 'rgba(5, 4, 12, 0.7)',
    '--surface-sunken-soft': 'rgba(5, 4, 12, 0.6)',
    '--surface-raised': 'rgba(255, 255, 255, 0.025)',
    '--surface-hover': 'var(--glass-light)',
    '--panel-bg': 'var(--glass)',
    '--panel-bg-solid': 'var(--glass-strong)',
    '--panel-bg-opaque': 'var(--bg-2)',
    '--panel-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.035), rgba(255, 255, 255, 0) 40%)',
    '--panel-border': 'var(--line-strong)',
    '--panel-border-width': '1px',
    '--panel-radius': 'var(--radius-sm)',
    '--panel-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.06), var(--shadow-2)',
    '--panel-blur': 'blur(14px) saturate(1.2)',
    '--panel-divider': 'var(--line)',
    '--titlebar-bg': 'transparent',
    '--titlebar-fg': 'var(--text-1)',
    '--titlebar-font': 'var(--font-pixel)',
    '--titlebar-size': 'var(--fs-xs)',
    '--titlebar-tracking': '0.14em',
    '--titlebar-transform': 'uppercase',
    '--titlebar-marker-size': '8px',
    '--bracket-size': '14px',
    '--bracket-width': 'var(--px)',
    '--overlay-scrim': 'rgba(3, 2, 8, 0.72)',
    '--overlay-blur': 'blur(4px)',
    '--button-font': 'var(--font-display)',
    '--button-tracking': '0.03em',
    '--button-radius': '0px',
    '--button-edge-width': 'var(--px)',
    '--button-bevel-hi': 'rgba(255, 255, 255, 0.18)',
    '--button-bevel-lo': 'rgba(0, 0, 0, 0.32)',
    '--button-hover-filter': 'brightness(1.12)',
    '--button-press-offset': '2px',
    '--button-bg': 'var(--bg-4)',
    '--button-bg-2': 'var(--bg-3)',
    '--button-fg': 'var(--text-0)',
    '--button-edge': 'var(--line-bright)',
    '--button-danger-bg': '#ff7a7e',
    '--button-danger-bg-2': 'var(--red)',
    '--button-danger-fg': '#1a0305',
    '--button-danger-edge': '#8c1d22',
    '--button-success-bg': '#6cf0b0',
    '--button-success-bg-2': 'var(--green)',
    '--button-success-fg': '#02170c',
    '--button-success-edge': '#0f7a47',
    '--button-gold-bg': '#ffe27a',
    '--button-gold-bg-2': 'var(--yellow)',
    '--button-gold-fg': '#1d1400',
    '--button-gold-edge': '#9c7400',
    '--input-bg': 'var(--surface-sunken)',
    '--input-fg': 'var(--text-0)',
    '--input-border': 'var(--line-strong)',
    '--input-border-hover': 'var(--line-bright)',
    '--input-radius': 'var(--radius-sm)',
    '--input-inset': 'inset 0 2px 0 rgba(0, 0, 0, 0.35)',
    '--input-placeholder': 'var(--text-3)',
    '--control-track': 'var(--bg-1)',
    '--control-track-edge': 'var(--line-bright)',
    '--shell-bar-bg': 'linear-gradient(180deg, rgba(8, 6, 18, 0.94), rgba(8, 6, 18, 0.82))',
    '--shell-bar-border': 'var(--line)',
    '--shell-bar-blur': 'blur(10px)',
    '--shell-bar-rule-opacity': '0.7',
    '--shell-bar-solid': 'rgba(8, 6, 18, 0.95)',
    '--shell-dock-bg': 'color-mix(in srgb, var(--bg-1) 94%, transparent)',
    '--shell-dock-border': 'var(--line-strong)',
    '--shell-dock-shadow': '0 -10px 30px rgba(0, 0, 0, 0.35)',
    '--shell-dock-blur': 'blur(12px)',
    '--toast-bg': 'var(--glass-strong)',
    '--toast-shadow': 'var(--shadow-2)',
    '--hud-bg': 'rgba(10, 8, 22, 0.72)',
    '--hud-bg-strong': 'var(--glass-strong)',
    '--hud-border': 'var(--line-strong)',
    '--hud-fg': 'var(--text-0)',
    '--hud-muted': 'var(--text-2)',
    '--hud-radius': 'var(--radius-sm)',
    '--hud-shadow': 'var(--shadow-1)',
    '--hud-blur': 'blur(10px)',
    '--arcade-floor-bg': '#07050f',
    '--cabinet-body': '#1d1936',
    '--cabinet-body-2': '#0d0a1c',
    '--cabinet-edge': 'rgba(214, 196, 255, 0.18)',
    '--cabinet-bezel': '#15122a',
    '--cabinet-screen-bg': '#000',
    '--cabinet-glass': 'linear-gradient(122deg, rgba(255, 255, 255, 0.2) 0%, rgba(255, 255, 255, 0.06) 26%, transparent 27%)',
    '--cabinet-screen-inset': 'inset 0 0 0 1px rgba(255, 255, 255, 0.07)',
    '--cabinet-shadow': '0 30px 80px rgba(0, 0, 0, 0.6)',
    '--marquee-font': 'var(--font-display)',
    '--marquee-ink': '#fff',
    '--marquee-outline': '#1a0826',
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.26), rgba(255, 255, 255, 0) 42%)',
    '--marquee-tracking': '0.04em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.22)',
    '--scanline-pitch': '3px',
    '--scanline-opacity-full': '0.55',
    '--scanline-opacity-soft': '0.25',
    '--grid-ink': 'rgba(255, 255, 255, 0.025)',
    '--grid-size': '24px',
    '--noise-opacity': '0.06',
    '--vignette-edge': 'rgba(0, 0, 0, 0.55)',
  },
  renderer: {
    background: '#05040b',
    surface: '#110e22',
    text: '#f8f6ff',
    textMuted: '#9d95c4',
    line: '#beb0ff',
    accent: '#22d3ee',
    accent2: '#ff4fd8',
    gridAlpha: 0.06,
    scanlines: 0.18,
    scanlinesSoft: 0.08,
    glow: 1,
    glowSoft: 0.5,
  },
};
