/**
 * Mall Arcade '92 — the pure physical arcade fantasy: second floor of the mall, past the food court.
 * Dark carpet with a ridiculous geometric pattern, humming fluorescent tubes, rows of cabinets in
 * red/blue/purple light, lit marquees, token machines, ticket dispensers and a prize counter.
 *
 * Chrome reads as PHYSICAL arcade hardware: black speckled laminate panels with chrome T-molding,
 * backlit marquee title bars, convex push-buttons (the primary action is the big red one) and
 * token-brass gold. Numbers stay on the legible numeral face (--font-num).
 */
import type { ThemeDefinition } from '../types.ts';

const INK = '#fff7ea';

export const MALL_ARCADE_92: ThemeDefinition = {
  id: 'mall-arcade-92',
  name: "Mall Arcade '92",
  description:
    'Level 2, past the food court: geometric carpet, humming fluorescent tubes, lit marquees, tokens, tickets and the prize counter.',
  meta: {
    era: '1992 · Mall arcade',
    tagline: 'Carpet, tokens, fluorescent light and a whole row of cabinets.',
    swatches: ['#0d0818', '#1e1334', '#ff2f4f', '#3d8bff'],
    family: 'physical',
  },
  effects: {
    surface: 'plastic',
    crt: 0.55,
    grain: 0.12,
    analog: 0,
    ambient: 'dust',
    visualizer: 'bubbles',
    transition: 'fluorescent',
  },
  colorScheme: 'dark',
  metaThemeColor: '#0d0818',
  tokens: {
    '--theme-color-scheme': 'dark',
    '--bg-0': '#0d0818',
    '--bg-1': '#130c22',
    '--bg-2': '#1a112d',
    '--bg-3': '#231839',
    '--bg-4': '#2e2049',
    '--bg-5': '#3c2b5e',
    '--glass': 'rgba(22, 14, 38, 0.94)',
    '--glass-strong': 'rgba(17, 10, 30, 0.97)',
    '--glass-light': 'rgba(255, 240, 220, 0.05)',
    '--line': 'rgba(214, 190, 255, 0.14)',
    '--line-strong': 'rgba(214, 190, 255, 0.28)',
    '--line-bright': 'rgba(236, 224, 255, 0.5)',
    '--text-0': INK,
    '--text-1': '#e6dcf2',
    '--text-2': '#b4a6cc',
    '--text-3': '#a295bd',
    '--text-inverse': '#0d0818',
    '--pink': '#ff4f9a',
    '--cyan': '#3fd4ff',
    '--yellow': '#ffcc33',
    '--green': '#3fe07e',
    '--orange': '#ff8c2e',
    '--purple': '#b77bff',
    '--red': '#ff3b4e',
    '--blue': '#4d8dff',
    '--lime': '#b8f03c',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': '#ff3b5c',
    '--accent-2': '#4d8dff',
    '--accent-deep': '#1c0610',
    '--accent-ink': '#12040a',
    '--page-bg': 'var(--bg-0)',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': 'var(--yellow)',
    '--scrollbar-thumb': 'var(--bg-5)',
    '--font-display': "'DASCADE Digits', 'Pixelify Sans Variable', 'Tiny5', 'Silkscreen', ui-monospace, monospace",
    '--font-pixel': "'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--font-ui': "'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    '--font-tech': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-num': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.02em',
    '--label-tracking': '0.12em',
    '--px': '3px',
    '--radius-sm': '4px',
    '--radius': '8px',
    '--radius-lg': '12px',
    '--shadow-1': '0 2px 0 rgba(0, 0, 0, 0.45), 0 8px 20px rgba(0, 0, 0, 0.4)',
    '--shadow-2': '0 4px 0 rgba(0, 0, 0, 0.5), 0 18px 40px rgba(0, 0, 0, 0.55)',
    '--shadow-3': '0 30px 80px rgba(0, 0, 0, 0.65)',
    '--glow-sm-full': '0 0 10px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--glow-md-full':
      '0 0 16px color-mix(in srgb, var(--accent) 50%, transparent), 0 0 36px color-mix(in srgb, var(--accent) 22%, transparent)',
    '--glow-lg-full':
      '0 0 22px color-mix(in srgb, var(--accent) 60%, transparent), 0 0 70px color-mix(in srgb, var(--accent) 28%, transparent)',
    '--text-glow-full': '0 0 10px color-mix(in srgb, var(--accent) 65%, transparent)',
    '--glow-sm-soft': '0 0 8px color-mix(in srgb, var(--accent) 40%, transparent)',
    '--glow-md-soft': '0 0 10px color-mix(in srgb, var(--accent) 35%, transparent)',
    '--glow-lg-soft': '0 0 14px color-mix(in srgb, var(--accent) 40%, transparent)',
    '--text-glow-soft': '0 0 5px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--ease-out': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    '--ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
    '--ease-spring': 'cubic-bezier(0.34, 1.5, 0.64, 1)',
    '--motion-1': '110ms',
    '--motion-2': '200ms',
    '--motion-3': '380ms',
    '--motion-4': '640ms',
    '--surface-sunken': 'rgba(6, 3, 12, 0.72)',
    '--surface-sunken-soft': 'rgba(6, 3, 12, 0.55)',
    '--surface-raised': 'rgba(255, 240, 220, 0.03)',
    '--surface-hover': 'rgba(255, 240, 220, 0.06)',
    '--panel-bg': 'var(--glass)',
    '--panel-bg-solid': 'var(--glass-strong)',
    '--panel-bg-opaque': 'var(--bg-2)',
    '--panel-sheen':
      'radial-gradient(circle at 20% 30%, rgba(255, 255, 255, 0.035) 0 1px, transparent 1.5px) 0 0 / 7px 7px, radial-gradient(circle at 70% 80%, rgba(255, 255, 255, 0.03) 0 1px, transparent 1.5px) 0 0 / 11px 11px',
    '--panel-border': '#5a4a78',
    '--panel-border-width': '2px',
    '--panel-radius': '8px',
    '--panel-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.12), inset 0 -2px 0 rgba(0, 0, 0, 0.4), var(--shadow-2)',
    '--panel-blur': 'none',
    '--panel-divider': 'rgba(214, 190, 255, 0.16)',
    '--titlebar-bg': 'linear-gradient(180deg, #2c1d48 0%, #1d1232 55%, #160d27 100%)',
    '--titlebar-fg': '#ffd76a',
    '--titlebar-font': 'var(--font-pixel)',
    '--titlebar-size': 'var(--fs-xs)',
    '--titlebar-tracking': '0.16em',
    '--titlebar-transform': 'uppercase',
    '--titlebar-marker-size': '9px',
    '--bracket-size': '0px',
    '--bracket-width': '0px',
    '--overlay-scrim': 'rgba(8, 4, 16, 0.76)',
    '--overlay-blur': 'none',
    '--button-font': 'var(--font-display)',
    '--button-tracking': '0.04em',
    '--button-radius': '10px',
    '--button-edge-width': '2px',
    '--button-bevel-hi': 'rgba(255, 255, 255, 0.3)',
    '--button-bevel-lo': 'rgba(0, 0, 0, 0.38)',
    '--button-hover-filter': 'brightness(1.1)',
    '--button-press-offset': '3px',
    '--button-bg': '#3b2a5c',
    '--button-bg-2': '#251a3e',
    '--button-fg': INK,
    '--button-edge': '#0a0612',
    '--button-danger-bg': '#ff6a74',
    '--button-danger-bg-2': '#e0293b',
    '--button-danger-fg': '#1a0305',
    '--button-danger-edge': '#5e0a14',
    '--button-success-bg': '#6af0a0',
    '--button-success-bg-2': '#26c465',
    '--button-success-fg': '#02170c',
    '--button-success-edge': '#0a4a24',
    '--button-gold-bg': '#ffe07a',
    '--button-gold-bg-2': '#f0b020',
    '--button-gold-fg': '#241600',
    '--button-gold-edge': '#6e4a00',
    '--input-bg': '#0a0612',
    '--input-fg': INK,
    '--input-border': '#4d3f6a',
    '--input-border-hover': '#7a68a0',
    '--input-radius': '6px',
    '--input-inset': 'inset 0 2px 0 rgba(0, 0, 0, 0.55), inset 0 0 0 1px rgba(0, 0, 0, 0.3)',
    '--input-placeholder': '#9a8cb4',
    '--control-track': '#0a0612',
    '--control-track-edge': '#5a4a78',
    '--shell-bar-bg': 'linear-gradient(180deg, #1f1436 0%, #150d26 70%, #0f0a1c 100%)',
    '--shell-bar-border': '#3a2b58',
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '1',
    '--shell-bar-solid': '#150d26',
    '--shell-dock-bg': '#150d26',
    '--shell-dock-border': '#3a2b58',
    '--shell-dock-shadow': '0 -10px 28px rgba(0, 0, 0, 0.45)',
    '--shell-dock-blur': 'none',
    '--toast-bg': '#1a112d',
    '--toast-shadow': 'var(--shadow-2)',
    '--hud-bg': 'rgba(18, 11, 32, 0.9)',
    '--hud-bg-strong': '#140c24',
    '--hud-border': '#4d3f6a',
    '--hud-fg': INK,
    '--hud-muted': '#b4a6cc',
    '--hud-radius': '6px',
    '--hud-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.08), 0 3px 0 rgba(0, 0, 0, 0.45)',
    '--hud-blur': 'none',
    '--arcade-floor-bg': 'transparent',
    '--cabinet-body': '#241a3a',
    '--cabinet-body-2': '#110b1e',
    '--cabinet-edge': 'rgba(230, 210, 255, 0.28)',
    '--cabinet-bezel': '#120b20',
    '--cabinet-screen-bg': '#000',
    '--cabinet-glass':
      'linear-gradient(118deg, rgba(255, 255, 255, 0.22) 0%, rgba(255, 255, 255, 0.07) 24%, transparent 25%, transparent 70%, rgba(255, 255, 255, 0.04) 71%, transparent 80%)',
    '--cabinet-screen-inset': 'inset 0 0 0 2px rgba(0, 0, 0, 0.6), inset 0 0 18px rgba(0, 0, 0, 0.6)',
    '--cabinet-shadow': '0 26px 60px rgba(0, 0, 0, 0.7)',
    '--marquee-font': 'var(--font-display)',
    '--marquee-ink': '#fff',
    '--marquee-outline': '#1a0610',
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.32), rgba(255, 255, 255, 0) 46%)',
    '--marquee-tracking': '0.05em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.26)',
    '--scanline-pitch': '3px',
    '--scanline-opacity-full': '0.5',
    '--scanline-opacity-soft': '0.22',
    '--grid-ink': 'transparent',
    '--grid-size': '24px',
    '--noise-opacity': '0.05',
    '--vignette-edge': 'rgba(0, 0, 0, 0.6)',
  },
  overrides: {
    '--title-shadow': '0 3px 0 #7a0f24, 0 0 18px rgba(255, 59, 92, 0.45)',
    '--button-primary-bg': '#e3263f',
    '--button-primary-bg-2': '#b50f28',
    '--button-primary-fg': '#fff',
    '--button-primary-edge': '#4e0613',
    '--button-primary-glow': 'rgba(255, 59, 92, 0.35)',
    '--button-secondary-edge': '#0a0612',
    '--titlebar-marker': '#ff3b5c',
    '--panel-glow-border': '#ff3b5c',
    '--panel-glow-shadow':
      'inset 0 1px 0 rgba(255, 255, 255, 0.12), 0 0 0 1px rgba(255, 59, 92, 0.25), 0 0 26px rgba(255, 59, 92, 0.22), var(--shadow-2)',
    '--control-accent': '#ff3b5c',
    '--control-accent-ink': '#1a0308',
    '--input-focus-ring': '0 0 0 3px rgba(255, 204, 51, 0.35)',
    '--shell-bar-rule': 'linear-gradient(90deg, #ff3b5c, #b77bff 50%, #4d8dff)',
  },
  materials: {
    // Card tables: mall-arcade redemption-counter felt (royal blue), chrome rails.
    felt: '#17418c',
    feltDeep: '#0d2a60',
    feltLine: '#4f7fd8',
    rail: '#2a1d3e',
    railHighlight: '#6d5a92',
    // Boards: printed control-panel graphics — cream vs arcade purple, red cursor light.
    boardLight: '#eadfc4',
    boardDark: '#5b3f8c',
    boardFrame: '#1a1128',
    boardHighlight: '#ffcc33',
    pieceLight: '#fff6e8',
    pieceDark: '#1c1426',
    pieceEdge: '#07040c',
    // Sea / radar: deep cabinet-monitor blue with phosphor green.
    water: '#0f2f6a',
    waterDeep: '#081a40',
    gridLine: '#4d8dff',
    radar: '#3fe07e',
    // Mini golf: blacklight glow-golf carpet.
    grass: '#1f8f5a',
    grassDeep: '#136640',
    sand: '#f0d27a',
    hazard: '#2f7bff',
    wall: '#3a2658',
    wallTop: '#ff4f9a',
    // Terrain: sunset backdrop art on a side panel.
    sky: '#150a2c',
    skyHorizon: '#5a2a78',
    ground: '#3b2a5e',
    groundDeep: '#221638',
    groundEdge: '#ff8c2e',
    // Racing: sit-down racer cabinet track.
    asphalt: '#26222e',
    asphaltLine: '#fff7ea',
    curbA: '#ff3b4e',
    curbB: '#fff7ea',
    offroad: '#1c3a2a',
    // Cards: redemption tickets / game cards.
    cardFace: '#fffaf0',
    cardInk: '#140a1e',
    cardBack: '#c81e3a',
    cardBackInk: '#ffcc33',
    // Paper: prize-counter ticket stock.
    paper: '#fdf3dc',
    paperInk: '#1d1228',
    paperEdge: '#e0c890',
    // Stage: the prize-counter stage under fluorescent light.
    stage: '#160e26',
    stageLight: '#ff3b5c',
    podium: '#3b2a5e',
    // Screens: CRT in a black bezel.
    screen: '#050308',
    screenGlow: '#3fd4ff',
    bezel: '#140c20',
    // Hardware: chrome T-molding, token brass, LED bulbs.
    metal: '#b8b0c8',
    metalHighlight: '#fbf6ff',
    led: '#ff3b4e',
    ledOff: '#3a1520',
  },
  gameMaterials: {
    // Cocktail-table cabinet: the board is printed under black cabinet glass.
    chess: { boardFrame: '#07050c' },
    checkers: { boardFrame: '#07050c' },
    // Blacklight mini golf next to the arcade: neon rails over the dark carpet.
    putt: { wall: '#2a1a44', wallTop: '#3fd4ff', sky: '#150c26', stage: '#0b0614' },
    // Quiz machine: questions and answers on a deep CRT-blue screen.
    trivia: { cardFace: '#0f1a48', cardInk: '#fff7ea' },
    tanks: { sky: '#1a0c34', skyHorizon: '#7a2e6e' },
    bingo: { cardFace: '#fff4d6' },
    quest: { paper: '#1a112d', paperInk: '#f4e8d0', paperEdge: '#5a4a78' },
  },
  copy: {
    'arcade.tagline': 'Level 2 · Food court',
    'arcade.status': '11 CABINETS LIT|TOKENS 4 FOR $1|TICKETS PAY OUT AT THE COUNTER|HIGH SCORES RESET NEVER|NO FOOD ON THE MACHINES',
    'arcade.badge': 'OPEN TIL 9',
    'cabinet.heading': 'Pick a machine',
    'lobby.players': 'Players at the machine',
    'results.title': 'Final scores',
    'tournament.title': 'Tournament Board',
    'tournament.subtitle': 'Top scores above the prize counter',
    'settings.title': 'Operator menu',
    'jukebox.title': 'Jukebox',
    'state.loading': 'Warming up the tubes…',
    'state.connecting': 'Inserting token…',
    'state.empty': 'Nobody on this machine yet',
    'state.error': 'Out of order',
  },
  renderer: {
    background: '#0d0818',
    surface: '#1a112d',
    text: INK,
    textMuted: '#b4a6cc',
    line: '#d6beff',
    accent: '#ff3b5c',
    accent2: '#4d8dff',
    gridAlpha: 0.06,
    scanlines: 0.2,
    scanlinesSoft: 0.09,
    glow: 1,
    glowSoft: 0.5,
  },
};
