/**
 * Neon Noir — the premium theme. A rain-soaked arcade district after midnight: deep ink blacks,
 * wet glass, restrained neon (sodium teal + rose), fog and cinematic light. Serious, not comedy.
 *
 * Typography: Space Grotesk (installed) carries headings, signage and tiny caps labels, letter-
 * spaced and upright; the pixel DNA lives in the environment's architecture and the cabinet art. Numbers stay on --font-num. Structural chrome lives in
 * apps/web/src/themes/neon-noir/skin.css; the rain/fog/reflection environment in Environment.tsx.
 */
import type { ThemeDefinition } from '../types.ts';

const INK = '#030407';
const TEAL = '#46d9ec';
const ROSE = '#ff4d8d';

export const NEON_NOIR: ThemeDefinition = {
  id: 'neon-noir',
  name: 'Neon Noir',
  description: 'A rain-soaked arcade district after midnight: wet glass, restrained neon, fog and cinematic light.',
  meta: {
    era: 'After midnight · Rain on glass',
    tagline: 'Rain on glass. Neon in puddles. The arcade never closes.',
    swatches: [INK, '#111722', TEAL, ROSE],
    family: 'premium',
  },
  effects: { surface: 'glass', crt: 0.06, grain: 0.14, analog: 0, ambient: 'rain', visualizer: 'spectrum', transition: 'fade' },
  copy: {
    'arcade.tagline': 'Open until dawn',
    'arcade.status': 'LIGHT RAIN|11 CABINETS LIT|DISTRICT 07|OPEN UNTIL DAWN',
    'arcade.badge': 'AFTER HOURS',
    'cabinet.heading': 'Choose your game',
    'lobby.title': 'The lounge',
    'lobby.players': "Tonight's players",
    'results.title': 'Final tally',
    'tournament.title': 'Tournament Hall',
    'tournament.subtitle': 'Brackets run until the rain stops.',
    'jukebox.title': 'Night console',
    'state.loading': 'Loading',
    'state.connecting': 'Finding the signal',
    'state.empty': 'Quiet tonight',
    'state.error': 'The lights went out',
  },
  materials: {
    // Obsidian felt under black lacquer rails.
    felt: '#0f1d22',
    feltDeep: '#071013',
    feltLine: '#2b5763',
    rail: '#12151b',
    railHighlight: '#3b4452',
    // Wet glass boards: smoked light squares, deep blue-black dark squares, porcelain & onyx pieces.
    boardLight: '#8295a9',
    boardDark: '#263244',
    boardFrame: '#0a0e15',
    boardHighlight: TEAL,
    pieceLight: '#f1f5fa',
    pieceDark: '#0a0d13',
    pieceEdge: '#9fb4cc',
    // Harbour at night.
    water: '#07151f',
    waterDeep: '#030b11',
    gridLine: '#3aa7bd',
    radar: TEAL,
    // Night-lit turf under sodium lamps.
    grass: '#1c4a3b',
    grassDeep: '#113327',
    sand: '#8a7a5d',
    hazard: '#0d3552',
    wall: '#1a1e27',
    wallTop: '#3a4251',
    // Rain-slick rooftops and a starless sky.
    sky: '#05070c',
    skyHorizon: '#1c2636',
    ground: '#1a1f2a',
    groundDeep: '#0b0e14',
    groundEdge: '#5f7188',
    // Rain-slick asphalt.
    asphalt: '#15191f',
    asphaltLine: '#d9e2ea',
    curbA: ROSE,
    curbB: '#dfe6ee',
    offroad: '#0b1014',
    // Cards: cool porcelain faces, smoked-glass backs with a teal thread.
    cardFace: '#eaeff4',
    cardInk: '#0c1016',
    cardBack: '#101722',
    cardBackInk: TEAL,
    // Cool grey stock.
    paper: '#e2e7eb',
    paperInk: '#12161c',
    paperEdge: '#a9b3bd',
    // Stage under a single spotlight.
    stage: '#07090e',
    stageLight: TEAL,
    podium: '#151b26',
    // Screens and bezels.
    screen: '#020305',
    screenGlow: TEAL,
    bezel: '#0c1017',
    // Brushed gunmetal and rose status lamps.
    metal: '#8d99a8',
    metalHighlight: '#e6edf5',
    led: ROSE,
    ledOff: '#2a1620',
  },
  gameMaterials: {
    // A little more separation between glass squares for chess/checkers readability.
    chess: { boardLight: '#8a9db2', boardDark: '#243043' },
    checkers: { boardLight: '#6f8194', boardDark: '#1a2331', pieceLight: '#e9eef4', pieceDark: '#c93a6c' },
    // The racing circuit reads better with a lighter lane line and cool shoulders.
    circuit: { offroad: '#0d1317', asphalt: '#171b22' },
    // Ships: black harbour water under teal sodium light.
    ships: { water: '#0a1822', waterDeep: '#04090f', gridLine: '#46d9ec', radar: '#46d9ec' },
    // Tanks: moonlit rooftops over a foggy skyline.
    tanks: { sky: '#060910', skyHorizon: '#243044', ground: '#1d2330', groundDeep: '#0e1219', groundEdge: '#6f8399' },
    // Party prompt/answer cards are smoked glass under the rain, not porcelain playing cards: the slot
    // colours then read as thin neon tints instead of bright pastel slabs.
    trivia: { cardFace: '#0f1620', cardInk: '#eef3f8' },
    survey: { cardFace: '#0f1620', cardInk: '#eef3f8' },
    deception: { cardFace: '#0f1620', cardInk: '#eef3f8' },
  },
  colorScheme: 'dark',
  metaThemeColor: INK,
  tokens: {
    '--theme-color-scheme': 'dark',
    '--bg-0': INK,
    '--bg-1': '#070a10',
    '--bg-2': '#0b0f17',
    '--bg-3': '#111722',
    '--bg-4': '#18202d',
    '--bg-5': '#222c3b',
    '--glass': 'rgba(10, 14, 21, 0.8)',
    '--glass-strong': 'rgba(7, 10, 16, 0.94)',
    '--glass-light': 'rgba(200, 225, 255, 0.045)',
    '--line': 'rgba(170, 200, 230, 0.1)',
    '--line-strong': 'rgba(170, 200, 230, 0.2)',
    '--line-bright': 'rgba(200, 222, 245, 0.36)',
    '--text-0': '#eef3f8',
    '--text-1': '#c4ced9',
    '--text-2': '#94a1b0',
    '--text-3': '#808d9c',
    '--text-inverse': '#05070b',
    '--pink': ROSE,
    '--cyan': TEAL,
    '--yellow': '#f4c25b',
    '--green': '#4ee0a2',
    '--orange': '#ff8f5a',
    '--purple': '#a292ff',
    '--red': '#ff5468',
    '--blue': '#6aa8ff',
    '--lime': '#b5e861',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': 'var(--cyan)',
    '--accent-2': 'var(--pink)',
    '--accent-deep': '#04121a',
    '--accent-ink': '#02070b',
    '--page-bg': 'var(--bg-0)',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': '#f4c25b',
    '--scrollbar-thumb': 'var(--bg-5)',
    // Space Grotesk carries headings and signage; 'DASCADE Digits' stays first (see THEMING.md).
    '--font-display': "'DASCADE Digits', 'Space Grotesk Variable', 'Inter Variable', system-ui, -apple-system, 'Segoe UI', sans-serif",
    // Tiny caps labels read as refined signage here, not bitmap type.
    '--font-pixel': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-ui': "'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    '--font-tech': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-num': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.08em',
    '--label-tracking': '0.2em',
    '--px': '1px',
    '--radius-sm': '6px',
    '--radius': '10px',
    '--radius-lg': '16px',
    '--shadow-1': '0 1px 0 rgba(0, 0, 0, 0.5), 0 10px 28px rgba(0, 0, 0, 0.45)',
    '--shadow-2': '0 1px 0 rgba(0, 0, 0, 0.5), 0 22px 54px rgba(0, 0, 0, 0.6)',
    '--shadow-3': '0 40px 100px rgba(0, 0, 0, 0.7)',
    '--glow-sm-full': '0 0 12px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--glow-md-full':
      '0 0 16px color-mix(in srgb, var(--accent) 32%, transparent), 0 0 44px color-mix(in srgb, var(--accent) 14%, transparent)',
    '--glow-lg-full':
      '0 0 22px color-mix(in srgb, var(--accent) 40%, transparent), 0 0 80px color-mix(in srgb, var(--accent) 18%, transparent)',
    '--text-glow-full': '0 0 14px color-mix(in srgb, var(--accent) 45%, transparent)',
    '--glow-sm-soft': '0 0 8px color-mix(in srgb, var(--accent) 26%, transparent)',
    '--glow-md-soft': '0 0 10px color-mix(in srgb, var(--accent) 24%, transparent)',
    '--glow-lg-soft': '0 0 14px color-mix(in srgb, var(--accent) 28%, transparent)',
    '--text-glow-soft': '0 0 6px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
    '--ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
    '--ease-spring': 'cubic-bezier(0.3, 1.3, 0.6, 1)',
    '--motion-1': '140ms',
    '--motion-2': '260ms',
    '--motion-3': '480ms',
    '--motion-4': '820ms',
    '--surface-sunken': 'rgba(2, 4, 8, 0.62)',
    '--surface-sunken-soft': 'rgba(2, 4, 8, 0.5)',
    '--surface-raised': 'rgba(200, 225, 255, 0.03)',
    '--surface-hover': 'rgba(200, 225, 255, 0.06)',
    '--panel-bg': 'var(--glass)',
    '--panel-bg-solid': 'var(--glass-strong)',
    '--panel-bg-opaque': 'var(--bg-2)',
    '--panel-sheen':
      'linear-gradient(165deg, rgba(210, 232, 255, 0.07) 0%, rgba(210, 232, 255, 0.015) 32%, rgba(210, 232, 255, 0) 55%)',
    '--panel-border': 'rgba(180, 208, 238, 0.16)',
    '--panel-border-width': '1px',
    '--panel-radius': 'var(--radius)',
    '--panel-shadow': 'inset 0 1px 0 rgba(220, 238, 255, 0.08), inset 0 -1px 0 rgba(0, 0, 0, 0.4), var(--shadow-2)',
    // No backdrop blur over the live rain: the city is already baked out of focus behind menus,
    // and re-blurring an animating layer every frame is the one thing that costs real GPU time.
    '--panel-blur': 'none',
    '--panel-divider': 'var(--line)',
    '--titlebar-bg': 'transparent',
    '--titlebar-fg': 'var(--text-1)',
    '--titlebar-font': 'var(--font-tech)',
    '--titlebar-size': 'var(--fs-xs)',
    '--titlebar-tracking': '0.22em',
    '--titlebar-transform': 'uppercase',
    '--titlebar-marker-size': '6px',
    '--bracket-size': '0px',
    '--bracket-width': '1px',
    '--overlay-scrim': 'rgba(2, 3, 6, 0.74)',
    '--overlay-blur': 'none',
    '--button-font': 'var(--font-tech)',
    '--button-tracking': '0.14em',
    '--button-radius': '8px',
    '--button-edge-width': '1px',
    '--button-bevel-hi': 'rgba(220, 238, 255, 0.1)',
    '--button-bevel-lo': 'rgba(0, 0, 0, 0.28)',
    '--button-hover-filter': 'brightness(1.1)',
    '--button-press-offset': '1px',
    '--button-bg': 'rgba(30, 40, 56, 0.78)',
    '--button-bg-2': 'rgba(16, 22, 32, 0.86)',
    '--button-fg': 'var(--text-0)',
    '--button-edge': 'rgba(190, 215, 240, 0.26)',
    '--button-danger-bg': '#ff7a8a',
    '--button-danger-bg-2': '#e8465a',
    '--button-danger-fg': '#16030a',
    '--button-danger-edge': '#7d1a2a',
    '--button-success-bg': '#79ecbd',
    '--button-success-bg-2': '#3fcf93',
    '--button-success-fg': '#02140c',
    '--button-success-edge': '#146a47',
    '--button-gold-bg': '#f8d68c',
    '--button-gold-bg-2': '#e2ac44',
    '--button-gold-fg': '#1a1100',
    '--button-gold-edge': '#8a6414',
    '--input-bg': 'rgba(2, 4, 8, 0.6)',
    '--input-fg': 'var(--text-0)',
    '--input-border': 'rgba(170, 200, 230, 0.2)',
    '--input-border-hover': 'rgba(200, 222, 245, 0.38)',
    '--input-radius': '8px',
    '--input-inset': 'inset 0 1px 2px rgba(0, 0, 0, 0.5)',
    '--input-placeholder': 'var(--text-3)',
    '--control-track': 'rgba(2, 4, 8, 0.7)',
    '--control-track-edge': 'rgba(190, 215, 240, 0.28)',
    '--shell-bar-bg': 'linear-gradient(180deg, rgba(4, 6, 10, 0.94), rgba(4, 6, 10, 0.84))',
    '--shell-bar-border': 'rgba(170, 200, 230, 0.1)',
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '0.55',
    '--shell-bar-solid': 'rgba(4, 6, 10, 0.95)',
    '--shell-dock-bg': 'rgba(6, 9, 14, 0.94)',
    '--shell-dock-border': 'var(--line-strong)',
    '--shell-dock-shadow': '0 -14px 40px rgba(0, 0, 0, 0.5)',
    '--shell-dock-blur': 'none',
    '--toast-bg': 'rgba(8, 11, 17, 0.9)',
    '--toast-shadow': 'var(--shadow-2)',
    '--hud-bg': 'rgba(6, 9, 14, 0.66)',
    '--hud-bg-strong': 'var(--glass-strong)',
    '--hud-border': 'rgba(170, 200, 230, 0.18)',
    '--hud-fg': 'var(--text-0)',
    '--hud-muted': 'var(--text-2)',
    '--hud-radius': '8px',
    '--hud-shadow': 'var(--shadow-1)',
    '--hud-blur': 'blur(14px) saturate(1.2)',
    '--arcade-floor-bg': '#020306',
    '--cabinet-body': '#131924',
    '--cabinet-body-2': '#06080d',
    '--cabinet-edge': 'rgba(190, 215, 240, 0.2)',
    '--cabinet-bezel': '#0a0d14',
    '--cabinet-screen-bg': '#000',
    '--cabinet-glass':
      'linear-gradient(118deg, rgba(220, 238, 255, 0.16) 0%, rgba(220, 238, 255, 0.04) 30%, transparent 31%, transparent 72%, rgba(220, 238, 255, 0.05) 73%, transparent 80%)',
    '--cabinet-screen-inset': 'inset 0 0 0 1px rgba(200, 225, 255, 0.08), inset 0 0 24px rgba(0, 0, 0, 0.6)',
    '--cabinet-shadow': '0 36px 90px rgba(0, 0, 0, 0.72)',
    '--marquee-font': 'var(--font-tech)',
    '--marquee-ink': '#fff',
    '--marquee-outline': '#050709',
    '--marquee-sheen': 'linear-gradient(180deg, rgba(220, 238, 255, 0.18), rgba(220, 238, 255, 0) 46%)',
    '--marquee-tracking': '0.12em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.2)',
    '--scanline-pitch': '3px',
    '--scanline-opacity-full': '0.22',
    '--scanline-opacity-soft': '0.1',
    '--grid-ink': 'rgba(170, 200, 230, 0.018)',
    '--grid-size': '32px',
    '--noise-opacity': '0.05',
    '--vignette-edge': 'rgba(0, 0, 0, 0.7)',
  },
  overrides: {
    '--title-shadow': '0 1px 0 rgba(0, 0, 0, 0.8), 0 0 28px rgba(70, 217, 236, 0.18)',
    '--bracket-color': 'rgba(190, 215, 240, 0.4)',
    '--titlebar-marker': ROSE,
    '--input-focus-ring': 'rgba(70, 217, 236, 0.55)',
    '--shell-bar-rule': 'linear-gradient(90deg, transparent, rgba(70, 217, 236, 0.55) 30%, rgba(255, 77, 141, 0.55) 70%, transparent)',
  },
  renderer: {
    background: INK,
    surface: '#0b0f17',
    text: '#eef3f8',
    textMuted: '#94a1b0',
    line: '#9fb4cc',
    accent: TEAL,
    accent2: ROSE,
    gridAlpha: 0.05,
    scanlines: 0.06,
    scanlinesSoft: 0.03,
    glow: 0.8,
    glowSoft: 0.4,
  },
};
