/**
 * Saturday Morning — loud, colourful 1990s TV studio / game-show / cartoon energy (original; no
 * network branding). Electric-blue studio, grape-purple set pieces with thick ink outlines and
 * hard offset shadows, candy-coloured buttons, a chunky rounded display face (Lilita One, OFL)
 * and zero glow: everything is flat, bold and printed. Competitive games calm down: the game
 * backdrop is a quiet deep indigo and every material keeps boards readable.
 *
 * The structural half (studio set, drifting shapes/squiggles, checkerboards, scoreboards,
 * confetti) is apps/web/src/themes/saturday-morning/.
 */
import type { ThemeDefinition } from '../types.ts';
import { DELTA_NEON } from './delta-neon.ts';

const LILITA = "'Lilita One', 'Arial Rounded MT Bold', 'Trebuchet MS', 'Segoe UI', system-ui, sans-serif";
const INK = '#120833';

export const SATURDAY_MORNING: ThemeDefinition = {
  id: 'saturday-morning',
  name: 'Saturday Morning',
  description:
    'A loud 1990s TV studio: bright geometric sets, checkerboards, squiggles, game-show scoreboards, ridiculous buzzers and confetti. Boards stay calm and readable.',
  meta: {
    era: '199X · Live from Studio B',
    tagline: 'Cartoons, buzzers and a studio audience. Everybody wins something!',
    swatches: ['#2233b8', '#28157f', '#ffe14d', '#ff4fa3'],
    family: 'comedy',
  },
  effects: { surface: 'plastic', crt: 0, grain: 0, analog: 0, ambient: 'confetti', visualizer: 'blocks', transition: 'wipe' },
  colorScheme: 'dark',
  metaThemeColor: '#2233b8',
  materials: {
    // Game-show table: bright teal felt, candy-red rail.
    felt: '#0f8f86',
    feltDeep: '#0a6861',
    feltLine: '#7ff5e8',
    rail: '#d9345f',
    railHighlight: '#ff8fb3',
    // Board: sunny cream / studio purple, chunky frame.
    boardLight: '#ffe9b0',
    boardDark: '#7b4ad6',
    boardFrame: INK,
    boardHighlight: '#3ee07a',
    pieceLight: '#ffffff',
    pieceDark: '#1c0f40',
    pieceEdge: INK,
    // Cartoon water.
    water: '#1f7ae0',
    waterDeep: '#1257a8',
    gridLine: '#bfe6ff',
    radar: '#ffe14d',
    // Putt: toy-box turf, crayon sand, bubblegum water hazard, block walls.
    grass: '#4cc95a',
    grassDeep: '#2f9e44',
    sand: '#ffd98a',
    hazard: '#2ec5ff',
    wall: '#ff5c8a',
    wallTop: '#ffd1e0',
    // Tanks: afternoon-cartoon sky, bright hills.
    sky: '#58b8ff',
    skyHorizon: '#bfe8ff',
    ground: '#8c5a2b',
    groundDeep: '#5e3a1a',
    groundEdge: '#5ad05f',
    // Racing: toy track.
    asphalt: '#3d3a5c',
    asphaltLine: '#ffffff',
    curbA: '#ff4d5e',
    curbB: '#ffffff',
    offroad: '#46b04f',
    // Cards: white with ink; backs = checkerboard purple/yellow feel.
    cardFace: '#ffffff',
    cardInk: '#1a0b3d',
    cardBack: '#e0237a',
    cardBackInk: '#ffe14d',
    // Paper: cartoon cue card.
    paper: '#fffbe8',
    paperInk: '#1a0b3d',
    paperEdge: '#ffcf33',
    // Studio.
    stage: '#1c1170',
    stageLight: '#ffe14d',
    podium: '#e0237a',
    // TV screens.
    screen: '#10083a',
    screenGlow: '#2ee6e6',
    bezel: '#ff8c1a',
    // Toy hardware.
    metal: '#ffcf33',
    metalHighlight: '#fff4b8',
    led: '#ff4fa3',
    ledOff: '#4a1f5e',
  },
  gameMaterials: {
    // Competitive boards: classic, calm contrast.
    chess: { boardLight: '#fff1c9', boardDark: '#6a44c9', boardHighlight: '#ffcf33' },
    checkers: { boardLight: '#ffdf6b', boardDark: '#d9345f' },
    ships: { water: '#1a5fc2', waterDeep: '#0e3f8a', gridLine: '#a8dcff', radar: '#ffe14d' },
    tanks: { sky: '#6cc4ff', skyHorizon: '#d4f0ff' },
    putt: { sky: '#2a4fd0', skyHorizon: '#4f86ee' },
    trivia: { stage: '#221590', stageLight: '#ffe14d', podium: '#ff4fa3' },
    wheel: { stage: '#1c1170', metal: '#ffe14d', led: '#ffffff' },
    bingo: { cardFace: '#ffffff', cardBack: '#2ec5c5', paperEdge: '#ff4fa3' },
    dasino: { felt: '#0b7f78', feltDeep: '#075c57', rail: '#7b2fd6' },
  },
  copy: {
    'arcade.tagline': 'Live from Studio B!',
    'arcade.status': 'ON AIR|STUDIO AUDIENCE READY|BUZZERS CHARGED|CONFETTI LOADED|NOW IN COLOR|COMING UP NEXT: YOU',
    'arcade.badge': 'LIVE!',
    'cabinet.heading': 'Pick a show!',
    'lobby.title': 'Green room',
    'lobby.players': 'Tonight’s contestants',
    'results.title': 'And the winner is…',
    'tournament.title': 'The Big Championship Show',
    'tournament.subtitle': 'Brackets, buzzers and one very large trophy',
    'settings.title': 'Control booth',
    'jukebox.title': 'Music Video Booth',
    'state.loading': 'Stay tuned…',
    'state.connecting': 'Warming up the studio',
    'state.empty': 'Nobody here yet. Cue the crickets!',
    'state.error': 'We are experiencing technical difficulties',
  },
  tokens: {
    ...DELTA_NEON.tokens,
    '--theme-color-scheme': 'dark',
    '--bg-0': '#140a4a',
    '--bg-1': '#1b0f62',
    '--bg-2': '#23147a',
    '--bg-3': '#2e1b94',
    '--bg-4': '#3a24ad',
    '--bg-5': '#4a31c4',
    '--glass': '#28157f',
    '--glass-strong': '#1f1070',
    '--glass-light': 'rgba(255, 255, 255, 0.08)',
    '--line': 'rgba(210, 205, 255, 0.24)',
    '--line-strong': 'rgba(225, 220, 255, 0.42)',
    '--line-bright': 'rgba(255, 255, 255, 0.72)',
    '--text-0': '#ffffff',
    '--text-1': '#f0eeff',
    '--text-2': '#d6d2ff',
    '--text-3': '#c2bcf5',
    '--text-inverse': '#1a0b3d',
    '--pink': '#ff4fa3',
    '--cyan': '#2ee6e6',
    '--yellow': '#ffe14d',
    '--green': '#4dea7a',
    '--orange': '#ff9a2e',
    '--purple': '#c29cff',
    '--red': '#ff5d6c',
    '--blue': '#66c2ff',
    '--lime': '#c1f23a',
    '--shade': INK,
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': 'var(--yellow)',
    '--accent-2': 'var(--pink)',
    '--accent-deep': '#2a1070',
    '--accent-ink': '#1a0b3d',
    '--page-bg': '#2233b8',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': '#ffffff',
    '--scrollbar-thumb': '#ff4fa3',
    '--font-display': `'DASCADE Digits', ${LILITA}`,
    '--font-pixel': LILITA,
    '--font-ui': "'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    '--font-tech': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-num': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.01em',
    '--label-tracking': '0.08em',
    '--px': '3px',
    '--radius-sm': '8px',
    '--radius': '16px',
    '--radius-lg': '26px',
    '--shadow-1': `3px 3px 0 ${INK}`,
    '--shadow-2': `5px 6px 0 ${INK}`,
    '--shadow-3': `8px 10px 0 rgba(18, 8, 51, 0.92)`,
    '--glow-sm-full': '0 0 0 transparent',
    '--glow-md-full': '0 0 0 transparent',
    '--glow-lg-full': '0 0 0 transparent',
    '--text-glow-full': 'none',
    '--glow-sm-soft': '0 0 0 transparent',
    '--glow-md-soft': '0 0 0 transparent',
    '--glow-lg-soft': '0 0 0 transparent',
    '--text-glow-soft': 'none',
    '--ease-out': 'cubic-bezier(0.2, 0.9, 0.3, 1)',
    '--ease-in-out': 'cubic-bezier(0.6, 0, 0.4, 1)',
    '--ease-spring': 'cubic-bezier(0.3, 1.8, 0.5, 1)',
    '--motion-1': '110ms',
    '--motion-2': '200ms',
    '--motion-3': '380ms',
    '--motion-4': '620ms',
    '--surface-sunken': 'rgba(14, 6, 52, 0.55)',
    '--surface-sunken-soft': 'rgba(14, 6, 52, 0.4)',
    '--surface-raised': 'rgba(255, 255, 255, 0.07)',
    '--surface-hover': 'rgba(255, 255, 255, 0.12)',
    '--panel-bg': '#28157f',
    '--panel-bg-solid': '#28157f',
    '--panel-bg-opaque': '#28157f',
    '--panel-sheen': 'none',
    '--panel-border': INK,
    '--panel-border-width': '3px',
    '--panel-radius': 'var(--radius)',
    '--panel-shadow': `inset 0 3px 0 rgba(255, 255, 255, 0.14), 6px 7px 0 ${INK}`,
    '--panel-blur': 'none',
    '--panel-divider': 'rgba(18, 8, 51, 0.7)',
    '--titlebar-bg': '#ffe14d',
    '--titlebar-fg': '#1a0b3d',
    '--titlebar-font': LILITA,
    '--titlebar-size': 'var(--fs-md)',
    '--titlebar-tracking': '0.03em',
    '--titlebar-transform': 'none',
    '--titlebar-marker-size': '12px',
    '--bracket-size': '0px',
    '--bracket-width': '0px',
    '--overlay-scrim': 'rgba(16, 6, 60, 0.74)',
    '--overlay-blur': 'none',
    '--button-font': 'var(--font-display)',
    '--button-tracking': '0.03em',
    '--button-radius': '14px',
    '--button-edge-width': '3px',
    '--button-bevel-hi': 'rgba(255, 255, 255, 0.45)',
    '--button-bevel-lo': 'rgba(18, 8, 51, 0.3)',
    '--button-hover-filter': 'brightness(1.07) saturate(1.1)',
    '--button-press-offset': '3px',
    '--button-bg': '#7048f0',
    '--button-bg-2': '#5430d8',
    '--button-fg': '#ffffff',
    '--button-edge': INK,
    '--button-danger-bg': '#ff7d89',
    '--button-danger-bg-2': '#ff4d5e',
    '--button-danger-fg': '#2a0010',
    '--button-danger-edge': INK,
    '--button-success-bg': '#7ff59e',
    '--button-success-bg-2': '#3ddc6a',
    '--button-success-fg': '#032010',
    '--button-success-edge': INK,
    '--button-gold-bg': '#ffd36b',
    '--button-gold-bg-2': '#ffae1a',
    '--button-gold-fg': '#2a1400',
    '--button-gold-edge': INK,
    '--input-bg': '#160b56',
    '--input-fg': '#ffffff',
    '--input-border': INK,
    '--input-border-hover': '#ffe14d',
    '--input-radius': '12px',
    '--input-inset': 'inset 0 3px 0 rgba(0, 0, 0, 0.3)',
    '--input-placeholder': '#b5aef0',
    '--control-track': '#160b56',
    '--control-track-edge': INK,
    '--shell-bar-bg': '#1a0f66',
    '--shell-bar-border': INK,
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '1',
    '--shell-bar-solid': '#1a0f66',
    '--shell-dock-bg': '#1f1070',
    '--shell-dock-border': INK,
    '--shell-dock-shadow': `0 -4px 0 ${INK}`,
    '--shell-dock-blur': 'none',
    '--toast-bg': '#28157f',
    '--toast-shadow': `5px 5px 0 ${INK}`,
    '--hud-bg': 'rgba(24, 12, 90, 0.92)',
    '--hud-bg-strong': '#1c0f6c',
    '--hud-border': INK,
    '--hud-fg': '#ffffff',
    '--hud-muted': 'var(--text-2)',
    '--hud-radius': '12px',
    '--hud-shadow': `3px 4px 0 ${INK}`,
    '--hud-blur': 'none',
    '--arcade-floor-bg': '#1d2aa6',
    '--cabinet-body': '#7048f0',
    '--cabinet-body-2': '#3a1ea8',
    '--cabinet-edge': INK,
    '--cabinet-bezel': '#1a0b3d',
    '--cabinet-screen-bg': '#0c0630',
    '--cabinet-glass': 'linear-gradient(125deg, rgba(255, 255, 255, 0.28) 0%, rgba(255, 255, 255, 0.08) 22%, transparent 23%)',
    '--cabinet-screen-inset': `inset 0 0 0 3px ${INK}`,
    '--cabinet-shadow': `10px 12px 0 rgba(18, 8, 51, 0.85)`,
    '--marquee-font': 'var(--font-display)',
    '--marquee-ink': '#ffffff',
    '--marquee-outline': INK,
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0) 45%)',
    '--marquee-tracking': '0.02em',
    '--scanline-ink': 'rgba(0, 0, 0, 0)',
    '--scanline-pitch': '3px',
    '--scanline-opacity-full': '0',
    '--scanline-opacity-soft': '0',
    '--grid-ink': 'rgba(255, 255, 255, 0.05)',
    '--grid-size': '28px',
    '--noise-opacity': '0',
    '--vignette-edge': 'rgba(14, 6, 60, 0.4)',
  },
  overrides: {
    '--title-shadow': `3px 3px 0 ${INK}, 6px 6px 0 #ff4fa3`,
    '--button-primary-bg': '#fff07a',
    '--button-primary-bg-2': '#ffd21a',
    '--button-primary-fg': '#1a0b3d',
    '--button-primary-edge': INK,
    '--button-primary-glow': 'transparent',
    '--button-secondary-edge': INK,
    '--bracket-color': '#ffe14d',
    '--titlebar-marker': '#ff4fa3',
    '--panel-glow-border': INK,
    '--panel-glow-shadow': `inset 0 3px 0 rgba(255, 255, 255, 0.14), 6px 7px 0 ${INK}`,
    '--control-accent': '#ffe14d',
    '--control-accent-ink': '#1a0b3d',
    '--input-focus-ring': '#ffe14d',
    '--shell-bar-rule':
      'repeating-linear-gradient(90deg, #ffe14d 0 18px, #ff4fa3 18px 36px, #2ee6e6 36px 54px, #4dea7a 54px 72px)',
    '--game-backdrop':
      'radial-gradient(900px 420px at 50% -10%, rgba(102, 194, 255, 0.14), transparent 65%), linear-gradient(180deg, rgba(28, 20, 128, 0.9), rgba(20, 12, 92, 0.96) 75%)',
  },
  renderer: {
    background: '#170d5e',
    surface: '#28157f',
    text: '#ffffff',
    textMuted: '#d6d2ff',
    line: '#d6d2ff',
    accent: '#ffe14d',
    accent2: '#ff4fa3',
    gridAlpha: 0.12,
    scanlines: 0,
    scanlinesSoft: 0,
    glow: 0.2,
    glowSoft: 0.1,
  },
};
