/**
 * Shareware Casino '97 — "DASCADE FUN PACK v3.7 · REGISTERED VERSION".
 *
 * A bargain-bin casino / shareware CD-ROM compilation running on a late-90s desktop: putty-beige
 * application windows with bevelled edges and burgundy title bars, brass/gold trim, glossy red
 * physical buttons, white inset text fields, tiny red LEDs, a gaudy casino carpet behind it all.
 *
 * Structure: window CHROME (frames, title bars, buttons, fields, dialogs) is beige/brass; window
 * CONTENT stays a dark "felt/CRT" well so every game's own colours (and the catalog accents) keep
 * their contrast. Dialogs go fully beige ("weirdly serious settings") via the skin, which re-inks
 * their text locally. Original CSS only — no operating-system or casino-software artwork.
 */
import type { ThemeDefinition } from '../types.ts';

/* Chrome swatches (kept here so the skin, tokens and materials agree). */
const PUTTY = '#d9d1bd';
const PUTTY_LIGHT = '#fbf6e8';
const PUTTY_SHADOW = '#8a806a';
const PUTTY_DARK = '#3e372b';
const BRASS = '#c9a24a';
const BRASS_LIGHT = '#f6dd8c';
const BRASS_DARK = '#6e4f14';
const OXBLOOD = '#7a0f1c';
const CASINO_RED = '#d8262a';
const INK = '#1a140b';

export const SHAREWARE_97: ThemeDefinition = {
  id: 'shareware-97',
  name: "Shareware Casino '97",
  description:
    'A bargain-bin casino CD-ROM on a late-90s desktop: putty-beige windows with burgundy title bars, brass trim, glossy red buttons, amber LCDs and a gaudy casino carpet.',
  meta: {
    era: '1997 · Bargain-bin CD-ROM',
    tagline: 'DASCADE FUN PACK v3.7 — registered version.',
    swatches: ['#3a0a14', PUTTY, '#f2c14e', CASINO_RED],
    family: 'retro-desktop',
  },
  effects: { surface: 'bevel', crt: 0.3, grain: 0.08, analog: 0, ambient: 'sparkle', visualizer: 'lcd', transition: 'boot' },
  copy: {
    'arcade.tagline': 'Fun Pack v3.7 · Delta Alpha Sierra',
    'arcade.status': 'MODEM READY|{cabinets} CABINETS ONLINE|NETWORK {online}|{rooms} ROOMS LIVE|1-30 USERS|SOUND CARD OK|FULL VERSION',
    'arcade.badge': 'REGISTERED COPY',
    'cabinet.heading': 'Select a program',
    'lobby.title': 'Network Lobby',
    'lobby.players': 'Connected users',
    'results.title': 'Final Tally',
    'tournament.title': 'Tournament Center Deluxe',
    'tournament.subtitle': 'Brackets, byes and bragging rights. Now in 256 colors.',
    'settings.title': 'Configuration Utility',
    'jukebox.title': 'DAS-CD Player 3.7',
    'state.loading': 'Loading from CD-ROM…',
    'state.connecting': 'Dialing in…',
    'state.empty': 'Nothing here yet. This slot intentionally left blank.',
    'state.error': 'Unexpected Fun Fault',
  },
  materials: {
    // Casino table: classic green felt, gold inlay line, brass rail.
    felt: '#12703f',
    feltDeep: '#0a4527',
    feltLine: '#e8c35a',
    rail: '#8f6218',
    railHighlight: '#f2cf6b',
    // Premium shareware chess: maple and walnut in a brass frame.
    boardLight: '#ecd6a4',
    boardDark: '#9a5a2c',
    boardFrame: BRASS,
    boardHighlight: '#ffe14d',
    pieceLight: '#fff8e6',
    pieceDark: '#24160d',
    pieceEdge: '#0e0804',
    // VGA ocean with radar-green sweep.
    water: '#0c3f73',
    waterDeep: '#06254a',
    gridLine: '#6fd6ff',
    radar: '#3dff7f',
    // 1997 CD mini-golf: saturated turf, velvet bumpers with gold trim.
    grass: '#2fae3a',
    grassDeep: '#1e7c2a',
    sand: '#f0d48a',
    hazard: '#1f6fd9',
    wall: '#7a1f2b',
    wallTop: '#f2c14e',
    // Jewel-case artillery: pre-rendered sunset sky over brown hills.
    sky: '#1d0f45',
    skyHorizon: '#e8607a',
    ground: '#6e4a28',
    groundDeep: '#3b2513',
    groundEdge: '#86d44a',
    // Ridiculously ambitious shareware racer.
    asphalt: '#3a3942',
    asphaltLine: '#ffe14d',
    curbA: CASINO_RED,
    curbB: '#fff7e3',
    offroad: '#2e7a38',
    // Card stock: ivory faces, burgundy backs with gold ink.
    cardFace: '#fffdf5',
    cardInk: INK,
    cardBack: '#8a1020',
    cardBackInk: '#f2c14e',
    // Manual pages / prompt cards.
    paper: '#f7f0dc',
    paperInk: '#1d160c',
    paperEdge: '#c9b98f',
    // Strange 90s party-game compilation stage.
    stage: '#1f0b35',
    stageLight: '#ffd23a',
    podium: '#8a1628',
    // Tiny CRTs in beige plastic.
    screen: '#07150f',
    screenGlow: '#5dff9a',
    bezel: PUTTY,
    // Brass hardware and red LEDs.
    metal: BRASS,
    metalHighlight: '#fff0b8',
    led: '#ff3b2f',
    ledOff: '#4a1512',
  },
  gameMaterials: {
    // "DAS Chess Deluxe — Marble Edition".
    chess: { boardLight: '#ece5d3', boardDark: '#4f806a', boardFrame: BRASS, boardHighlight: '#ffe14d' },
    // Checkers keeps the parlour wood (darker walnut so red/black pieces pop).
    checkers: { boardLight: '#e6c98f', boardDark: '#6e3b1c' },
    // DASQuest: a forgotten multimedia adventure CD — parchment and a beige monitor.
    quest: { paper: '#efe2bf', paperInk: '#2a1c0c', paperEdge: '#a8894e', screen: '#0a0f1c', screenGlow: '#8fb8ff' },
    // DAStravaganza compilation: purple game-show stage, burgundy podiums, gold lights.
    trivia: { stage: '#240c3d', podium: '#8a1628', stageLight: '#ffd23a' },
    survey: { stage: '#240c3d', podium: '#8a1628', stageLight: '#ffd23a' },
    // "Bizarre 1997 CD mini-golf": velvet bumpers, bright gold trim, a pre-rendered midnight-teal void.
    putt: { wall: '#8a1628', wallTop: '#ffd54a', sky: '#0e3140', stage: '#0e3140' },
    // The racer ships with a sunset skybox too.
    circuit: { sky: '#241255', skyHorizon: '#ff7a59', offroad: '#2b6e34' },
  },
  colorScheme: 'dark',
  metaThemeColor: OXBLOOD,
  tokens: {
    '--theme-color-scheme': 'dark',
    // Window CONTENT wells: dark casino felt, so game art and catalog accents keep their contrast.
    '--bg-0': '#0a0f0d',
    '--bg-1': '#0e1714',
    '--bg-2': '#13201b',
    '--bg-3': '#1a2b24',
    '--bg-4': '#243a31',
    '--bg-5': '#334d42',
    '--glass': 'rgba(16, 30, 25, 0.94)',
    '--glass-strong': 'rgba(12, 22, 19, 0.97)',
    '--glass-light': 'rgba(255, 240, 200, 0.06)',
    '--line': 'rgba(242, 207, 107, 0.16)',
    '--line-strong': 'rgba(242, 207, 107, 0.32)',
    '--line-bright': 'rgba(246, 221, 140, 0.6)',
    '--text-0': '#fff7e3',
    '--text-1': '#ecdfbf',
    '--text-2': '#cbbd95',
    '--text-3': '#ad9f7c',
    '--text-inverse': INK,
    '--pink': '#ff5fa8',
    '--cyan': '#40d9cf',
    '--yellow': '#ffd23a',
    '--green': '#52e07c',
    '--orange': '#ff9a3c',
    '--purple': '#b890ff',
    '--red': '#ff4f4a',
    '--blue': '#6aa8ff',
    '--lime': '#b6e84a',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': '#f2c14e',
    '--accent-2': CASINO_RED,
    '--accent-deep': '#2a1406',
    '--accent-ink': '#1c0f00',
    '--page-bg': '#2a0810',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': '#ffe14d',
    '--scrollbar-thumb': PUTTY_SHADOW,
    '--font-display': "'DASCADE Digits', 'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--font-pixel': "'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--font-ui': "Tahoma, Verdana, 'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif",
    '--font-tech': "Verdana, Tahoma, 'Inter Variable', system-ui, sans-serif",
    '--font-num': "Tahoma, 'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.02em',
    '--label-tracking': '0.1em',
    '--px': '2px',
    '--radius-sm': '0px',
    '--radius': '2px',
    '--radius-lg': '3px',
    '--shadow-1': '2px 2px 0 rgba(0, 0, 0, 0.55)',
    '--shadow-2': '4px 4px 0 rgba(0, 0, 0, 0.5), 0 14px 30px rgba(0, 0, 0, 0.45)',
    '--shadow-3': '6px 6px 0 rgba(0, 0, 0, 0.5), 0 30px 70px rgba(0, 0, 0, 0.6)',
    '--glow-sm-full': '0 0 8px color-mix(in srgb, var(--accent) 38%, transparent)',
    '--glow-md-full': '0 0 14px color-mix(in srgb, var(--accent) 40%, transparent), 0 0 30px color-mix(in srgb, var(--accent) 16%, transparent)',
    '--glow-lg-full': '0 0 20px color-mix(in srgb, var(--accent) 48%, transparent), 0 0 56px color-mix(in srgb, var(--accent) 22%, transparent)',
    '--text-glow-full': '0 0 10px color-mix(in srgb, var(--accent) 55%, transparent)',
    '--glow-sm-soft': '0 0 6px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--glow-md-soft': '0 0 8px color-mix(in srgb, var(--accent) 28%, transparent)',
    '--glow-lg-soft': '0 0 12px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--text-glow-soft': '0 0 5px color-mix(in srgb, var(--accent) 35%, transparent)',
    '--ease-out': 'cubic-bezier(0.25, 0.8, 0.3, 1)',
    '--ease-in-out': 'cubic-bezier(0.6, 0, 0.4, 1)',
    '--ease-spring': 'cubic-bezier(0.3, 1.35, 0.6, 1)',
    '--motion-1': '90ms',
    '--motion-2': '160ms',
    '--motion-3': '300ms',
    '--motion-4': '520ms',
    '--surface-sunken': 'rgba(4, 9, 7, 0.72)',
    '--surface-sunken-soft': 'rgba(4, 9, 7, 0.55)',
    '--surface-raised': 'rgba(255, 240, 200, 0.045)',
    '--surface-hover': 'rgba(255, 225, 140, 0.1)',
    '--panel-bg': 'linear-gradient(180deg, #16261f, #0f1b17)',
    '--panel-bg-solid': '#122019',
    '--panel-bg-opaque': '#122019',
    '--panel-sheen': 'none',
    '--panel-border': PUTTY,
    '--panel-border-width': '4px',
    '--panel-radius': '0px',
    '--panel-shadow': `0 0 0 1px ${PUTTY_DARK}, inset 0 0 0 1px ${PUTTY_DARK}, inset 2px 2px 0 1px rgba(0, 0, 0, 0.45), 5px 5px 0 rgba(0, 0, 0, 0.45)`,
    '--panel-blur': 'none',
    '--panel-divider': 'rgba(242, 207, 107, 0.22)',
    '--titlebar-bg': `linear-gradient(90deg, ${OXBLOOD} 0%, #a81b24 55%, ${CASINO_RED} 100%)`,
    '--titlebar-fg': '#fff3c8',
    '--titlebar-font': "Tahoma, Verdana, 'Inter Variable', system-ui, sans-serif",
    '--titlebar-size': 'var(--fs-sm)',
    '--titlebar-tracking': '0.02em',
    '--titlebar-transform': 'none',
    '--titlebar-marker-size': '12px',
    '--bracket-size': '0px',
    '--bracket-width': '0px',
    '--overlay-scrim': 'rgba(20, 4, 8, 0.66)',
    '--overlay-blur': 'none',
    '--button-font': "Tahoma, Verdana, 'Inter Variable', system-ui, sans-serif",
    '--button-tracking': '0.01em',
    '--button-radius': '2px',
    '--button-edge-width': '1px',
    '--button-bevel-hi': 'rgba(255, 255, 255, 0.85)',
    '--button-bevel-lo': 'rgba(60, 48, 30, 0.55)',
    '--button-hover-filter': 'brightness(1.06)',
    '--button-press-offset': '1px',
    '--button-bg': '#ebe4d2',
    '--button-bg-2': '#c9c0aa',
    '--button-fg': INK,
    '--button-edge': PUTTY_DARK,
    '--button-danger-bg': '#9c2a22',
    '--button-danger-bg-2': '#5e1010',
    '--button-danger-fg': '#fff0e0',
    '--button-danger-edge': '#2a0505',
    '--button-success-bg': '#7be895',
    '--button-success-bg-2': '#1f9e4a',
    '--button-success-fg': '#03170a',
    '--button-success-edge': '#0b4d22',
    '--button-gold-bg': BRASS_LIGHT,
    '--button-gold-bg-2': '#d4a022',
    '--button-gold-fg': '#231500',
    '--button-gold-edge': BRASS_DARK,
    '--input-bg': '#fffdf5',
    '--input-fg': INK,
    '--input-border': PUTTY_DARK,
    '--input-border-hover': '#000',
    '--input-radius': '0px',
    '--input-inset': `inset 2px 2px 0 ${PUTTY_SHADOW}, inset -1px -1px 0 ${PUTTY_LIGHT}`,
    '--input-placeholder': '#6b6250',
    '--control-track': '#08110e',
    '--control-track-edge': PUTTY_SHADOW,
    '--shell-bar-bg': `linear-gradient(90deg, #5e0a15 0%, ${OXBLOOD} 30%, #a81b24 75%, #c0262a 100%)`,
    '--shell-bar-border': PUTTY_DARK,
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '1',
    '--shell-bar-solid': OXBLOOD,
    '--shell-dock-bg': PUTTY,
    '--shell-dock-border': PUTTY_LIGHT,
    '--shell-dock-shadow': `0 -1px 0 ${PUTTY_DARK}, 0 -8px 20px rgba(0, 0, 0, 0.35)`,
    '--shell-dock-blur': 'none',
    '--toast-bg': '#13211c',
    '--toast-shadow': `0 0 0 1px ${PUTTY_DARK}, 4px 4px 0 rgba(0, 0, 0, 0.5)`,
    '--hud-bg': 'rgba(8, 14, 12, 0.9)',
    '--hud-bg-strong': '#0b1512',
    '--hud-border': BRASS,
    '--hud-fg': '#fff7e3',
    '--hud-muted': '#cbbd95',
    '--hud-radius': '0px',
    '--hud-shadow': `0 0 0 1px ${BRASS_DARK}, 3px 3px 0 rgba(0, 0, 0, 0.5)`,
    '--hud-blur': 'none',
    '--arcade-floor-bg': 'transparent',
    '--cabinet-body': '#5a1a1f',
    '--cabinet-body-2': '#2a0a0e',
    '--cabinet-edge': 'rgba(246, 221, 140, 0.55)',
    '--cabinet-bezel': '#1a1410',
    '--cabinet-screen-bg': '#030806',
    '--cabinet-glass': 'linear-gradient(122deg, rgba(255, 255, 255, 0.22) 0%, rgba(255, 255, 255, 0.06) 24%, transparent 25%)',
    '--cabinet-screen-inset': `inset 0 0 0 2px ${PUTTY_DARK}, inset 2px 2px 0 3px rgba(0, 0, 0, 0.5)`,
    '--cabinet-shadow': '0 26px 60px rgba(0, 0, 0, 0.6)',
    '--marquee-font': "'DASCADE Digits', 'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--marquee-ink': '#fff3c8',
    '--marquee-outline': '#3a0610',
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.34), rgba(255, 255, 255, 0) 45%)',
    '--marquee-tracking': '0.03em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.26)',
    '--scanline-pitch': '2px',
    '--scanline-opacity-full': '0.35',
    '--scanline-opacity-soft': '0.15',
    '--grid-ink': 'transparent',
    '--grid-size': '24px',
    '--noise-opacity': '0.035',
    '--vignette-edge': 'rgba(10, 0, 3, 0.6)',
  },
  overrides: {
    // Primary = the big glossy red "physical" button (skin adds the dome highlight).
    '--button-primary-bg': '#ff6a55',
    '--button-primary-bg-2': '#c4121c',
    '--button-primary-fg': '#fffaf0',
    '--button-primary-edge': '#4a060b',
    '--button-primary-glow': 'rgba(255, 70, 50, 0.28)',
    '--button-secondary-edge': PUTTY_DARK,
    '--title-shadow': `0 1px 0 ${BRASS_LIGHT}, 0 2px 0 ${BRASS}, 0 3px 0 ${BRASS_DARK}, 0 4px 0 #3a2606, 0 7px 8px rgba(0, 0, 0, 0.55)`,
    '--bracket-color': BRASS,
    '--titlebar-marker': BRASS_LIGHT,
    '--panel-glow-border': BRASS,
    '--panel-glow-shadow': `0 0 0 1px ${BRASS_DARK}, inset 0 0 0 1px ${BRASS_DARK}, inset 2px 2px 0 1px rgba(0, 0, 0, 0.45), 5px 5px 0 rgba(0, 0, 0, 0.45)`,
    '--control-accent': '#f2c14e',
    '--control-accent-ink': '#1c0f00',
    '--input-focus-ring': '0 0 0 2px #ffe14d',
    '--game-backdrop':
      'radial-gradient(ellipse 120% 70% at 50% -10%, rgba(242, 193, 78, 0.12), transparent 60%), radial-gradient(ellipse 90% 60% at 50% 115%, rgba(216, 38, 42, 0.14), transparent 60%), linear-gradient(180deg, rgba(27, 10, 14, 0.86) 0%, rgba(16, 9, 10, 0.9) 55%, rgba(10, 6, 7, 0.94) 100%)',
    '--shell-bar-rule': `linear-gradient(90deg, ${BRASS_DARK}, ${BRASS_LIGHT} 50%, ${BRASS_DARK})`,
  },
  renderer: {
    background: '#0b1411',
    surface: '#13201b',
    text: '#fff7e3',
    textMuted: '#cbbd95',
    line: '#e8c35a',
    accent: '#f2c14e',
    accent2: CASINO_RED,
    gridAlpha: 0.08,
    scanlines: 0.14,
    scanlinesSoft: 0.06,
    glow: 0.6,
    glowSoft: 0.3,
  },
};

