/**
 * VHS After Dark — the late-night video store and the analog TV in the back room. Dim fluorescent
 * light, plastic shelving full of rental cases, cream tape labels written in marker, CRT blue,
 * the VCR's on-screen display (PLAY ▶, REC ●, a blinking 12:00) and the hum of a set left on.
 *
 * Analog effects are used SPARINGLY: tracking distortion and tape seek only on transitions and
 * decorative screens, never constant noise over boards or text. Chrome is black clamshell plastic
 * with cream tape-label title strips; the primary action is a label-white VCR key. The marker font
 * (Kalam, loaded with the skin) is decorative only — labels, titles, handwriting; numbers stay on
 * --font-num.
 */
import type { ThemeDefinition } from '../types.ts';

const INK = '#eef0f6';

export const VHS_AFTER_DARK: ThemeDefinition = {
  id: 'vhs-after-dark',
  name: 'VHS After Dark',
  description:
    'The late-night video store: dim fluorescent aisles, rental cases, marker-written tape labels, CRT glow and a VCR clock blinking 12:00.',
  meta: {
    era: '1989 · Late-night video store',
    tagline: 'Be kind, rewind. Open late.',
    swatches: ['#07080e', '#161a28', '#f1e8d0', '#ff3d6e'],
    family: 'analog',
  },
  effects: {
    surface: 'plastic',
    crt: 0.6,
    grain: 0.3,
    analog: 0.75,
    ambient: 'dust',
    visualizer: 'reels',
    transition: 'tracking',
  },
  colorScheme: 'dark',
  metaThemeColor: '#07080e',
  tokens: {
    '--theme-color-scheme': 'dark',
    '--bg-0': '#07080e',
    '--bg-1': '#0c0e16',
    '--bg-2': '#12151f',
    '--bg-3': '#191d2a',
    '--bg-4': '#222736',
    '--bg-5': '#2d3346',
    '--glass': 'rgba(14, 16, 24, 0.95)',
    '--glass-strong': 'rgba(10, 12, 18, 0.98)',
    '--glass-light': 'rgba(220, 230, 255, 0.04)',
    '--line': 'rgba(180, 196, 230, 0.12)',
    '--line-strong': 'rgba(180, 196, 230, 0.24)',
    '--line-bright': 'rgba(210, 222, 245, 0.44)',
    '--text-0': INK,
    '--text-1': '#cfd4e2',
    '--text-2': '#a2a9bd',
    '--text-3': '#959cb2',
    '--text-inverse': '#0a0b10',
    '--pink': '#ff5c9d',
    '--cyan': '#4fe3e0',
    '--yellow': '#ffd452',
    '--green': '#5fe39a',
    '--orange': '#ff9447',
    '--purple': '#a996ff',
    '--red': '#ff4d5a',
    '--blue': '#5b8cff',
    '--lime': '#b7ea55',
    '--shade': '#000',
    '--light': '#fff',
    '--success': 'var(--green)',
    '--warning': 'var(--yellow)',
    '--danger': 'var(--red)',
    '--info': 'var(--cyan)',
    '--accent': '#4fe3e0',
    '--accent-2': '#ff3d6e',
    '--accent-deep': '#061a1c',
    '--accent-ink': '#051312',
    '--page-bg': 'var(--bg-0)',
    '--page-fg': 'var(--text-0)',
    '--focus-ring': '#ffd452',
    '--scrollbar-thumb': 'var(--bg-5)',
    '--font-display': "'DASCADE Digits', 'Tiny5', 'Silkscreen', ui-monospace, 'SFMono-Regular', monospace",
    '--font-pixel': "'Silkscreen', 'Tiny5', ui-monospace, monospace",
    '--font-ui': "'Inter Variable', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    '--font-tech': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--font-num': "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif",
    '--heading-tracking': '0.03em',
    '--label-tracking': '0.14em',
    '--px': '2px',
    '--radius-sm': '2px',
    '--radius': '4px',
    '--radius-lg': '6px',
    '--shadow-1': '0 2px 0 rgba(0, 0, 0, 0.5), 0 8px 20px rgba(0, 0, 0, 0.45)',
    '--shadow-2': '0 3px 0 rgba(0, 0, 0, 0.55), 0 18px 44px rgba(0, 0, 0, 0.6)',
    '--shadow-3': '0 30px 80px rgba(0, 0, 0, 0.7)',
    '--glow-sm-full': '0 0 8px color-mix(in srgb, var(--accent) 35%, transparent)',
    '--glow-md-full':
      '0 0 14px color-mix(in srgb, var(--accent) 38%, transparent), 0 0 34px color-mix(in srgb, var(--accent) 16%, transparent)',
    '--glow-lg-full':
      '0 0 20px color-mix(in srgb, var(--accent) 45%, transparent), 0 0 60px color-mix(in srgb, var(--accent) 20%, transparent)',
    '--text-glow-full': '0 0 8px color-mix(in srgb, var(--accent) 50%, transparent)',
    '--glow-sm-soft': '0 0 6px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--glow-md-soft': '0 0 8px color-mix(in srgb, var(--accent) 28%, transparent)',
    '--glow-lg-soft': '0 0 12px color-mix(in srgb, var(--accent) 30%, transparent)',
    '--text-glow-soft': '0 0 4px color-mix(in srgb, var(--accent) 35%, transparent)',
    '--ease-out': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    '--ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
    '--ease-spring': 'cubic-bezier(0.3, 1.3, 0.6, 1)',
    '--motion-1': '120ms',
    '--motion-2': '220ms',
    '--motion-3': '400ms',
    '--motion-4': '680ms',
    '--surface-sunken': 'rgba(3, 4, 8, 0.72)',
    '--surface-sunken-soft': 'rgba(3, 4, 8, 0.55)',
    '--surface-raised': 'rgba(220, 230, 255, 0.025)',
    '--surface-hover': 'rgba(220, 230, 255, 0.055)',
    '--panel-bg': 'var(--glass)',
    '--panel-bg-solid': 'var(--glass-strong)',
    '--panel-bg-opaque': 'var(--bg-2)',
    '--panel-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0) 30%)',
    '--panel-border': '#2c3244',
    '--panel-border-width': '1px',
    '--panel-radius': '3px',
    '--panel-shadow': 'inset 0 1px 0 rgba(255, 255, 255, 0.07), 0 0 0 1px rgba(0, 0, 0, 0.6), var(--shadow-2)',
    '--panel-blur': 'none',
    '--panel-divider': 'rgba(180, 196, 230, 0.13)',
    '--titlebar-bg': 'linear-gradient(180deg, #f3ead3 0%, #e9dec1 100%)',
    '--titlebar-fg': '#1b1c26',
    '--titlebar-font': 'var(--font-pixel)',
    '--titlebar-size': 'var(--fs-xs)',
    '--titlebar-tracking': '0.14em',
    '--titlebar-transform': 'uppercase',
    '--titlebar-marker-size': '10px',
    '--bracket-size': '0px',
    '--bracket-width': '0px',
    '--overlay-scrim': 'rgba(2, 3, 6, 0.8)',
    '--overlay-blur': 'none',
    '--button-font': 'var(--font-display)',
    '--button-tracking': '0.06em',
    '--button-radius': '2px',
    '--button-edge-width': '1px',
    '--button-bevel-hi': 'rgba(255, 255, 255, 0.16)',
    '--button-bevel-lo': 'rgba(0, 0, 0, 0.5)',
    '--button-hover-filter': 'brightness(1.14)',
    '--button-press-offset': '2px',
    '--button-bg': '#2a2f3e',
    '--button-bg-2': '#1a1e29',
    '--button-fg': INK,
    '--button-edge': '#05060a',
    '--button-danger-bg': '#ff6a74',
    '--button-danger-bg-2': '#e2364a',
    '--button-danger-fg': '#16030a',
    '--button-danger-edge': '#4a0812',
    '--button-success-bg': '#7cecae',
    '--button-success-bg-2': '#3ec67e',
    '--button-success-fg': '#03170c',
    '--button-success-edge': '#0b3f22',
    '--button-gold-bg': '#ffe083',
    '--button-gold-bg-2': '#efb73a',
    '--button-gold-fg': '#221600',
    '--button-gold-edge': '#5e4200',
    '--input-bg': '#06070c',
    '--input-fg': INK,
    '--input-border': '#343b50',
    '--input-border-hover': '#58617c',
    '--input-radius': '2px',
    '--input-inset': 'inset 0 2px 0 rgba(0, 0, 0, 0.55)',
    '--input-placeholder': '#8a91a8',
    '--control-track': '#06070c',
    '--control-track-edge': '#434a60',
    '--shell-bar-bg': 'linear-gradient(180deg, #151822 0%, #0e1018 100%)',
    '--shell-bar-border': '#262b3a',
    '--shell-bar-blur': 'none',
    '--shell-bar-rule-opacity': '0.9',
    '--shell-bar-solid': '#0e1018',
    '--shell-dock-bg': '#0e1018',
    '--shell-dock-border': '#262b3a',
    '--shell-dock-shadow': '0 -10px 30px rgba(0, 0, 0, 0.5)',
    '--shell-dock-blur': 'none',
    '--toast-bg': '#12151f',
    '--toast-shadow': 'var(--shadow-2)',
    '--hud-bg': 'rgba(9, 10, 16, 0.9)',
    '--hud-bg-strong': '#0c0e16',
    '--hud-border': '#2c3244',
    '--hud-fg': INK,
    '--hud-muted': '#a2a9bd',
    '--hud-radius': '2px',
    '--hud-shadow': '0 2px 0 rgba(0, 0, 0, 0.5)',
    '--hud-blur': 'none',
    '--arcade-floor-bg': 'transparent',
    '--cabinet-body': '#1c1f2b',
    '--cabinet-body-2': '#0b0c12',
    '--cabinet-edge': 'rgba(200, 212, 240, 0.2)',
    '--cabinet-bezel': '#0e1017',
    '--cabinet-screen-bg': '#02030a',
    '--cabinet-glass': 'radial-gradient(120% 90% at 30% 20%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.03) 40%, transparent 60%)',
    '--cabinet-screen-inset': 'inset 0 0 22px rgba(0, 0, 0, 0.75), inset 0 0 0 2px rgba(0, 0, 0, 0.6)',
    '--cabinet-shadow': '0 30px 70px rgba(0, 0, 0, 0.75)',
    '--marquee-font': 'var(--font-display)',
    '--marquee-ink': '#fff',
    '--marquee-outline': '#0a0b12',
    '--marquee-sheen': 'linear-gradient(180deg, rgba(255, 255, 255, 0.16), rgba(255, 255, 255, 0) 40%)',
    '--marquee-tracking': '0.05em',
    '--scanline-ink': 'rgba(0, 0, 0, 0.3)',
    '--scanline-pitch': '3px',
    '--scanline-opacity-full': '0.45',
    '--scanline-opacity-soft': '0.2',
    '--grid-ink': 'transparent',
    '--grid-size': '24px',
    '--noise-opacity': '0.07',
    '--vignette-edge': 'rgba(0, 0, 0, 0.7)',
  },
  overrides: {
    '--title-shadow': '-1.5px 0 0 rgba(255, 45, 110, 0.55), 1.5px 0 0 rgba(60, 225, 235, 0.55), 0 0 14px rgba(79, 227, 224, 0.2)',
    '--button-primary-bg': '#f6efdc',
    '--button-primary-bg-2': '#e4d8b8',
    '--button-primary-fg': '#15161e',
    '--button-primary-edge': '#05060a',
    '--button-primary-glow': 'rgba(241, 232, 208, 0.18)',
    '--button-secondary-edge': '#05060a',
    '--bracket-color': '#ff3d6e',
    '--titlebar-marker': '#ff3d6e',
    '--panel-glow-border': '#4fe3e0',
    '--panel-glow-shadow':
      'inset 0 1px 0 rgba(255, 255, 255, 0.07), 0 0 0 1px rgba(79, 227, 224, 0.18), 0 0 24px rgba(79, 227, 224, 0.12), var(--shadow-2)',
    '--control-accent': '#4fe3e0',
    '--control-accent-ink': '#051312',
    '--input-focus-ring': '0 0 0 3px rgba(79, 227, 224, 0.28)',
    '--shell-bar-rule': 'linear-gradient(90deg, transparent, #ff3d6e 20%, #4fe3e0 80%, transparent)',
  },
  materials: {
    // Card tables: the dim green of a pool-hall table in a late movie.
    felt: '#17493a',
    feltDeep: '#0d2e24',
    feltLine: '#3f8a70',
    rail: '#20232e',
    railHighlight: '#4a5064',
    // Boards: faded cream vs smoky blue-grey, like a board game in a rental bin.
    boardLight: '#d9d2bc',
    boardDark: '#4c5670',
    boardFrame: '#12141c',
    boardHighlight: '#ffd452',
    pieceLight: '#f4efe0',
    pieceDark: '#161820',
    pieceEdge: '#050609',
    // Sea: CRT blue-screen water with cyan grid.
    water: '#10275a',
    waterDeep: '#08173a',
    gridLine: '#4fe3e0',
    radar: '#5fe39a',
    // Mini golf: after-hours putting green under sodium light.
    grass: '#2c7a4e',
    grassDeep: '#1d5838',
    sand: '#d8c690',
    hazard: '#2e5fc0',
    wall: '#2a2f3e',
    wallTop: '#6a7390',
    // Terrain: late-movie night sky over the parking lot.
    sky: '#070a18',
    skyHorizon: '#26244a',
    ground: '#2a2d3c',
    groundDeep: '#171922',
    groundEdge: '#ff5c9d',
    // Racing: wet night road.
    asphalt: '#1d1f28',
    asphaltLine: '#f1e8d0',
    curbA: '#ff4d5a',
    curbB: '#e9e2cd',
    offroad: '#15241d',
    // Cards: cream tape-label stock; backs are a black rental sleeve with a pink band.
    cardFace: '#f5eedb',
    cardInk: '#16171f',
    cardBack: '#15171f',
    cardBackInk: '#ff3d6e',
    // Paper: VHS label / index card.
    paper: '#f3ead3',
    paperInk: '#1b1c28',
    paperEdge: '#cfc2a0',
    // Stage: late-night public-access TV set.
    stage: '#0d0f18',
    stageLight: '#4fe3e0',
    podium: '#232838',
    // Screens: CRT with cyan-blue phosphor glow.
    screen: '#03040a',
    screenGlow: '#6aa8ff',
    bezel: '#12141c',
    // Hardware: brushed VCR silver, red REC LED.
    metal: '#9aa0b0',
    metalHighlight: '#eef0f6',
    led: '#ff3b3b',
    ledOff: '#3a1518',
  },
  gameMaterials: {
    quest: { paper: '#0f1119', paperInk: '#e6e1d0', paperEdge: '#3a4054', screenGlow: '#4fe3e0' },
    deception: { stage: '#08090f', stageLight: '#ff3d6e', cardFace: '#efe6cc' },
    masterpiece: { paper: '#f6eed8', paperEdge: '#c9b98f' },
    chess: { boardFrame: '#191c26' },
  },
  copy: {
    'arcade.tagline': 'Be kind, rewind',
    'arcade.status': 'PLAY \u25B6\uFE0E|SP · STANDARD PLAY|NEW RELEASES THIS WAY|LATE FEES WAIVED TONIGHT|TRACKING: AUTO',
    'arcade.badge': 'REC ●',
    'cabinet.heading': 'Pick a tape',
    'lobby.title': 'Now playing',
    'lobby.players': 'Cast',
    'results.title': 'The end',
    'tournament.title': 'Top rentals',
    'tournament.subtitle': 'This week’s most-played brackets, behind the counter',
    'settings.title': 'Setup menu',
    'jukebox.title': 'Mixtape deck',
    'state.loading': 'Rewinding…',
    'state.connecting': 'Tracking…',
    'state.empty': 'Blank tape',
    'state.error': 'Tape jammed',
  },
  renderer: {
    background: '#07080e',
    surface: '#12151f',
    text: INK,
    textMuted: '#a2a9bd',
    line: '#b4c4e6',
    accent: '#4fe3e0',
    accent2: '#ff3d6e',
    gridAlpha: 0.06,
    scanlines: 0.22,
    scanlinesSoft: 0.1,
    glow: 0.7,
    glowSoft: 0.35,
  },
};
