/**
 * DAStravaganza Trivia starter pack — food. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const FOOD: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'food-001',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Guacamole is made mainly from which fruit?',
    options: ['Mango', 'Avocado', 'Lime', 'Tomato'],
    correct: 1,
    explanation: 'The name comes from the Nahuatl word āhuacamōlli, meaning "avocado sauce".',
  },
  {
    id: 'food-002',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Paella, a rice dish cooked in a wide, shallow pan, comes from which country?',
    options: ['Italy', 'Mexico', 'Spain', 'Portugal'],
    correct: 2,
    explanation: "Paella originated in the Valencia region on Spain's eastern coast.",
  },
  {
    id: 'food-003',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the main ingredient in hummus?',
    options: ['Lentils', 'Chickpeas', 'Fava beans', 'Black beans'],
    correct: 1,
    explanation: 'Hummus blends cooked chickpeas with tahini, lemon juice and garlic.',
  },
  {
    id: 'food-004',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which bright yellow spice, a relative of ginger, gives many curries their golden color?',
    options: ['Paprika', 'Cinnamon', 'Turmeric', 'Nutmeg'],
    correct: 2,
    explanation: 'Turmeric is ground from the dried underground stem (rhizome) of a plant in the ginger family.',
  },
  {
    id: 'food-005',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which cheese is traditionally used on a Margherita pizza?',
    options: ['Cheddar', 'Gouda', 'Halloumi', 'Mozzarella'],
    correct: 3,
    explanation: 'Tomato, mozzarella and basil echo the red, white and green of the Italian flag.',
  },
  {
    id: 'food-006',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Tofu is made by curdling the milk of which bean?',
    options: ['Soybeans', 'Chickpeas', 'Kidney beans', 'Lima beans'],
    correct: 0,
    explanation: 'Soy milk is set with a coagulant and pressed into blocks, a bit like making cheese.',
  },
  {
    id: 'food-007',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Raisins are dried versions of which fruit?',
    options: ['Figs', 'Cherries', 'Grapes', 'Dates'],
    correct: 2,
    explanation: 'Sultanas are dried grapes too, usually from a pale, seedless variety.',
  },
  {
    id: 'food-008',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Pho, a fragrant noodle soup, comes from which country?',
    options: ['Thailand', 'Vietnam', 'Japan', 'South Korea'],
    correct: 1,
    explanation: 'Pho pairs flat rice noodles with a fragrant broth, most often made with beef or chicken.',
  },
  {
    id: 'food-009',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What does it mean to cook pasta "al dente"?',
    options: ['Until very soft', 'Until firm to the bite', 'In salted butter', 'In a stone oven'],
    correct: 1,
    explanation: 'Al dente is Italian for "to the tooth".',
  },
  {
    id: 'food-010',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Chocolate is made from the seeds of which tree?',
    options: ['Carob', 'Coffee', 'Cacao', 'Kola'],
    correct: 2,
    explanation: 'Cacao seeds, often called cocoa beans, are fermented, dried and roasted to make chocolate.',
  },
  {
    id: 'food-011',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Kimchi, a spicy fermented vegetable side dish, is a staple of which cuisine?',
    options: ['Korean', 'Japanese', 'Thai', 'Indian'],
    correct: 0,
    explanation: 'Kimchi is most often made with napa cabbage, chili, garlic and ginger.',
  },
  {
    id: 'food-012',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which cheese tops a classic Greek salad?',
    options: ['Ricotta', 'Gruyère', 'Brie', 'Feta'],
    correct: 3,
    explanation: "Feta is a brined cheese traditionally made from sheep's milk, sometimes mixed with goat's milk.",
  },
  {
    id: 'food-013',
    category: 'food',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Goulash, a hearty paprika-spiced stew, comes from which country?',
    options: ['Spain', 'Hungary', 'Greece', 'Ireland'],
    correct: 1,
    explanation: 'Its name comes from the Hungarian word gulyás, meaning herdsman.',
  },

  // --- Multiple choice: medium ---
  {
    id: 'food-014',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In Italian, what does the word "latte" mean?',
    options: ['Coffee', 'Milk', 'Foam', 'Cream'],
    correct: 1,
    explanation: 'Ask for just a "latte" in Italy and you may well be handed a glass of milk.',
  },
  {
    id: 'food-015',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Camembert cheese comes from which region of France?',
    options: ['Normandy', 'Provence', 'Alsace', 'Burgundy'],
    correct: 0,
    explanation: 'The cheese is named after the village of Camembert in Normandy.',
  },
  {
    id: 'food-016',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Gouda cheese is named after a city in which country?',
    options: ['Belgium', 'Denmark', 'Netherlands', 'Switzerland'],
    correct: 2,
    explanation: 'The city of Gouda, in the province of South Holland, has hosted a cheese market for centuries.',
  },
  {
    id: 'food-017',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Cinnamon comes from which part of a tree?',
    options: ['The seeds', 'The leaves', 'The roots', 'The inner bark'],
    correct: 3,
    explanation: 'Strips of inner bark curl up as they dry, forming cinnamon sticks, also called quills.',
  },
  {
    id: 'food-018',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In cooking, what does it mean to "julienne" a vegetable?',
    options: ['Boil it briefly, then chill it', 'Grate it into a fine pulp', 'Cut it into thin matchsticks', 'Char it over an open flame'],
    correct: 2,
    explanation: 'Julienned carrots and peppers are a classic garnish and stir-fry ingredient.',
  },
  {
    id: 'food-019',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which French kitchen phrase means having every ingredient prepped and ready before you start cooking?',
    options: ['Bain-marie', 'Mise en place', 'Amuse-bouche', 'En papillote'],
    correct: 1,
    explanation: 'Chefs often translate mise en place as "everything in its place".',
  },
  {
    id: 'food-020',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which sauce is made by whisking egg yolks with melted butter and lemon juice?',
    options: ['Béchamel', 'Marinara', 'Hollandaise', 'Chimichurri'],
    correct: 2,
    explanation: 'Hollandaise is the classic sauce spooned over eggs Benedict.',
  },
  {
    id: 'food-021',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which variety of rice is classically used to make risotto?',
    options: ['Basmati', 'Jasmine', 'Long-grain', 'Arborio'],
    correct: 3,
    explanation: "Arborio's short, starchy grains give risotto its creamy texture.",
  },
  {
    id: 'food-022',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The Middle Eastern dip baba ganoush is made mainly from which vegetable?',
    options: ['Carrots', 'Eggplant', 'Zucchini', 'Red peppers'],
    correct: 1,
    explanation: 'The eggplant is roasted until smoky, then mashed with tahini, lemon and garlic.',
  },
  {
    id: 'food-023',
    category: 'food',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which spiky Southeast Asian fruit, famous for its powerful smell, is nicknamed the "king of fruits"?',
    options: ['Durian', 'Jackfruit', 'Mangosteen', 'Rambutan'],
    correct: 0,
    explanation: "Durian's aroma is so strong that some hotels and public transit systems ban it.",
  },

  // --- Multiple choice: hard ---
  {
    id: 'food-024',
    category: 'food',
    difficulty: 'hard',
    type: 'mc',
    prompt: "Roquefort cheese is traditionally made from which animal's milk?",
    options: ['Cow', 'Goat', 'Sheep', 'Water buffalo'],
    correct: 2,
    explanation: "By law, Roquefort must be made from sheep's milk and ripened in the natural caves of Roquefort-sur-Soulzon.",
  },
  {
    id: 'food-025',
    category: 'food',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The Granny Smith apple was first grown in which country?',
    options: ['England', 'Australia', 'Canada', 'New Zealand'],
    correct: 1,
    explanation: 'It is named after Maria Ann Smith, who grew the first tree near Sydney in the 1860s.',
  },
  {
    id: 'food-026',
    category: 'food',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Broccoli, cauliflower, kale and Brussels sprouts were all bred from which single wild plant?',
    options: ['Wild lettuce', 'Wild celery', 'Wild cabbage', 'Wild spinach'],
    correct: 2,
    explanation: 'All are cultivated forms of one species, Brassica oleracea, selected for their leaves, buds or flower heads.',
  },
  {
    id: 'food-027',
    category: 'food',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The Sachertorte, a rich chocolate cake with apricot jam, was created in which city?',
    options: ['Vienna', 'Budapest', 'Munich', 'Zurich'],
    correct: 0,
    explanation: 'Franz Sacher created the cake in Vienna in 1832, and the Hotel Sacher still serves it today.',
  },
  {
    id: 'food-028',
    category: 'food',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Saffron threads are which part of the crocus flower?',
    options: ['The petals', 'The stigmas', 'The seeds', 'The roots'],
    correct: 1,
    explanation: 'Each flower yields only three stigmas, picked by hand, which is one reason saffron is so costly.',
  },

  // --- True / false ---
  {
    id: 'food-029',
    category: 'food',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Botanically speaking, a tomato is a fruit.',
    correct: true,
    explanation: 'A tomato develops from a flower and holds seeds, which makes it a berry in botanical terms.',
  },
  {
    id: 'food-030',
    category: 'food',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Peanuts grow on trees.',
    correct: false,
    explanation: 'Peanuts are legumes: after the plant flowers, its pods develop underground.',
  },
  {
    id: 'food-031',
    category: 'food',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Vanilla comes from the seed pods of an orchid.',
    correct: true,
    explanation: 'Vanilla pods are the fruit of climbing orchids originally native to Mexico and Central America.',
  },
  {
    id: 'food-032',
    category: 'food',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Green tea and black tea are made from different plant species.',
    correct: false,
    explanation: 'Both come from Camellia sinensis; the difference lies in how the leaves are processed.',
  },
  {
    id: 'food-033',
    category: 'food',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Coffee beans are the seeds of a fruit.',
    correct: true,
    explanation: 'They grow inside red or yellow coffee "cherries", usually two seeds per fruit.',
  },
  {
    id: 'food-034',
    category: 'food',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'By definition, sushi must contain raw fish.',
    correct: false,
    explanation: 'Sushi is defined by its vinegared rice; cucumber rolls and egg (tamago) sushi contain no fish at all.',
  },
  {
    id: 'food-035',
    category: 'food',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Nutmeg and mace come from the same fruit.',
    correct: true,
    explanation: 'Nutmeg is the seed, and mace is the lacy red covering wrapped around it.',
  },
  {
    id: 'food-036',
    category: 'food',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Black peppercorns and bell peppers come from closely related plants.',
    correct: false,
    explanation: 'Peppercorns are the berries of a tropical vine, while bell peppers are a Capsicum, like chili peppers.',
  },

  // --- Type the answer ---
  {
    id: 'food-037',
    category: 'food',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What baked Italian dish is made from layers of flat pasta sheets, sauce and cheese?',
    accept: ['Lasagna', 'Lasagne'],
    explanation: 'In Italy, lasagne (the plural) is the usual name for both the dish and its wide pasta sheets.',
  },
  {
    id: 'food-038',
    category: 'food',
    difficulty: 'easy',
    type: 'text',
    prompt: 'Prunes are made by drying which fruit?',
    accept: ['Plums', 'Plum'],
    explanation: 'Prunes are usually made from European plum varieties that dry well without fermenting.',
  },
  {
    id: 'food-039',
    category: 'food',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What finely ground Japanese green tea powder is whisked with hot water in the traditional tea ceremony?',
    accept: ['Matcha'],
    explanation: 'Matcha is made from shade-grown tea leaves that are stone-ground into a fine powder.',
  },
  {
    id: 'food-040',
    category: 'food',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What chilled Spanish soup is made from blended raw tomatoes, cucumber and peppers?',
    accept: ['Gazpacho'],
    explanation: 'Gazpacho comes from Andalusia in southern Spain, where it is a summertime favorite.',
  },
  {
    id: 'food-041',
    category: 'food',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What French-named technique seals food in a vacuum bag and cooks it in a precisely heated water bath?',
    accept: ['Sous vide'],
    explanation: 'Sous vide is French for "under vacuum".',
  },

  // --- Closest number ---
  {
    id: 'food-042',
    category: 'food',
    difficulty: 'easy',
    type: 'number',
    prompt: 'In U.S. measurements, how many ounces are in one pound?',
    correct: 16,
    unit: 'ounces',
    explanation: 'A pound is 16 ounces, or about 454 grams.',
  },
  {
    id: 'food-043',
    category: 'food',
    difficulty: 'medium',
    type: 'number',
    prompt: 'In U.S. kitchen measurements, how many teaspoons make one tablespoon?',
    correct: 3,
    unit: 'teaspoons',
    explanation: 'Three teaspoons make a tablespoon, and 16 tablespoons make a cup.',
  },
  {
    id: 'food-044',
    category: 'food',
    difficulty: 'medium',
    type: 'number',
    prompt: 'In what year did tire makers André and Édouard Michelin publish the first Michelin Guide?',
    correct: 1900,
    explanation: 'The free guide listed garages, hotels and places to eat for French motorists; its famous restaurant stars came later.',
  },
  {
    id: 'food-045',
    category: 'food',
    difficulty: 'hard',
    type: 'number',
    prompt: 'In what year was Coca-Cola first sold, at a pharmacy in Atlanta?',
    correct: 1886,
    explanation: "Pharmacist John Pemberton created the syrup, and it was first sold at Jacobs' Pharmacy for five cents a glass.",
  },

  // --- Put in order ---
  {
    id: 'food-046',
    category: 'food',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these bread-making steps in order.',
    items: ['Mix flour, water and yeast', 'Knead the dough', 'Let the dough rise', 'Bake in a hot oven'],
    ends: ['First', 'Last'],
    explanation: 'Kneading develops gluten, and rising lets the yeast fill the dough with gas before it is baked.',
  },
  {
    id: 'food-047',
    category: 'food',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Rank these peppers from mildest to hottest.',
    items: ['Bell pepper', 'Jalapeño', 'Habanero', 'Ghost pepper'],
    ends: ['Mildest', 'Hottest'],
    explanation: 'On the Scoville scale, bell peppers score zero while ghost peppers can top one million units.',
  },
  {
    id: 'food-048',
    category: 'food',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Candy makers cook sugar syrup through stages. Put these from lowest to highest temperature.',
    items: ['Soft ball', 'Hard ball', 'Soft crack', 'Hard crack'],
    ends: ['Coolest', 'Hottest'],
    explanation: 'Soft ball forms around 235 °F (113 °C), while hard crack needs about 300 °F (149 °C).',
  },
];
