/**
 * DAStravaganza Trivia starter pack — general. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const GENERAL: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'general-001',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which colour do you get by mixing blue and yellow paint?',
    options: ['Green', 'Purple', 'Orange', 'Brown'],
    correct: 0,
    explanation: 'Blue and yellow are primaries on the traditional painter’s colour wheel, and together they make green.',
  },
  {
    id: 'general-002',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How many players does each team have on the pitch at the start of a football (soccer) match?',
    options: ['9', '10', '11', '12'],
    correct: 2,
    fixedOrder: true,
    explanation: 'Each side starts with 11 players, including the goalkeeper.',
  },
  {
    id: 'general-003',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which month of the year has the fewest days?',
    options: ['April', 'June', 'November', 'February'],
    correct: 3,
    explanation: 'February has 28 days, or 29 in a leap year.',
  },
  {
    id: 'general-004',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Who painted “The Starry Night” in 1889?',
    options: ['Claude Monet', 'Vincent van Gogh', 'Paul Cézanne', 'Pablo Picasso'],
    correct: 1,
    explanation: 'Van Gogh painted the swirling night sky while staying at an asylum in Saint-Rémy-de-Provence, France.',
  },
  {
    id: 'general-005',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In which sport would a player score with a “slam dunk”?',
    options: ['Volleyball', 'Basketball', 'Tennis', 'Rugby'],
    correct: 1,
    explanation: 'In a slam dunk, a player leaps up and forces the ball down through the hoop.',
  },
  {
    id: 'general-006',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In tennis, which word is used for a score of zero?',
    options: ['Nil', 'Love', 'Duck', 'Blank'],
    correct: 1,
    explanation: 'A game score of 15–0 is called out as “fifteen–love”.',
  },
  {
    id: 'general-007',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How many strings does a standard guitar have?',
    options: ['4', '5', '6', '7'],
    correct: 2,
    fixedOrder: true,
    explanation: 'Standard tuning, from the lowest string to the highest, is E–A–D–G–B–E.',
  },
  {
    id: 'general-008',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correct: 1,
    fixedOrder: true,
    explanation: 'The name comes from the Greek for “six angles”; a pentagon has five sides and an octagon has eight.',
  },
  {
    id: 'general-009',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In which sport do teams compete for the Stanley Cup?',
    options: ['Baseball', 'Ice hockey', 'Basketball', 'American football'],
    correct: 1,
    explanation: 'First awarded in 1893, the Stanley Cup is the championship trophy of the National Hockey League.',
  },
  {
    id: 'general-010',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which chess piece can only ever move diagonally?',
    options: ['Rook', 'Bishop', 'Knight', 'Queen'],
    correct: 1,
    explanation: 'Because it only moves diagonally, a bishop stays on squares of the same colour all game.',
  },
  {
    id: 'general-011',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which animal is nicknamed the “ship of the desert”?',
    options: ['Camel', 'Horse', 'Elephant', 'Ostrich'],
    correct: 0,
    explanation: 'Camels can go a long time without drinking, and their wide feet spread out on soft sand.',
  },
  {
    id: 'general-012',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'An invitation asks you to “RSVP”. What does it want you to do?',
    options: ['Bring a guest', 'Dress formally', 'Arrive early', 'Please reply'],
    correct: 3,
    explanation: 'RSVP comes from the French “Répondez s’il vous plaît” — “please reply”.',
  },
  {
    id: 'general-013',
    category: 'general',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which of these is NOT one of the four suits in a standard deck of playing cards?',
    options: ['Hearts', 'Clubs', 'Stars', 'Spades'],
    correct: 2,
    explanation: 'The four suits are hearts, diamonds, clubs and spades.',
  },

  // --- Multiple choice: medium ---
  {
    id: 'general-014',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Strictly speaking, the name “Big Ben” belongs to which part of the famous London landmark?',
    options: ['The great bell', 'The clock tower', 'The largest clock face', 'The minute hand'],
    correct: 0,
    explanation: 'Big Ben is the nickname of the Great Bell; the tower itself was renamed Elizabeth Tower in 2012.',
  },
  {
    id: 'general-015',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which composer wrote the “Moonlight Sonata”?',
    options: ['Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Ludwig van Beethoven', 'Frédéric Chopin'],
    correct: 2,
    explanation: 'Beethoven’s Piano Sonata No. 14 got its “Moonlight” nickname from a music critic after the composer’s death.',
  },
  {
    id: 'general-016',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In golf, what is the term for finishing a hole one stroke under par?',
    options: ['Eagle', 'Bogey', 'Birdie', 'Albatross'],
    correct: 2,
    explanation: 'An eagle is two under par, an albatross is three under, and a bogey is one over.',
  },
  {
    id: 'general-017',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which of these colours does NOT appear in the five Olympic rings?',
    options: ['Blue', 'Black', 'Purple', 'Green'],
    correct: 2,
    explanation: 'The rings are blue, yellow, black, green and red on a white background.',
  },
  {
    id: 'general-018',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which day of the week is named after the Norse god of thunder?',
    options: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    correct: 2,
    explanation: 'Thursday comes from “Thor’s day”.',
  },
  {
    id: 'general-019',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In the NATO phonetic alphabet, which word stands for the letter Z?',
    options: ['Zebra', 'Zulu', 'Zero', 'Zeta'],
    correct: 1,
    explanation: 'The alphabet runs from Alfa, Bravo and Charlie all the way to X-ray, Yankee and Zulu.',
  },
  {
    id: 'general-020',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'On sheet music, what does the Italian marking “forte” tell a musician to do?',
    options: ['Play loudly', 'Play softly', 'Play slowly', 'Play faster'],
    correct: 0,
    explanation: 'Forte means “strong”; its opposite, piano, means “soft”.',
  },
  {
    id: 'general-021',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which composer wrote the set of four violin concertos known as “The Four Seasons”?',
    options: ['Johann Sebastian Bach', 'George Frideric Handel', 'Joseph Haydn', 'Antonio Vivaldi'],
    correct: 3,
    explanation: 'Vivaldi published the concertos in 1725, each one painting a picture of a season in music.',
  },
  {
    id: 'general-022',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The abbreviation “e.g.” comes from a Latin phrase meaning what?',
    options: ['For example', 'That is', 'And so on', 'Note well'],
    correct: 0,
    explanation: '“e.g.” stands for “exempli gratia”, while “i.e.” (“id est”) means “that is”.',
  },
  {
    id: 'general-023',
    category: 'general',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In which Italian city is Michelangelo’s original marble statue of David displayed?',
    options: ['Rome', 'Venice', 'Florence', 'Milan'],
    correct: 2,
    explanation: 'The original has stood in Florence’s Galleria dell’Accademia since 1873; a replica stands in the Piazza della Signoria.',
  },

  // --- Multiple choice: hard ---
  {
    id: 'general-024',
    category: 'general',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'In a year that is not a leap year, which month always starts on the same day of the week as January?',
    options: ['April', 'July', 'October', 'December'],
    correct: 2,
    explanation: 'In a common year, 1 January and 1 October are exactly 273 days — 39 whole weeks — apart.',
  },
  {
    id: 'general-025',
    category: 'general',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which architect designed the glass pyramid at the entrance of the Louvre in Paris?',
    options: ['Frank Gehry', 'Zaha Hadid', 'Norman Foster', 'I. M. Pei'],
    correct: 3,
    explanation: 'Chinese-American architect I. M. Pei’s pyramid was controversial at first but became a Paris icon.',
  },
  {
    id: 'general-026',
    category: 'general',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Jørn Utzon, the architect of the Sydney Opera House, came from which country?',
    options: ['Sweden', 'Denmark', 'Norway', 'Finland'],
    correct: 1,
    explanation: 'Utzon, a Dane, won the international design competition for the opera house in 1957.',
  },
  {
    id: 'general-027',
    category: 'general',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which martial art’s name translates as “the gentle way”?',
    options: ['Karate', 'Judo', 'Aikido', 'Kendo'],
    correct: 1,
    explanation: 'Judo was founded in Japan by Kanō Jigorō in 1882; karate means “empty hand”.',
  },
  {
    id: 'general-028',
    category: 'general',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'What does a philatelist collect?',
    options: ['Coins', 'Stamps', 'Butterflies', 'Autographs'],
    correct: 1,
    explanation: 'Philately is the collecting and study of postage stamps; coin collectors are called numismatists.',
  },

  // --- True or false ---
  {
    id: 'general-029',
    category: 'general',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'A standard 88-key piano has more white keys than black keys.',
    correct: true,
    explanation: 'It has 52 white keys and 36 black keys.',
  },
  {
    id: 'general-030',
    category: 'general',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Leonardo da Vinci painted the ceiling of the Sistine Chapel.',
    correct: false,
    explanation: 'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512.',
  },
  {
    id: 'general-031',
    category: 'general',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Each player begins a game of chess with 16 pieces, pawns included.',
    correct: true,
    explanation: 'Each side has 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen and a king.',
  },
  {
    id: 'general-032',
    category: 'general',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The viola is a larger instrument than the cello.',
    correct: false,
    explanation:
      'The viola is only a little bigger than a violin and is held under the chin; the much larger cello is played sitting down.',
  },
  {
    id: 'general-033',
    category: 'general',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The Mona Lisa hangs in the British Museum in London.',
    correct: false,
    explanation: 'Leonardo da Vinci’s Mona Lisa is displayed at the Louvre in Paris.',
  },
  {
    id: 'general-034',
    category: 'general',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The word “alphabet” comes from the names of the first two Greek letters.',
    correct: true,
    explanation: 'Alpha and beta are the first two letters of the Greek alphabet.',
  },
  {
    id: 'general-035',
    category: 'general',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'In the Gregorian calendar, every year divisible by 100 is a leap year.',
    correct: false,
    explanation: 'Century years are leap years only if divisible by 400, so 2000 was a leap year but 1900 was not.',
  },
  {
    id: 'general-036',
    category: 'general',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Great Sphinx of Giza has the head of a human and the body of a lion.',
    correct: true,
    explanation: 'The huge limestone statue sits near the pyramids on Egypt’s Giza plateau.',
  },

  // --- Type the answer ---
  {
    id: 'general-037',
    category: 'general',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What is a baby kangaroo called?',
    accept: ['Joey', 'Joeys'],
    explanation: 'A newborn joey crawls into its mother’s pouch and keeps growing there for months.',
  },
  {
    id: 'general-038',
    category: 'general',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What is the name of the “&” symbol?',
    accept: ['Ampersand'],
    explanation: 'The & began as a joined-up way of writing “et”, Latin for “and”.',
  },
  {
    id: 'general-039',
    category: 'general',
    difficulty: 'easy',
    type: 'text',
    prompt: 'In the traditional seven colours of the rainbow, which colour comes between blue and violet?',
    accept: ['Indigo'],
    explanation: 'The order is often remembered as ROY G. BIV: red, orange, yellow, green, blue, indigo, violet.',
  },
  {
    id: 'general-040',
    category: 'general',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What is a baby swan called?',
    accept: ['Cygnet', 'Cygnets'],
    explanation: 'Adult male swans are called cobs and females are called pens.',
  },
  {
    id: 'general-041',
    category: 'general',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What is the name of the traditional Japanese art of flower arranging?',
    accept: ['Ikebana', 'Kado'],
    explanation:
      'Ikebana, also called kadō (“the way of flowers”), focuses on line, shape and balance rather than simply packing in blooms.',
  },

  // --- Closest number ---
  {
    id: 'general-042',
    category: 'general',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many minutes are there in one full day?',
    correct: 1440,
    unit: 'minutes',
    explanation: '24 hours × 60 minutes = 1,440 minutes.',
  },
  {
    id: 'general-043',
    category: 'general',
    difficulty: 'hard',
    type: 'number',
    prompt: 'Which year is written in Roman numerals as MCMLXIX?',
    correct: 1969,
    explanation: 'M = 1000, CM = 900, LX = 60 and IX = 9, which adds up to 1969.',
  },
  {
    id: 'general-044',
    category: 'general',
    difficulty: 'medium',
    type: 'number',
    prompt: 'What is the highest possible score in a single game of ten-pin bowling?',
    correct: 300,
    unit: 'points',
    explanation: 'A perfect game takes 12 strikes in a row.',
  },
  {
    id: 'general-045',
    category: 'general',
    difficulty: 'hard',
    type: 'number',
    prompt: 'How long is an official marathon, in kilometres? (Decimals count!)',
    correct: 42.195,
    unit: 'km',
    explanation: 'The distance was standardised at 42.195 km (26 miles 385 yards) in 1921.',
  },

  // --- Put in order ---
  {
    id: 'general-046',
    category: 'general',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Order these spans of time from shortest to longest.',
    items: ['Hour', 'Week', 'Year', 'Century'],
    ends: ['Shortest', 'Longest'],
    explanation: 'An hour is 60 minutes, a week is 7 days, a year is 365 or 366 days and a century is 100 years.',
  },
  {
    id: 'general-047',
    category: 'general',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Order these artists by birth year, earliest first.',
    items: ['Leonardo da Vinci', 'Rembrandt', 'Claude Monet', 'Andy Warhol'],
    ends: ['Earliest', 'Latest'],
    explanation: 'Leonardo was born in 1452, Rembrandt in 1606, Monet in 1840 and Warhol in 1928.',
  },
  {
    id: 'general-048',
    category: 'general',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Order these composers by birth year, earliest first.',
    items: ['Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Pyotr Ilyich Tchaikovsky'],
    ends: ['Earliest', 'Latest'],
    explanation: 'Bach was born in 1685, Mozart in 1756, Beethoven in 1770 and Tchaikovsky in 1840.',
  },
];
