/**
 * DAStravaganza Trivia starter pack — geography. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const GEOGRAPHY: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'geography-001',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    correct: 0,
    explanation: 'Ottawa lies in Ontario on the Ottawa River, which forms part of the boundary with Quebec.',
  },
  {
    id: 'geography-002',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which city is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
    correct: 2,
    explanation: 'Canberra was purpose-built as the capital, partly as a compromise between rivals Sydney and Melbourne.',
  },
  {
    id: 'geography-003',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Mount Everest is part of which mountain range?',
    options: ['Andes', 'Himalayas', 'Alps', 'Rocky Mountains'],
    correct: 1,
    explanation: 'Everest is the highest peak of the Himalayas and the highest mountain on Earth above sea level.',
  },
  {
    id: 'geography-004',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which river flows through the heart of Paris?',
    options: ['Loire', 'Rhône', 'Thames', 'Seine'],
    correct: 3,
    explanation: 'The Seine winds through Paris on its way to the English Channel.',
  },
  {
    id: 'geography-005',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The Sahara Desert covers much of the northern part of which continent?',
    options: ['Africa', 'Asia', 'Australia', 'South America'],
    correct: 0,
    explanation: 'The Sahara stretches across North Africa from the Atlantic coast to the Red Sea.',
  },
  {
    id: 'geography-006',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: "Which European country's mainland is famously shaped like a boot?",
    options: ['Greece', 'Spain', 'Italy', 'Portugal'],
    correct: 2,
    explanation: 'The Italian "boot" even has a heel (Apulia) and a toe (Calabria).',
  },
  {
    id: 'geography-007',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: "Which country's flag is white with a single red circle in the center?",
    options: ['South Korea', 'Japan', 'Bangladesh', 'Palau'],
    correct: 1,
    explanation: "The red disc on Japan's flag represents the sun.",
  },
  {
    id: 'geography-008',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which U.S. state is made up entirely of islands?',
    options: ['Alaska', 'Florida', 'Rhode Island', 'Hawaii'],
    correct: 3,
    explanation: 'Hawaii is a chain of volcanic islands in the middle of the Pacific Ocean.',
  },
  {
    id: 'geography-009',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The ancient Inca site of Machu Picchu is in which country?',
    options: ['Peru', 'Bolivia', 'Chile', 'Ecuador'],
    correct: 0,
    explanation: 'Machu Picchu sits high in the Andes above the Urubamba River valley.',
  },
  {
    id: 'geography-010',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which large island off the southeast coast of Africa is famous for its lemurs?',
    options: ['Sri Lanka', 'Madagascar', 'Mauritius', 'Zanzibar'],
    correct: 1,
    explanation:
      'Lemurs evolved on Madagascar and live wild nowhere else, apart from a few on the nearby Comoros that people probably brought there.',
  },
  {
    id: 'geography-011',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The Rialto Bridge crosses the Grand Canal in which city?',
    options: ['Florence', 'Rome', 'Venice', 'Milan'],
    correct: 2,
    explanation: "Completed in 1591, the stone Rialto Bridge is the oldest bridge across Venice's Grand Canal.",
  },
  {
    id: 'geography-012',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which U.S. state is nicknamed the "Lone Star State"?',
    options: ['Texas', 'Arizona', 'Oklahoma', 'Nevada'],
    correct: 0,
    explanation: 'The nickname recalls the single star on the flag of the former Republic of Texas.',
  },
  {
    id: 'geography-013',
    category: 'geography',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the capital of Kenya?',
    options: ['Mombasa', 'Nairobi', 'Kampala', 'Addis Ababa'],
    correct: 1,
    explanation: "Nairobi grew from a railway depot founded in 1899 into Kenya's capital city.",
  },

  // --- Multiple choice: medium ---
  {
    id: 'geography-014',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The Great Barrier Reef lies off the coast of which Australian state?',
    options: ['New South Wales', 'Queensland', 'Victoria', 'Western Australia'],
    correct: 1,
    explanation: "The reef runs for more than 2,000 km along Queensland's coast in the Coral Sea.",
  },
  {
    id: 'geography-015',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What is the capital of New Zealand?',
    options: ['Auckland', 'Christchurch', 'Wellington', 'Queenstown'],
    correct: 2,
    explanation: 'Wellington, at the southern tip of the North Island, has been the capital since 1865.',
  },
  {
    id: 'geography-016',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which strait separates Spain from Morocco at the entrance to the Mediterranean Sea?',
    options: ['Strait of Gibraltar', 'Bosphorus', 'Strait of Hormuz', 'Strait of Magellan'],
    correct: 0,
    explanation: 'At its narrowest, the Strait of Gibraltar is only about 14 km (9 miles) wide.',
  },
  {
    id: 'geography-017',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The Danube River empties into which sea?',
    options: ['Baltic Sea', 'North Sea', 'Adriatic Sea', 'Black Sea'],
    correct: 3,
    explanation: "The Danube flows from Germany's Black Forest to a wide delta on the Black Sea in Romania and Ukraine.",
  },
  {
    id: 'geography-018',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: "Which country's flag has vertical stripes of green, white and orange, with green nearest the flagpole?",
    options: ['Italy', 'Ireland', 'Hungary', 'Mexico'],
    correct: 1,
    explanation: "Ireland's tricolour dates from the mid-1800s; Italy's similar flag uses red instead of orange.",
  },
  {
    id: 'geography-019',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which mountain range forms much of the border between France and Spain?',
    options: ['Alps', 'Pyrenees', 'Apennines', 'Carpathians'],
    correct: 1,
    explanation: 'The tiny country of Andorra is tucked high in the Pyrenees between the two.',
  },
  {
    id: 'geography-020',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correct: 2,
    explanation: 'Brasília was built from scratch in the interior and replaced Rio de Janeiro as capital in 1960.',
  },
  {
    id: 'geography-021',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which Caribbean island is shared by Haiti and the Dominican Republic?',
    options: ['Cuba', 'Jamaica', 'Puerto Rico', 'Hispaniola'],
    correct: 3,
    explanation: 'Hispaniola is the second-largest island in the Caribbean, after Cuba.',
  },
  {
    id: 'geography-022',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: "Mount Kilimanjaro, Africa's highest peak, is in which country?",
    options: ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'],
    correct: 1,
    explanation: 'Kilimanjaro rises in northeastern Tanzania, close to the Kenyan border.',
  },
  {
    id: 'geography-023',
    category: 'geography',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The Canary Islands belong to which country?',
    options: ['Portugal', 'Italy', 'Spain', 'France'],
    correct: 2,
    explanation: 'Though they lie off the coast of northwest Africa, the Canaries are a Spanish autonomous community.',
  },

  // --- Multiple choice: hard ---
  {
    id: 'geography-024',
    category: 'geography',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'What is the capital of Mongolia?',
    options: ['Ulaanbaatar', 'Tashkent', 'Bishkek', 'Dushanbe'],
    correct: 0,
    explanation: "Ulaanbaatar is often called the world's coldest national capital.",
  },
  {
    id: 'geography-025',
    category: 'geography',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which country is completely surrounded by South Africa?',
    options: ['Eswatini', 'Botswana', 'Lesotho', 'Namibia'],
    correct: 2,
    explanation: 'Lesotho is one of only three countries entirely surrounded by another, along with San Marino and Vatican City.',
  },
  {
    id: 'geography-026',
    category: 'geography',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which European capital stands on the Vltava River?',
    options: ['Vienna', 'Prague', 'Budapest', 'Bratislava'],
    correct: 1,
    explanation: 'The famous Charles Bridge crosses the Vltava in the heart of Prague.',
  },
  {
    id: 'geography-027',
    category: 'geography',
    difficulty: 'hard',
    type: 'mc',
    prompt: "Which is Canada's only officially bilingual province?",
    options: ['Quebec', 'Ontario', 'New Brunswick', 'Nova Scotia'],
    correct: 2,
    explanation: "New Brunswick gives English and French equal status; Quebec's sole official language is French.",
  },
  {
    id: 'geography-028',
    category: 'geography',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Victoria Falls lies on the border between Zambia and which other country?',
    options: ['Botswana', 'Malawi', 'Mozambique', 'Zimbabwe'],
    correct: 3,
    explanation: 'The falls are on the Zambezi River, which forms the Zambia–Zimbabwe border there.',
  },

  // --- True / false ---
  {
    id: 'geography-029',
    category: 'geography',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The Panama Canal links the Atlantic and Pacific Oceans.',
    correct: true,
    explanation: 'Opened in 1914, the canal spares ships the long voyage around the tip of South America.',
  },
  {
    id: 'geography-030',
    category: 'geography',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The official language of Brazil is Spanish.',
    correct: false,
    explanation: "Brazil's official language is Portuguese, a legacy of its colonial history.",
  },
  {
    id: 'geography-031',
    category: 'geography',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Canada and the United States share the longest international border in the world.',
    correct: true,
    explanation: 'The border runs for nearly 9,000 km (about 5,500 miles), including the boundary with Alaska.',
  },
  {
    id: 'geography-032',
    category: 'geography',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Portugal shares a land border with France.',
    correct: false,
    explanation: "Portugal's only land neighbor is Spain, which lies between it and France.",
  },
  {
    id: 'geography-033',
    category: 'geography',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Nile flows generally northward and empties into the Mediterranean Sea.',
    correct: true,
    explanation: "The Nile's delta fans out across Egypt's Mediterranean coast, north of Cairo.",
  },
  {
    id: 'geography-034',
    category: 'geography',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Equator passes through Mexico.',
    correct: false,
    explanation: 'All of Mexico lies north of the Equator, which crosses South America through Ecuador, Colombia and Brazil.',
  },
  {
    id: 'geography-035',
    category: 'geography',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Alaska shares a land border with Russia.',
    correct: false,
    explanation: "Alaska's only land neighbor is Canada; Russia lies across the narrow Bering Strait.",
  },
  {
    id: 'geography-036',
    category: 'geography',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Reykjavík is the northernmost capital city of any sovereign country.',
    correct: true,
    explanation: "Iceland's capital lies at about 64° north, a little south of the Arctic Circle.",
  },

  // --- Type the answer ---
  {
    id: 'geography-037',
    category: 'geography',
    difficulty: 'easy',
    type: 'text',
    prompt: 'The island of Bali is part of which country?',
    accept: ['Indonesia'],
    explanation: 'Indonesia is made up of thousands of islands, and Bali is one of the best known.',
  },
  {
    id: 'geography-038',
    category: 'geography',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What is the capital city of Argentina?',
    accept: ['Buenos Aires'],
    explanation: 'Buenos Aires sits on the wide Río de la Plata estuary.',
  },
  {
    id: 'geography-039',
    category: 'geography',
    difficulty: 'medium',
    type: 'text',
    prompt: 'The ancient rock-cut city of Petra is in which country?',
    accept: ['Jordan', 'Hashemite Kingdom of Jordan'],
    explanation: 'Petra was carved into rose-red sandstone cliffs by the Nabataeans more than 2,000 years ago.',
  },
  {
    id: 'geography-040',
    category: 'geography',
    difficulty: 'medium',
    type: 'text',
    prompt: 'The Taj Mahal stands in which Indian city?',
    accept: ['Agra'],
    explanation: 'The white-marble mausoleum rises on the bank of the Yamuna River in Agra.',
  },
  {
    id: 'geography-041',
    category: 'geography',
    difficulty: 'hard',
    type: 'text',
    prompt: 'The historic desert trading city of Timbuktu is in which present-day country?',
    accept: ['Mali', 'Republic of Mali'],
    explanation: 'Near the Niger River, Timbuktu was a great center of trade and Islamic scholarship in the 1400s and 1500s.',
  },

  // --- Closest number ---
  {
    id: 'geography-042',
    category: 'geography',
    difficulty: 'easy',
    type: 'number',
    prompt: 'How many states make up the United States?',
    correct: 50,
    unit: 'states',
    explanation: 'Hawaii became the 50th state in August 1959.',
  },
  {
    id: 'geography-043',
    category: 'geography',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many provinces does Canada have?',
    correct: 10,
    unit: 'provinces',
    explanation: 'Canada has ten provinces plus three territories: Yukon, the Northwest Territories and Nunavut.',
  },
  {
    id: 'geography-044',
    category: 'geography',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many states does Australia have?',
    correct: 6,
    unit: 'states',
    explanation: 'The six are New South Wales, Victoria, Queensland, South Australia, Western Australia and Tasmania.',
  },
  {
    id: 'geography-045',
    category: 'geography',
    difficulty: 'hard',
    type: 'number',
    prompt: 'How many countries share a land border with Germany?',
    correct: 9,
    unit: 'countries',
    explanation: 'Denmark, Poland, Czechia, Austria, Switzerland, France, Luxembourg, Belgium and the Netherlands.',
  },

  // --- Put in order ---
  {
    id: 'geography-046',
    category: 'geography',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these U.S. cities in order from west to east.',
    items: ['San Francisco', 'Denver', 'Chicago', 'New York City'],
    ends: ['West', 'East'],
    explanation: 'San Francisco is on the Pacific coast, Denver near the Rockies, Chicago on Lake Michigan and New York on the Atlantic.',
  },
  {
    id: 'geography-047',
    category: 'geography',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these cities in order from north to south.',
    items: ['Oslo', 'Paris', 'Rome', 'Cape Town'],
    ends: ['Northernmost', 'Southernmost'],
    explanation: 'Oslo is near 60° N, Paris 49° N and Rome 42° N, while Cape Town is about 34° south of the Equator.',
  },
  {
    id: 'geography-048',
    category: 'geography',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Rank these mountains from tallest to shortest.',
    items: ['Mount Everest', 'Kilimanjaro', 'Mont Blanc', 'Mount Fuji'],
    ends: ['Tallest', 'Shortest'],
    explanation: 'Everest tops 8,800 m, Kilimanjaro is about 5,900 m, Mont Blanc about 4,800 m and Mount Fuji about 3,800 m.',
  },
];
