/**
 * DAStravaganza Trivia starter pack — history. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const HISTORY: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'history-001',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The Parthenon was built on the Acropolis of which ancient city?',
    options: ['Sparta', 'Athens', 'Corinth', 'Thebes'],
    correct: 1,
    explanation: 'The Parthenon, a temple dedicated to the goddess Athena, was completed in the 430s BC.',
  },
  {
    id: 'history-002',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Who was the first person to walk on the Moon?',
    options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'],
    correct: 2,
    explanation: 'Armstrong stepped onto the lunar surface during the Apollo 11 mission, with Buzz Aldrin following him out.',
  },
  {
    id: 'history-003',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: "The Terracotta Army was buried to guard the tomb of which country's first emperor?",
    options: ['Japan', 'Korea', 'Mongolia', 'China'],
    correct: 3,
    explanation: "Thousands of life-size clay soldiers were buried near Xi'an with Qin Shi Huang, who died in 210 BC.",
  },
  {
    id: 'history-004',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The ancient Olympic Games originated in which present-day country?',
    options: ['Italy', 'Greece', 'Egypt', 'Turkey'],
    correct: 1,
    explanation: 'The ancient games were held every four years at Olympia, in southern Greece.',
  },
  {
    id: 'history-005',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Around 1440, Johannes Gutenberg developed which world-changing invention in Europe?',
    options: ['The movable-type printing press', 'The mechanical clock', 'The telescope', 'The magnetic compass'],
    correct: 0,
    explanation: 'His press made books far cheaper to produce, and the Gutenberg Bible was printed in the 1450s.',
  },
  {
    id: 'history-006',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which country gave the Statue of Liberty to the United States?',
    options: ['France', 'Britain', 'Spain', 'Italy'],
    correct: 0,
    explanation: 'The statue was a gift from the people of France and was dedicated in New York Harbor in 1886.',
  },
  {
    id: 'history-007',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Julius Caesar was a famous general and statesman of which ancient civilization?',
    options: ['Ancient Greece', 'Ancient Persia', 'Ancient Egypt', 'Ancient Rome'],
    correct: 3,
    explanation: "Caesar's rise to power in the 1st century BC helped bring the Roman Republic to an end.",
  },
  {
    id: 'history-008',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which is the only one of the Seven Wonders of the Ancient World still largely standing?',
    options: ['Colossus of Rhodes', 'Hanging Gardens of Babylon', 'Great Pyramid of Giza', 'Temple of Artemis'],
    correct: 2,
    explanation: 'Built around 2560 BC, it remained the tallest human-made structure on Earth for thousands of years.',
  },
  {
    id: 'history-009',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which Roman city was buried by the eruption of Mount Vesuvius in AD 79?',
    options: ['Pompeii', 'Troy', 'Carthage', 'Knossos'],
    correct: 0,
    explanation: 'Volcanic ash preserved Pompeii so well that visitors can still walk its streets today.',
  },
  {
    id: 'history-010',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which French leader crowned himself Emperor of the French in 1804?',
    options: ['Louis XIV', 'Charlemagne', 'Napoleon Bonaparte', 'Louis XVI'],
    correct: 2,
    explanation: 'Napoleon famously placed the crown on his own head at Notre-Dame Cathedral in Paris.',
  },
  {
    id: 'history-011',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'The Vikings originally came from which region of Europe?',
    options: ['Scandinavia', 'Iberia', 'The Balkans', 'The Alps'],
    correct: 0,
    explanation: 'Viking seafarers set out from what are now Norway, Sweden and Denmark.',
  },
  {
    id: 'history-012',
    category: 'history',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which British nurse became known as "The Lady with the Lamp"?',
    options: ['Mary Seacole', 'Florence Nightingale', 'Edith Cavell', 'Clara Barton'],
    correct: 1,
    explanation: 'She earned the name making night rounds to care for soldiers during the Crimean War in the 1850s.',
  },

  // --- Multiple choice: medium ---
  {
    id: 'history-013',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which English king agreed to the Magna Carta at Runnymede?',
    options: ['King Henry VIII', 'King Richard I', 'King John', 'King Edward I'],
    correct: 2,
    explanation: 'Rebel barons pressured King John into accepting the charter, which placed limits on royal power.',
  },
  {
    id: 'history-014',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Who was the first human to travel into space?',
    options: ['Alan Shepard', 'Yuri Gagarin', 'John Glenn', 'Valentina Tereshkova'],
    correct: 1,
    explanation: "Gagarin's Vostok 1 flight made a single orbit of Earth in about 108 minutes.",
  },
  {
    id: 'history-015',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Tenochtitlan, a city built on an island in a lake, was the capital of which civilization?',
    options: ['Maya', 'Aztec', 'Inca', 'Olmec'],
    correct: 1,
    explanation: 'The Aztec capital stood on Lake Texcoco, where Mexico City is today.',
  },
  {
    id: 'history-016',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The ancient Wonder that stood at the harbor of Alexandria, Egypt, was what kind of structure?',
    options: ['A towering lighthouse', 'A giant bronze statue', 'A terraced garden', 'A marble tomb'],
    correct: 0,
    explanation: 'The Lighthouse of Alexandria, or Pharos, guided ships for centuries before earthquakes brought it down.',
  },
  {
    id: 'history-017',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Who was the principal author of the U.S. Declaration of Independence?',
    options: ['Benjamin Franklin', 'John Adams', 'James Madison', 'Thomas Jefferson'],
    correct: 3,
    explanation: 'Jefferson wrote the first draft, which Franklin, Adams and the Continental Congress then edited.',
  },
  {
    id: 'history-018',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which explorer led the Spanish expedition that set out in 1519 and made the first voyage around the world?',
    options: ['Ferdinand Magellan', 'Francis Drake', 'James Cook', 'Vasco da Gama'],
    correct: 0,
    explanation: 'Magellan died in the Philippines in 1521; Juan Sebastián Elcano brought the last ship home in 1522.',
  },
  {
    id: 'history-019',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In 1498, which explorer became the first European to reach India by sailing around Africa?',
    options: ['Bartolomeu Dias', 'Vasco da Gama', 'Christopher Columbus', 'Henry Hudson'],
    correct: 1,
    explanation: 'The Portuguese navigator landed near Calicut, opening a sea route for the spice trade.',
  },
  {
    id: 'history-020',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The Rosetta Stone was the key to deciphering which ancient script?',
    options: ['Cuneiform', 'Linear B', 'Egyptian hieroglyphs', 'Mayan glyphs'],
    correct: 2,
    explanation: 'It carries the same decree in hieroglyphs, Demotic and Ancient Greek, letting scholars compare them.',
  },
  {
    id: 'history-021',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In 1932, who became the first woman to fly solo across the Atlantic Ocean?',
    options: ['Bessie Coleman', 'Amy Johnson', 'Harriet Quimby', 'Amelia Earhart'],
    correct: 3,
    explanation: "Earhart flew from Newfoundland to Northern Ireland, five years to the day after Lindbergh's famous flight.",
  },
  {
    id: 'history-022',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which wealthy banking family ruled Florence for much of the Renaissance?',
    options: ['The Borgias', 'The Medici', 'The Habsburgs', 'The Sforzas'],
    correct: 1,
    explanation: 'The Medici were major patrons of artists such as Botticelli and Michelangelo.',
  },
  {
    id: 'history-023',
    category: 'history',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which explorer led the first expedition to reach the South Pole, in 1911?',
    options: ['Robert Falcon Scott', 'Ernest Shackleton', 'Roald Amundsen', 'Richard Byrd'],
    correct: 2,
    explanation: "Amundsen's Norwegian team arrived on December 14, 1911, about five weeks before Scott's British party.",
  },

  // --- Multiple choice: hard ---
  {
    id: 'history-024',
    category: 'history',
    difficulty: 'hard',
    type: 'mc',
    prompt: "Which ancient people developed cuneiform, one of the world's earliest writing systems?",
    options: ['Sumerians', 'Phoenicians', 'Hittites', 'Minoans'],
    correct: 0,
    explanation: 'Scribes in Sumer, in Mesopotamia, pressed wedge-shaped marks into clay tablets more than 5,000 years ago.',
  },
  {
    id: 'history-025',
    category: 'history',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Most of the Great Wall of China that survives today was built during which dynasty?',
    options: ['Qin', 'Han', 'Tang', 'Ming'],
    correct: 3,
    explanation: 'Earlier walls go back over 2,000 years, but the familiar brick-and-stone sections are mostly Ming.',
  },
  {
    id: 'history-026',
    category: 'history',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Who made the first-ever spacewalk?',
    options: ['Gherman Titov', 'Alexei Leonov', 'Ed White', 'Yuri Gagarin'],
    correct: 1,
    explanation: 'In March 1965, Leonov spent about 12 minutes outside his Voskhod 2 spacecraft.',
  },
  {
    id: 'history-027',
    category: 'history',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The Code of Hammurabi was issued by a king of which ancient city?',
    options: ['Nineveh', 'Memphis', 'Babylon', 'Troy'],
    correct: 2,
    explanation: 'His laws were carved on a tall stone stele that is now displayed in the Louvre in Paris.',
  },
  {
    id: 'history-028',
    category: 'history',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The medieval Hanseatic League was a trading network centered mainly on which sea?',
    options: ['Mediterranean Sea', 'Baltic Sea', 'Black Sea', 'Caspian Sea'],
    correct: 1,
    explanation: 'Merchant towns such as Lübeck, Hamburg and Danzig (Gdańsk) banded together to protect their trade.',
  },

  // --- True / false ---
  {
    id: 'history-029',
    category: 'history',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The Berlin Wall fell in 1989.',
    correct: true,
    explanation: 'Crowds began crossing and chipping away at the wall after the border opened on November 9, 1989.',
  },
  {
    id: 'history-030',
    category: 'history',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The Titanic sank in the Pacific Ocean.',
    correct: false,
    explanation: 'The Titanic sank in the North Atlantic in April 1912 after striking an iceberg on its way to New York.',
  },
  {
    id: 'history-031',
    category: 'history',
    difficulty: 'medium',
    type: 'tf',
    prompt: "The Eiffel Tower was built for a World's Fair held in Paris in 1889.",
    correct: true,
    explanation: 'It served as the entrance arch to the 1889 Exposition Universelle, held 100 years after the French Revolution began.',
  },
  {
    id: 'history-032',
    category: 'history',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The U.S. Declaration of Independence was signed in Boston.',
    correct: false,
    explanation: 'It was adopted and signed in Philadelphia, in the building now known as Independence Hall.',
  },
  {
    id: 'history-033',
    category: 'history',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The United States bought Alaska from Russia in 1867.',
    correct: true,
    explanation: 'The price was $7.2 million, or roughly two cents per acre.',
  },
  {
    id: 'history-034',
    category: 'history',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Leaning Tower of Pisa was designed to lean.',
    correct: false,
    explanation: 'The tower began to tilt during construction in the late 1100s because its foundations sat on soft ground.',
  },
  {
    id: 'history-035',
    category: 'history',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Abraham Lincoln and Charles Darwin were born on the same day.',
    correct: true,
    explanation: 'Both were born on February 12, 1809: Lincoln in Kentucky and Darwin in Shrewsbury, England.',
  },
  {
    id: 'history-036',
    category: 'history',
    difficulty: 'hard',
    type: 'tf',
    prompt: "The Hundred Years' War lasted exactly one hundred years.",
    correct: false,
    explanation: 'The on-and-off conflict between England and France ran from 1337 to 1453, about 116 years, with long truces.',
  },

  // --- Type the answer ---
  {
    id: 'history-037',
    category: 'history',
    difficulty: 'easy',
    type: 'text',
    prompt: 'Who was the first President of the United States?',
    accept: ['George Washington', 'Washington'],
    explanation: 'Washington took office in 1789 and served two terms.',
  },
  {
    id: 'history-038',
    category: 'history',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What was the name of the ship that carried the Pilgrims to America in 1620?',
    accept: ['Mayflower'],
    explanation: 'The Mayflower anchored off Cape Cod before the settlers founded Plymouth Colony.',
  },
  {
    id: 'history-039',
    category: 'history',
    difficulty: 'medium',
    type: 'text',
    prompt: "Which Egyptian pharaoh's nearly intact tomb did Howard Carter uncover in 1922?",
    accept: ['Tutankhamun', 'Tutankhamen', 'Tutankhamon', 'King Tut', 'Tut'],
    explanation: 'The tomb in the Valley of the Kings held more than 5,000 objects, including a solid-gold inner coffin.',
  },
  {
    id: 'history-040',
    category: 'history',
    difficulty: 'medium',
    type: 'text',
    prompt: 'Which New Zealander reached the summit of Mount Everest with Tenzing Norgay in 1953?',
    accept: ['Edmund Hillary', 'Hillary', 'Sir Edmund Hillary', 'Ed Hillary', 'Sir Ed Hillary'],
    explanation: 'Hillary and Tenzing stood on the summit on May 29, 1953.',
  },
  {
    id: 'history-041',
    category: 'history',
    difficulty: 'hard',
    type: 'text',
    prompt: 'Which Carthaginian general famously led an army with war elephants across the Alps to invade Italy?',
    accept: ['Hannibal', 'Hannibal Barca'],
    explanation: 'Hannibal made his famous crossing in 218 BC, during the Second Punic War against Rome.',
  },

  // --- Closest number ---
  {
    id: 'history-042',
    category: 'history',
    difficulty: 'easy',
    type: 'number',
    prompt: 'In what year did Apollo 11 land on the Moon?',
    correct: 1969,
    explanation: 'Apollo 11 touched down in the Sea of Tranquility in July 1969.',
  },
  {
    id: 'history-043',
    category: 'history',
    difficulty: 'easy',
    type: 'number',
    prompt: 'In what year was the U.S. Declaration of Independence adopted?',
    correct: 1776,
    explanation: 'The Continental Congress adopted it on July 4, 1776.',
  },
  {
    id: 'history-044',
    category: 'history',
    difficulty: 'medium',
    type: 'number',
    prompt: "In what year did Christopher Columbus's first voyage reach the Americas?",
    correct: 1492,
    explanation: 'His ships made landfall in the Bahamas in October 1492.',
  },
  {
    id: 'history-045',
    category: 'history',
    difficulty: 'hard',
    type: 'number',
    prompt: 'In what year was the Magna Carta sealed?',
    correct: 1215,
    explanation: 'The charter was sealed at Runnymede, beside the River Thames, in June 1215.',
  },

  // --- Put in order ---
  {
    id: 'history-046',
    category: 'history',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these events in chronological order.',
    items: [
      'Great Pyramid of Giza is built',
      'Roman Colosseum opens',
      'Shakespeare writes Hamlet',
      'Lindbergh flies solo across the Atlantic',
    ],
    ends: ['Earliest', 'Latest'],
    explanation: 'Roughly 2560 BC, AD 80, around 1600, and 1927.',
  },
  {
    id: 'history-047',
    category: 'history',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these space-race milestones in chronological order.',
    items: ['First human in space', 'First spacewalk', 'First crewed Moon landing', 'First Space Shuttle launch'],
    ends: ['Earliest', 'Latest'],
    explanation:
      'The Soviet Union put the first person in space and made the first spacewalk; the United States landed on the Moon and later launched the Shuttle.',
  },
  {
    id: 'history-048',
    category: 'history',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Put these events of the ancient world in chronological order.',
    items: [
      'Code of Hammurabi is carved',
      'First recorded Olympic Games',
      'Library of Alexandria is founded',
      'Western Roman Empire falls',
    ],
    ends: ['Earliest', 'Latest'],
    explanation: 'About 1750 BC, 776 BC, around 300 BC, and AD 476.',
  },
];
