/**
 * DAStravaganza Trivia starter pack — nonsense. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const NONSENSE: StarterQuestion[] = [
  // ---------------------------------------------------------------- multiple choice — easy
  {
    id: 'nonsense-001',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What gets wetter and wetter the more it dries?',
    options: ['A candle', 'A towel', 'A mirror', 'A shadow'],
    correct: 1,
    explanation: 'A towel soaks up more water the more things it dries.',
  },
  {
    id: 'nonsense-002',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What has a neck but no head?',
    options: ['A snake', 'A giraffe', 'A bottle', 'A pillow'],
    correct: 2,
    explanation: 'A bottle has a neck, but only a cap sits on top of it.',
  },
  {
    id: 'nonsense-003',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What has hands but can’t clap?',
    options: ['A map', 'A ruler', 'A sock', 'A clock'],
    correct: 3,
    explanation: 'A clock’s hands point at the time but never applaud.',
  },
  {
    id: 'nonsense-004',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What has one eye but can’t see a thing?',
    options: ['A needle', 'A spoon', 'A cup', 'A pencil'],
    correct: 0,
    explanation: 'The "eye" of a needle is the hole the thread goes through.',
  },
  {
    id: 'nonsense-005',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What can you catch but never throw?',
    options: ['A ball', 'A cold', 'A frisbee', 'A pillow'],
    correct: 1,
    explanation: 'You can catch a cold, but you can’t toss one back.',
  },
  {
    id: 'nonsense-006',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What goes up and up but never comes down?',
    options: ['A balloon', 'An elevator', 'Your age', 'A kite'],
    correct: 2,
    explanation: 'Every birthday your age goes up, and it never goes back down.',
  },
  {
    id: 'nonsense-007',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What has lots of teeth but never bites?',
    options: ['A hammer', 'A spoon', 'A brick', 'A comb'],
    correct: 3,
    explanation: 'A comb’s teeth only ever tackle tangles.',
  },
  {
    id: 'nonsense-008',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What has to be broken before you can use it?',
    options: ['An egg', 'A window', 'A pencil', 'A mirror'],
    correct: 0,
    explanation: 'No omelet happens until the egg is cracked.',
  },
  {
    id: 'nonsense-009',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'If a task is "a piece of cake", it is…',
    options: ['Delicious', 'Very easy', 'Expensive', 'Half-finished'],
    correct: 1,
    explanation: 'The idiom means something is very easy to do.',
  },
  {
    id: 'nonsense-010',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What does it mean to "spill the beans"?',
    options: ['Waste money', 'Start an argument', 'Reveal a secret', 'Give up easily'],
    correct: 2,
    explanation: 'Spilling the beans means letting a secret slip out.',
  },
  {
    id: 'nonsense-011',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which has more mass: a kilogram of feathers or a kilogram of bricks?',
    options: ['The bricks', 'The feathers', 'It depends on the weather', 'They have exactly the same mass'],
    correct: 3,
    explanation: 'A kilogram is a kilogram; the feathers just take up a lot more room.',
  },
  {
    id: 'nonsense-012',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'When it’s "raining cats and dogs", the rain is…',
    options: ['Very heavy', 'Very light', 'Warm', 'About to stop'],
    correct: 0,
    explanation: 'The idiom means it is pouring down. No pets fall from the sky.',
  },

  // ---------------------------------------------------------------- multiple choice — medium
  {
    id: 'nonsense-013',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The more of these you take, the more you leave behind. What are they?',
    options: ['Photos', 'Footsteps', 'Naps', 'Cookies'],
    correct: 1,
    explanation: 'Every step you take leaves another footstep behind you.',
  },
  {
    id: 'nonsense-014',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What has cities but no houses, forests but no trees, and rivers but no fish?',
    options: ['A calendar', 'A mirror', 'A map', 'A telephone'],
    correct: 2,
    explanation: 'A map shows cities, forests and rivers without containing any of them.',
  },
  {
    id: 'nonsense-015',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What comes once in a minute, twice in a moment, but never in a thousand years?',
    options: ['The letter T', 'The letter O', 'The letter I', 'The letter M'],
    correct: 3,
    explanation: '"Minute" has one M, "moment" has two, and "a thousand years" has none.',
  },
  {
    id: 'nonsense-016',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What kind of room has no doors and no windows?',
    options: ['A mushroom', 'A ballroom', 'A classroom', 'A bathroom'],
    correct: 0,
    explanation: 'A mushroom is a "room" you can grow, but never walk into.',
  },
  {
    id: 'nonsense-017',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'It’s black when you buy it, red when you use it, and gray when you’re done. What is it?',
    options: ['A tea bag', 'Charcoal', 'A pencil', 'A chili pepper'],
    correct: 1,
    explanation: 'Charcoal starts black, glows red on the grill and ends up as gray ash.',
  },
  {
    id: 'nonsense-018',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What can travel all around the world while staying in one corner?',
    options: ['A spider', 'A compass', 'A stamp', 'A suitcase'],
    correct: 2,
    explanation: 'A postage stamp rides in the corner of an envelope wherever the mail goes.',
  },
  {
    id: 'nonsense-019',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'If you have me, you want to share me. Once you share me, you no longer have me. What am I?',
    options: ['A song', 'A joke', 'An umbrella', 'A secret'],
    correct: 3,
    explanation: 'Once a secret is shared, it isn’t a secret anymore.',
  },
  {
    id: 'nonsense-020',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which word has a whole "mile" between its first and last letters?',
    options: ['Smiles', 'Milestone', 'Mileage', 'Kilometers'],
    correct: 0,
    explanation: 'S-MILE-S: there is a "mile" between the two S’s.',
  },
  {
    id: 'nonsense-021',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What letter comes next: J, F, M, A, M, J, J, A, S, O, N, …?',
    options: ['P', 'D', 'E', 'J'],
    correct: 1,
    explanation: 'They are the first letters of the months, so D for December comes next.',
  },
  {
    id: 'nonsense-022',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which word, written in capital letters, still reads the same when you turn it upside down?',
    options: ['SLEEPS', 'WALKS', 'SWIMS', 'JUMPS'],
    correct: 2,
    explanation: 'Rotate SWIMS halfway around: the S’s and I stay put and the W and M swap places.',
  },
  {
    id: 'nonsense-023',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What begins with T, ends with T, and has T in it?',
    options: ['A kettle', 'A tea bag', 'A teacup', 'A teapot'],
    correct: 3,
    explanation: '"Teapot" starts and ends with the letter T, and it has tea in it.',
  },

  // ---------------------------------------------------------------- multiple choice — hard
  {
    id: 'nonsense-024',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which phrase uses exactly the same letters as "DORMITORY"?',
    options: ['Dirty room', 'Dry motor', 'Tidy mirror', 'Moody tram'],
    correct: 0,
    explanation: 'DORMITORY rearranges into DIRTY ROOM, a fitting anagram.',
  },
  {
    id: 'nonsense-025',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which word contains the vowels A, E, I, O and U exactly once each, in alphabetical order?',
    options: ['Education', 'Facetious', 'Sequoia', 'Dialogue'],
    correct: 1,
    explanation: 'F-A-c-E-t-I-O-U-s. The other three use all five vowels, but out of order.',
  },
  {
    id: 'nonsense-026',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which word has three double letters back to back, with nothing in between?',
    options: ['Committee', 'Mississippi', 'Bookkeeper', 'Balloon'],
    correct: 2,
    explanation: 'B-OO-KK-EE-per. Committee and Mississippi have three doubles too, but with letters in between.',
  },
  {
    id: 'nonsense-027',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'What letter comes next: O, T, T, F, F, S, S, E, …?',
    options: ['T', 'E', 'O', 'N'],
    correct: 3,
    explanation: 'One, Two, Three, Four, Five, Six, Seven, Eight… so Nine is next.',
  },
  {
    id: 'nonsense-028',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which number, spelled out in English, has all of its letters in alphabetical order?',
    options: ['Forty', 'Sixty', 'Eighty', 'Twenty'],
    correct: 0,
    explanation: 'F, O, R, T, Y: each letter comes later in the alphabet than the one before.',
  },

  // ---------------------------------------------------------------- true / false
  {
    id: 'nonsense-029',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Spelled backwards, "stressed" becomes "desserts".',
    correct: true,
    explanation: 'S-T-R-E-S-S-E-D reversed is D-E-S-S-E-R-T-S. Sweet!',
  },
  {
    id: 'nonsense-030',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'If you overtake the runner in second place during a race, you move into first place.',
    correct: false,
    explanation: 'You take their spot, so you are now in second place; the leader is still ahead of you.',
  },
  {
    id: 'nonsense-031',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'The word "palindrome" is itself a palindrome.',
    correct: false,
    explanation: 'Backwards it is "emordnilap". Words like "level" and "racecar" are palindromes.',
  },
  {
    id: 'nonsense-032',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The word "typewriter" can be typed using only the top row of letters on a QWERTY keyboard.',
    correct: true,
    explanation: 'T, Y, P, E, W, R and I all sit on the top letter row: Q W E R T Y U I O P.',
  },
  {
    id: 'nonsense-033',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Remove the last four letters of "queue" and it is still pronounced the same.',
    correct: true,
    explanation: 'Drop "ueue" and you are left with "Q", which sounds exactly like "queue".',
  },
  {
    id: 'nonsense-034',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'On a standard 12-hour clock, the hour and minute hands overlap exactly 24 times a day.',
    correct: false,
    explanation:
      'Only 22 times: the minute hand catches the hour hand 11 times every 12 hours, as the catch-up due just after 11 o’clock lands exactly at 12.',
  },
  {
    id: 'nonsense-035',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'The phrases "eleven plus two" and "twelve plus one" use exactly the same letters.',
    correct: true,
    explanation: 'They are perfect anagrams of each other, and both add up to thirteen.',
  },
  {
    id: 'nonsense-036',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'A googol is a 1 followed by 1,000 zeros.',
    correct: false,
    explanation: 'A googol is a 1 followed by 100 zeros; a mathematician’s young nephew came up with the name.',
  },

  // ---------------------------------------------------------------- type the answer
  {
    id: 'nonsense-037',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What gets bigger the more you take away from it?',
    accept: ['Hole', 'Pit', 'Ditch'],
    explanation: 'Dig more dirt out of a hole and it only grows.',
  },
  {
    id: 'nonsense-038',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'text',
    prompt: 'I’m tall when I’m young, short when I’m old, and I glow as I shrink. What am I?',
    accept: ['Candle', 'Candles'],
    explanation: 'A candle burns down shorter and shorter as it gives off light.',
  },
  {
    id: 'nonsense-039',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'text',
    prompt: 'Which word becomes shorter when you add two letters to it?',
    accept: ['Short'],
    explanation: 'Add "er" to "short" and it becomes "shorter".',
  },
  {
    id: 'nonsense-040',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'text',
    prompt: 'Which letter of the alphabet doesn’t appear in the name of any U.S. state?',
    accept: ['Q', 'Letter Q'],
    explanation: 'Every other letter shows up somewhere, even J (New Jersey), X (Texas) and Z (Arizona).',
  },
  {
    id: 'nonsense-041',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'text',
    prompt: 'Forward I’m heavy, but backward I’m not. What am I?',
    accept: ['Ton', 'Tons'],
    explanation: 'Spell "ton" backwards and you get "not".',
  },

  // ---------------------------------------------------------------- closest number
  {
    id: 'nonsense-042',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'number',
    prompt: 'A farmer has 17 sheep. All but 9 wander off. How many sheep are left?',
    correct: 9,
    unit: 'sheep',
    explanation: '"All but 9" means 9 of them stayed put.',
  },
  {
    id: 'nonsense-043',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'number',
    prompt: 'Divide 30 by one half, then add 10. What do you get?',
    correct: 70,
    explanation: 'Dividing by one half doubles a number: 30 ÷ ½ = 60, and 60 + 10 = 70.',
  },
  {
    id: 'nonsense-044',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'number',
    prompt: 'A patch of lily pads doubles in size every day. It covers the whole pond on day 48. On which day did it cover half the pond?',
    correct: 47,
    explanation: 'It doubles daily, so it was exactly half the size one day earlier.',
  },
  {
    id: 'nonsense-045',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'number',
    prompt: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How many cents does the ball cost?',
    correct: 5,
    unit: 'cents',
    explanation: 'Ball 5¢ + bat $1.05 = $1.10. A 10¢ ball would make the bat only 90¢ more expensive.',
  },

  // ---------------------------------------------------------------- put in order
  {
    id: 'nonsense-046',
    category: 'nonsense',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these greetings in order by how many letters they have.',
    items: ['Hi', 'Hey', 'Hiya', 'Hello'],
    ends: ['Fewest letters', 'Most letters'],
    explanation: 'Hi (2), Hey (3), Hiya (4), Hello (5).',
  },
  {
    id: 'nonsense-047',
    category: 'nonsense',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these number words in order by how many letters they have.',
    items: ['One', 'Four', 'Three', 'Eleven'],
    ends: ['Fewest letters', 'Most letters'],
    explanation: 'One (3), Four (4), Three (5), Eleven (6). Three has more letters than four!',
  },
  {
    id: 'nonsense-048',
    category: 'nonsense',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Put these amounts in order, from smallest to largest.',
    items: ['A pair', 'A dozen', 'A score', 'A gross'],
    ends: ['Smallest', 'Largest'],
    explanation: 'A pair is 2, a dozen 12, a score 20 and a gross 144 (a dozen dozens).',
  },
];
