/**
 * DAStravaganza Trivia starter pack — science. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const SCIENCE: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'science-001',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which planet is nicknamed the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
    correct: 1,
    explanation: 'Iron oxide — rust — in its dust and rocks gives Mars its reddish colour.',
  },
  {
    id: 'science-002',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which gas do plants take in from the air to carry out photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Hydrogen', 'Carbon dioxide'],
    correct: 3,
    explanation: 'Plants use sunlight to turn carbon dioxide and water into sugar, releasing oxygen.',
  },
  {
    id: 'science-003',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which is the largest planet in our solar system?',
    options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'],
    correct: 2,
    explanation: 'Jupiter is more than twice as massive as all the other planets combined.',
  },
  {
    id: 'science-004',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How many legs does a spider have?',
    options: ['6', '8', '10', '12'],
    correct: 1,
    fixedOrder: true,
    explanation: 'Spiders are arachnids — the same group as scorpions, ticks and mites — not insects.',
  },
  {
    id: 'science-005',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the nearest star to Earth?',
    options: ['Proxima Centauri', 'Sirius', 'The Sun', 'Polaris'],
    correct: 2,
    explanation: 'The Sun is a star! The next closest, Proxima Centauri, is about 4.2 light-years away.',
  },
  {
    id: 'science-006',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'A frog belongs to which group of animals?',
    options: ['Reptiles', 'Amphibians', 'Mammals', 'Fish'],
    correct: 1,
    explanation: 'Most amphibians start life in water as larvae — tadpoles, in the case of frogs — before living partly on land.',
  },
  {
    id: 'science-007',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What do honeybees collect from flowers to turn into honey?',
    options: ['Pollen', 'Sap', 'Dew', 'Nectar'],
    correct: 3,
    explanation: 'Bees evaporate water from sugary nectar to make honey; pollen is gathered mainly as protein food.',
  },
  {
    id: 'science-008',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the largest organ of the human body?',
    options: ['Liver', 'Skin', 'Brain', 'Lungs'],
    correct: 1,
    explanation: 'An adult’s skin covers roughly 1.5 to 2 square metres; the liver is the largest internal organ.',
  },
  {
    id: 'science-009',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which of these animals is a mammal?',
    options: ['Shark', 'Salmon', 'Octopus', 'Dolphin'],
    correct: 3,
    explanation: 'Dolphins breathe air, are warm-blooded and feed their young on milk.',
  },
  {
    id: 'science-010',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How many chambers does the human heart have?',
    options: ['2', '3', '4', '6'],
    correct: 2,
    fixedOrder: true,
    explanation: 'Two atria on top receive blood, and two ventricles below pump it out.',
  },
  {
    id: 'science-011',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which force keeps the planets in orbit around the Sun?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Static electricity'],
    correct: 2,
    explanation:
      'The Sun’s gravity constantly pulls on each planet, bending its path into an orbit instead of letting it fly off in a straight line.',
  },
  {
    id: 'science-012',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the largest animal living on Earth today?',
    options: ['African elephant', 'Giant squid', 'Whale shark', 'Blue whale'],
    correct: 3,
    explanation: 'Blue whales can grow to around 30 metres long.',
  },
  {
    id: 'science-013',
    category: 'science',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which blood cells carry oxygen around the body?',
    options: ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma cells'],
    correct: 0,
    explanation: 'Red blood cells are packed with haemoglobin, an iron-rich protein that binds oxygen.',
  },

  // --- Multiple choice: medium ---
  {
    id: 'science-014',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which gas makes up most of Earth’s atmosphere?',
    options: ['Oxygen', 'Argon', 'Carbon dioxide', 'Nitrogen'],
    correct: 3,
    explanation: 'Dry air is about 78% nitrogen and 21% oxygen.',
  },
  {
    id: 'science-015',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which vitamin does your skin make when it is exposed to sunlight?',
    options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
    correct: 2,
    explanation: 'Ultraviolet B light triggers vitamin D production in the skin.',
  },
  {
    id: 'science-016',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which element has the chemical symbol Fe?',
    options: ['Fluorine', 'Iron', 'Lead', 'Francium'],
    correct: 1,
    explanation: 'Fe comes from “ferrum”, the Latin word for iron.',
  },
  {
    id: 'science-017',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which part of a cell is nicknamed its “powerhouse”?',
    options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Cell membrane'],
    correct: 2,
    explanation: 'Mitochondria release energy from food molecules to make ATP, the cell’s energy currency.',
  },
  {
    id: 'science-018',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Roughly how long does sunlight take to reach Earth?',
    options: ['About 8 seconds', 'About 8 minutes', 'About 8 hours', 'About 8 days'],
    correct: 1,
    fixedOrder: true,
    explanation: 'Light crosses the roughly 150 million km from the Sun in about 8 minutes 20 seconds.',
  },
  {
    id: 'science-019',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What is the SI unit of force?',
    options: ['Joule', 'Watt', 'Pascal', 'Newton'],
    correct: 3,
    explanation: 'One newton accelerates a 1 kg mass by 1 metre per second squared.',
  },
  {
    id: 'science-020',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which coloured part of the eye controls how much light gets in by changing the size of the pupil?',
    options: ['Retina', 'Iris', 'Cornea', 'Lens'],
    correct: 1,
    explanation: 'The iris is a ring of muscle that shrinks the pupil in bright light and widens it in the dark.',
  },
  {
    id: 'science-021',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'How many hearts does an octopus have?',
    options: ['1', '2', '3', '4'],
    correct: 2,
    fixedOrder: true,
    explanation: 'Two hearts pump blood through the gills, and a third pumps it around the rest of the body.',
  },
  {
    id: 'science-022',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which naturalist wrote “On the Origin of Species”, published in 1859?',
    options: ['Charles Darwin', 'Gregor Mendel', 'Alfred Russel Wallace', 'Carl Linnaeus'],
    correct: 0,
    explanation: 'Darwin’s book set out his theory of evolution by natural selection.',
  },
  {
    id: 'science-023',
    category: 'science',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Rock that forms when magma or lava cools and hardens is called what?',
    options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossilised'],
    correct: 2,
    explanation: 'Granite and basalt are two common igneous rocks.',
  },

  // --- Multiple choice: hard ---
  {
    id: 'science-024',
    category: 'science',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Marie Curie won Nobel Prizes in which two fields?',
    options: ['Physics and Chemistry', 'Chemistry and Medicine', 'Physics and Medicine', 'Chemistry and Peace'],
    correct: 0,
    explanation: 'She shared the 1903 Nobel Prize in Physics and won the 1911 Nobel Prize in Chemistry on her own.',
  },
  {
    id: 'science-025',
    category: 'science',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'What is the smallest bone in the human body?',
    options: ['Incus', 'Malleus', 'Hyoid', 'Stapes'],
    correct: 3,
    explanation: 'The stirrup-shaped stapes in the middle ear is only about 3 mm long.',
  },
  {
    id: 'science-026',
    category: 'science',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which planet spins tipped over on its side, with an axial tilt of about 98°?',
    options: ['Uranus', 'Neptune', 'Saturn', 'Venus'],
    correct: 0,
    explanation:
      'Its extreme tilt gives Uranus very long seasons: each pole spends decades in constant sunlight, then decades in darkness.',
  },
  {
    id: 'science-027',
    category: 'science',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which part of a flower produces pollen?',
    options: ['Stigma', 'Ovary', 'Anther', 'Sepal'],
    correct: 2,
    explanation: 'The anther sits on a stalk called the filament; together they form the stamen.',
  },
  {
    id: 'science-028',
    category: 'science',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which element is the most abundant in Earth’s crust by mass?',
    options: ['Silicon', 'Oxygen', 'Iron', 'Aluminium'],
    correct: 1,
    explanation: 'Oxygen makes up nearly half of the crust’s mass, mostly locked up in silicate minerals.',
  },

  // --- True or false ---
  {
    id: 'science-029',
    category: 'science',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Water expands when it freezes.',
    correct: true,
    explanation: 'That’s why ice floats and why frozen water pipes can burst.',
  },
  {
    id: 'science-030',
    category: 'science',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Sound can travel through the vacuum of space.',
    correct: false,
    explanation: 'Sound needs a medium such as air, water or rock to travel through.',
  },
  {
    id: 'science-031',
    category: 'science',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Jupiter’s Great Red Spot is a giant storm.',
    correct: true,
    explanation: 'It is a vast, long-lived high-pressure storm that astronomers have watched for well over 150 years.',
  },
  {
    id: 'science-032',
    category: 'science',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Lightning never strikes the same place twice.',
    correct: false,
    explanation: 'Tall structures are hit again and again — the Empire State Building is struck many times a year.',
  },
  {
    id: 'science-033',
    category: 'science',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Diamond and graphite are both forms of carbon.',
    correct: true,
    explanation: 'The same carbon atoms, arranged differently, give hard diamond and soft, slippery graphite.',
  },
  {
    id: 'science-034',
    category: 'science',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'An adult human has more bones than a newborn baby.',
    correct: false,
    explanation: 'Babies have more separate bony parts; many fuse together as they grow, leaving 206 bones in a typical adult.',
  },
  {
    id: 'science-035',
    category: 'science',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Humans use only about 10% of their brains.',
    correct: false,
    explanation: 'Brain scans show activity throughout the brain, and nearly every region has a known job.',
  },
  {
    id: 'science-036',
    category: 'science',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Helium is the second most abundant element in the universe.',
    correct: true,
    explanation: 'Only hydrogen is more common; together the two make up about 98% of the ordinary matter in the universe by mass.',
  },

  // --- Type the answer ---
  {
    id: 'science-037',
    category: 'science',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What is the name of the galaxy that contains our solar system?',
    accept: ['Milky Way', 'Milky Way Galaxy'],
    explanation: 'The Milky Way is a barred spiral galaxy containing hundreds of billions of stars.',
  },
  {
    id: 'science-038',
    category: 'science',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What green pigment do plants use to capture energy from sunlight?',
    accept: ['Chlorophyll'],
    explanation: 'Chlorophyll absorbs mostly red and blue light and reflects green, which is why leaves look green.',
  },
  {
    id: 'science-039',
    category: 'science',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What is the longest bone in the human body?',
    accept: ['Femur', 'Thigh bone'],
    explanation: 'The femur runs from the hip to the knee.',
  },
  {
    id: 'science-040',
    category: 'science',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What is the chemical symbol for potassium?',
    accept: ['K'],
    explanation: 'K comes from “kalium”, the element’s Latin name.',
  },
  {
    id: 'science-041',
    category: 'science',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What is the name of the boundary around a black hole beyond which not even light can escape?',
    accept: ['Event horizon'],
    explanation: 'Anything that crosses the event horizon can never come back out.',
  },

  // --- Closest number ---
  {
    id: 'science-042',
    category: 'science',
    difficulty: 'medium',
    type: 'number',
    prompt: 'At sea level, what is the boiling point of water in degrees Fahrenheit?',
    correct: 212,
    unit: '°F',
    explanation: 'That’s 100 °C; water freezes at 32 °F.',
  },
  {
    id: 'science-043',
    category: 'science',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many chromosomes are in a typical human body cell?',
    correct: 46,
    unit: 'chromosomes',
    explanation: 'They come in 23 pairs — one set from each parent.',
  },
  {
    id: 'science-044',
    category: 'science',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many teeth are in a full set of adult human teeth, including wisdom teeth?',
    correct: 32,
    unit: 'teeth',
    explanation: 'Children have 20 baby teeth before the adult set comes through.',
  },
  {
    id: 'science-045',
    category: 'science',
    difficulty: 'hard',
    type: 'number',
    prompt: 'What is absolute zero on the Celsius scale?',
    correct: -273.15,
    unit: '°C',
    explanation: 'Absolute zero is 0 kelvin, the lowest temperature possible.',
  },

  // --- Put in order ---
  {
    id: 'science-046',
    category: 'science',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these planets in order of distance from the Sun, nearest first.',
    items: ['Mercury', 'Earth', 'Saturn', 'Uranus'],
    ends: ['Nearest', 'Farthest'],
    explanation: 'The full order is Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune.',
  },
  {
    id: 'science-047',
    category: 'science',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Order Earth’s layers from the surface down to the centre.',
    items: ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    ends: ['Surface', 'Centre'],
    explanation: 'The outer core is liquid metal, while the inner core is kept solid by immense pressure.',
  },
  {
    id: 'science-048',
    category: 'science',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Order these types of electromagnetic radiation from longest wavelength to shortest.',
    items: ['Radio waves', 'Infrared', 'Ultraviolet', 'Gamma rays'],
    ends: ['Longest wavelength', 'Shortest wavelength'],
    explanation: 'Visible light sits between infrared and ultraviolet on the spectrum.',
  },
];
