/**
 * DAStravaganza Trivia starter pack — screen. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const SCREEN: StarterQuestion[] = [
  // ---------------------------------------------------------------- multiple choice — easy
  {
    id: 'screen-001',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which studio made "Toy Story" (1995), the first feature film animated entirely by computer?',
    options: ['Pixar', 'DreamWorks Animation', 'Blue Sky Studios', 'Illumination'],
    correct: 0,
    explanation: 'Pixar produced "Toy Story" and Disney distributed it; it was the first fully computer-animated feature.',
  },
  {
    id: 'screen-002',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In "The Wizard of Oz" (1939), what is the name of Dorothy’s little dog?',
    options: ['Benji', 'Toto', 'Rover', 'Max'],
    correct: 1,
    explanation: 'Toto, a Cairn Terrier, follows Dorothy from Kansas all the way to Oz.',
  },
  {
    id: 'screen-003',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which school of witchcraft and wizardry does Harry Potter attend?',
    options: ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny'],
    correct: 2,
    explanation: 'Harry attends Hogwarts; Durmstrang and Beauxbatons visit it for the Triwizard Tournament.',
  },
  {
    id: 'screen-004',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What is the name of the cheerful talking snowman in Disney’s "Frozen" (2013)?',
    options: ['Sven', 'Kristoff', 'Hans', 'Olaf'],
    correct: 3,
    explanation: 'Olaf is the snowman; Sven is the reindeer, Kristoff the ice harvester and Hans the prince.',
  },
  {
    id: 'screen-005',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which sitcom’s friends spend much of their time in a coffee house called Central Perk?',
    options: ['Friends', 'Seinfeld', 'How I Met Your Mother', 'The Big Bang Theory'],
    correct: 0,
    explanation: 'Central Perk is the Manhattan coffee house where the "Friends" gang hangs out.',
  },
  {
    id: 'screen-006',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In "Star Wars", what is the name of Han Solo’s famously fast ship?',
    options: ['Serenity', 'Millennium Falcon', 'Nostromo', 'Galactica'],
    correct: 1,
    explanation: 'Han Solo won the Millennium Falcon from Lando Calrissian in a card game.',
  },
  {
    id: 'screen-007',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What kind of fish is Nemo in Pixar’s "Finding Nemo" (2003)?',
    options: ['Blue tang', 'Pufferfish', 'Clownfish', 'Angelfish'],
    correct: 2,
    explanation: 'Nemo and his dad Marlin are clownfish; their friend Dory is a blue tang.',
  },
  {
    id: 'screen-008',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which cartoon character’s catchphrase is "What’s up, Doc?"',
    options: ['Daffy Duck', 'Porky Pig', 'Woody Woodpecker', 'Bugs Bunny'],
    correct: 3,
    explanation: 'Bugs Bunny, the Looney Tunes star, usually says it while munching a carrot.',
  },
  {
    id: 'screen-009',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In which town does TV’s Simpson family live?',
    options: ['Springfield', 'Quahog', 'Arlen', 'Riverdale'],
    correct: 0,
    explanation: 'The Simpsons live in Springfield, a town whose state is famously never revealed.',
  },
  {
    id: 'screen-010',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which TV comedy is set at the Scranton branch of the paper company Dunder Mifflin?',
    options: ['Parks and Recreation', 'The Office', '30 Rock', 'Superstore'],
    correct: 1,
    explanation: 'The American version of "The Office" follows the staff of Dunder Mifflin in Scranton, Pennsylvania.',
  },
  {
    id: 'screen-011',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which cartoon family lives in the Stone Age town of Bedrock?',
    options: ['The Jetsons', 'The Croods', 'The Flintstones', 'The Simpsons'],
    correct: 2,
    explanation: 'Fred, Wilma and Pebbles Flintstone live in Bedrock, next door to the Rubbles.',
  },
  {
    id: 'screen-012',
    category: 'screen',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In "Doctor Who", what does the TARDIS time machine look like from the outside?',
    options: ['A red telephone box', 'A green garden shed', 'A yellow taxi', 'A blue police box'],
    correct: 3,
    explanation: 'The TARDIS is stuck looking like a 1960s British police box, but it is far bigger on the inside.',
  },

  // ---------------------------------------------------------------- multiple choice — medium
  {
    id: 'screen-013',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Who composed the music for the original "Star Wars" film?',
    options: ['John Williams', 'Hans Zimmer', 'Danny Elfman', 'Howard Shore'],
    correct: 0,
    explanation: 'John Williams scored "Star Wars", as well as "Jaws", "E.T." and "Jurassic Park".',
  },
  {
    id: 'screen-014',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What was Walt Disney’s first full-length animated feature film, released in 1937?',
    options: ['Pinocchio', 'Snow White and the Seven Dwarfs', 'Fantasia', 'Bambi'],
    correct: 1,
    explanation: '"Snow White and the Seven Dwarfs" came first; "Pinocchio" and "Fantasia" followed in 1940.',
  },
  {
    id: 'screen-015',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Who directed the thriller "Psycho" (1960)?',
    options: ['Orson Welles', 'Billy Wilder', 'Alfred Hitchcock', 'Stanley Kubrick'],
    correct: 2,
    explanation: 'Alfred Hitchcock, the "Master of Suspense", directed "Psycho".',
  },
  {
    id: 'screen-016',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Disney celebrates Mickey Mouse’s birthday on the release date of which 1928 cartoon?',
    options: ['The Skeleton Dance', 'Flowers and Trees', 'The Band Concert', 'Steamboat Willie'],
    correct: 3,
    explanation: '"Steamboat Willie" premiered on 18 November 1928, the date Disney treats as Mickey’s birthday.',
  },
  {
    id: 'screen-017',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In which city is the original sitcom "Frasier" (1993–2004) set?',
    options: ['Seattle', 'Boston', 'Chicago', 'Denver'],
    correct: 0,
    explanation: 'Frasier Crane left Boston (and the bar from "Cheers") to host a radio show in Seattle.',
  },
  {
    id: 'screen-018',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Peter Jackson’s "The Lord of the Rings" film trilogy was shot mainly in which country?',
    options: ['Ireland', 'New Zealand', 'Iceland', 'Canada'],
    correct: 1,
    explanation: 'Jackson, a New Zealander, filmed Middle-earth across his home country’s landscapes.',
  },
  {
    id: 'screen-019',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In Disney’s "Frozen", what is the name of the kingdom ruled by Elsa?',
    options: ['Corona', 'Agrabah', 'Arendelle', 'DunBroch'],
    correct: 2,
    explanation: 'Arendelle; Corona is from "Tangled", Agrabah from "Aladdin" and DunBroch from "Brave".',
  },
  {
    id: 'screen-020',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which Japanese studio made "My Neighbor Totoro" and "Spirited Away"?',
    options: ['Toei Animation', 'Madhouse', 'Sunrise', 'Studio Ghibli'],
    correct: 3,
    explanation: 'Studio Ghibli, co-founded by Hayao Miyazaki, made both films.',
  },
  {
    id: 'screen-021',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which British studio brought the clay duo Wallace and Gromit to the screen?',
    options: ['Aardman Animations', 'Laika', 'Cosgrove Hall', 'Rankin/Bass'],
    correct: 0,
    explanation: 'Bristol-based Aardman Animations created Wallace and Gromit with animator Nick Park.',
  },
  {
    id: 'screen-022',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which silent-film star played the Tramp in comedies such as "The Kid" (1921)?',
    options: ['Buster Keaton', 'Charlie Chaplin', 'Harold Lloyd', 'Stan Laurel'],
    correct: 1,
    explanation: 'Charlie Chaplin wrote, directed and starred in "The Kid" as his bowler-hatted Tramp.',
  },
  {
    id: 'screen-023',
    category: 'screen',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'In "Jurassic Park" (1993), where do scientists find the dinosaur DNA?',
    options: ['Frozen mammoth tusks', 'Fossilized dinosaur eggs', 'Mosquitoes trapped in amber', 'Bones from a tar pit'],
    correct: 2,
    explanation: 'The DNA comes from dinosaur blood inside ancient mosquitoes preserved in amber.',
  },

  // ---------------------------------------------------------------- multiple choice — hard
  {
    id: 'screen-024',
    category: 'screen',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which silent war film won the top award, Outstanding Picture, at the very first Academy Awards?',
    options: ['Metropolis', 'The Gold Rush', 'Nosferatu', 'Wings'],
    correct: 3,
    explanation: '"Wings" (1927), about World War I fighter pilots, is recognized as the first Best Picture winner.',
  },
  {
    id: 'screen-025',
    category: 'screen',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Who directed the Japanese classic "Seven Samurai" (1954)?',
    options: ['Akira Kurosawa', 'Yasujiro Ozu', 'Hayao Miyazaki', 'Kenji Mizoguchi'],
    correct: 0,
    explanation: 'Akira Kurosawa directed "Seven Samurai", which later inspired "The Magnificent Seven".',
  },
  {
    id: 'screen-026',
    category: 'screen',
    difficulty: 'hard',
    type: 'mc',
    prompt: '"The Jazz Singer" (1927) is famous as the first feature film to do what?',
    options: ['Be shot entirely in color', 'Include synchronized talking scenes', 'Win the Best Picture Oscar', 'Be shown in 3D'],
    correct: 1,
    explanation: 'Its synchronized singing and spoken dialogue launched the "talkie" era.',
  },
  {
    id: 'screen-027',
    category: 'screen',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which film was the first to win all five major Oscars: Picture, Director, Actor, Actress and Screenplay?',
    options: ['Gone with the Wind', 'Mutiny on the Bounty', 'It Happened One Night', 'The Thin Man'],
    correct: 2,
    explanation: 'Frank Capra’s 1934 comedy "It Happened One Night" was the first film to sweep the "Big Five".',
  },
  {
    id: 'screen-028',
    category: 'screen',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which pioneering filmmaker made "A Trip to the Moon" (1902), with its space capsule lodged in the Moon’s eye?',
    options: ['Louis Lumière', 'Thomas Edison', 'D. W. Griffith', 'Georges Méliès'],
    correct: 3,
    explanation: 'Georges Méliès, a former stage magician, made the French film "A Trip to the Moon".',
  },

  // ---------------------------------------------------------------- true / false
  {
    id: 'screen-029',
    category: 'screen',
    difficulty: 'easy',
    type: 'tf',
    prompt: '"Sesame Street" first aired in 1969.',
    correct: true,
    explanation: '"Sesame Street" premiered on American public television in November 1969.',
  },
  {
    id: 'screen-030',
    category: 'screen',
    difficulty: 'easy',
    type: 'tf',
    prompt: '"The Wizard of Oz" (1939) was filmed entirely in black and white.',
    correct: false,
    explanation: 'The Kansas scenes are sepia-toned, but the Land of Oz bursts into Technicolor.',
  },
  {
    id: 'screen-031',
    category: 'screen',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Steven Spielberg directed "Titanic" (1997).',
    correct: false,
    explanation: 'James Cameron wrote and directed "Titanic".',
  },
  {
    id: 'screen-032',
    category: 'screen',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Simpsons first appeared as short cartoons on "The Tracey Ullman Show".',
    correct: true,
    explanation: 'The family debuted in shorts on the show in 1987 before getting their own series in 1989.',
  },
  {
    id: 'screen-033',
    category: 'screen',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Hayao Miyazaki’s "Spirited Away" won the Academy Award for Best Animated Feature.',
    correct: true,
    explanation: 'It won at the 2003 ceremony, only the second year the Best Animated Feature award was given.',
  },
  {
    id: 'screen-034',
    category: 'screen',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The sitcom "Friends" ran for 12 seasons.',
    correct: false,
    explanation: '"Friends" ran for 10 seasons, from 1994 to 2004.',
  },
  {
    id: 'screen-035',
    category: 'screen',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'The Oscar statuette depicts a knight holding a sword, standing on a reel of film.',
    correct: true,
    explanation: 'The Academy describes Oscar as a knight holding a crusader’s sword atop a five-spoked film reel.',
  },
  {
    id: 'screen-036',
    category: 'screen',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Kermit the Frog made his TV debut on "Sesame Street".',
    correct: false,
    explanation: 'Kermit first appeared in 1955 on Jim Henson’s local show "Sam and Friends", years before "Sesame Street".',
  },

  // ---------------------------------------------------------------- type the answer
  {
    id: 'screen-037',
    category: 'screen',
    difficulty: 'easy',
    type: 'text',
    prompt: 'In Disney’s "The Lion King" (1994), what is the name of Simba’s father?',
    accept: ['Mufasa'],
    explanation: 'Mufasa is the king of the Pride Lands at the start of the film.',
  },
  {
    id: 'screen-038',
    category: 'screen',
    difficulty: 'easy',
    type: 'text',
    prompt: 'Which 2001 DreamWorks film stars a grumpy green ogre and a talking donkey?',
    accept: ['Shrek'],
    explanation: '"Shrek" won the first-ever Academy Award for Best Animated Feature.',
  },
  {
    id: 'screen-039',
    category: 'screen',
    difficulty: 'medium',
    type: 'text',
    prompt: 'In the X-Men films, what nearly indestructible metal coats Wolverine’s skeleton?',
    accept: ['Adamantium'],
    explanation: 'Adamantium is a fictional Marvel metal bonded to Wolverine’s bones and claws.',
  },
  {
    id: 'screen-040',
    category: 'screen',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What is the name of the spaceship’s talking computer in "2001: A Space Odyssey" (1968)?',
    accept: ['HAL 9000', 'HAL'],
    explanation: 'HAL 9000 runs the ship Discovery One in Stanley Kubrick’s film.',
  },
  {
    id: 'screen-041',
    category: 'screen',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What single word does Charles Foster Kane whisper at the start of "Citizen Kane" (1941)?',
    accept: ['Rosebud'],
    explanation: 'A reporter spends the film trying to work out what "Rosebud" meant.',
  },

  // ---------------------------------------------------------------- closest number
  {
    id: 'screen-042',
    category: 'screen',
    difficulty: 'easy',
    type: 'number',
    prompt: 'In "Back to the Future" (1985), how fast must the DeLorean go to travel through time?',
    correct: 88,
    unit: 'mph',
    explanation: 'Once the DeLorean hits 88 miles per hour, the flux capacitor sends it through time.',
  },
  {
    id: 'screen-043',
    category: 'screen',
    difficulty: 'easy',
    type: 'number',
    prompt: 'In what year was the first "Star Wars" film released in cinemas?',
    correct: 1977,
    explanation: '"Star Wars", later subtitled "A New Hope", opened in May 1977.',
  },
  {
    id: 'screen-044',
    category: 'screen',
    difficulty: 'medium',
    type: 'number',
    prompt: 'The title of Disney’s 1961 film "One Hundred and One Dalmatians" counts every dog. How many are puppies?',
    correct: 99,
    unit: 'puppies',
    explanation: 'Pongo and Perdita’s 15 puppies plus 84 rescued puppies make 99; add the two parents for 101.',
  },
  {
    id: 'screen-045',
    category: 'screen',
    difficulty: 'hard',
    type: 'number',
    prompt: 'In what year was the very first Academy Awards ceremony held?',
    correct: 1929,
    explanation: 'The first ceremony was held in May 1929 at the Hollywood Roosevelt Hotel.',
  },

  // ---------------------------------------------------------------- put in order
  {
    id: 'screen-046',
    category: 'screen',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these films in order of release.',
    items: ['Casablanca', 'The Sound of Music', 'E.T. the Extra-Terrestrial', 'Avatar'],
    ends: ['Earliest', 'Latest'],
    explanation: 'Casablanca (1942), The Sound of Music (1965), E.T. (1982), Avatar (2009).',
  },
  {
    id: 'screen-047',
    category: 'screen',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these TV series in the order they first aired.',
    items: ['I Love Lucy', 'Star Trek (original series)', 'Cheers', 'The Simpsons'],
    ends: ['Earliest', 'Latest'],
    explanation: 'I Love Lucy (1951), Star Trek (1966), Cheers (1982), The Simpsons (1989).',
  },
  {
    id: 'screen-048',
    category: 'screen',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Put these Pixar films in order of release.',
    items: ['A Bug’s Life', 'The Incredibles', 'WALL-E', 'Coco'],
    ends: ['Earliest', 'Latest'],
    explanation: 'A Bug’s Life (1998), The Incredibles (2004), WALL-E (2008), Coco (2017).',
  },
];
