/**
 * DAStravaganza Trivia starter pack — tech. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const TECH: StarterQuestion[] = [
  // --- Multiple choice: easy ---
  {
    id: 'tech-001',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In computing, what does “CPU” stand for?',
    options: ['Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Peripheral Unit'],
    correct: 0,
    explanation: 'The CPU carries out a program’s instructions — it’s often called the computer’s brain.',
  },
  {
    id: 'tech-002',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In modern computing, how many bits make up one byte?',
    options: ['4', '8', '16', '32'],
    correct: 1,
    fixedOrder: true,
    explanation: 'A bit is a single 0 or 1, and eight of them make a byte.',
  },
  {
    id: 'tech-003',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Who invented the World Wide Web while working at CERN?',
    options: ['Bill Gates', 'Vint Cerf', 'Tim Berners-Lee', 'Steve Jobs'],
    correct: 2,
    explanation: 'Tim Berners-Lee wrote the original proposal for the Web and built the first web browser and web server.',
  },
  {
    id: 'tech-004',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What does “HTML” stand for?',
    options: [
      'High Transfer Machine Language',
      'Hyperlink Text Management Logic',
      'Home Tool Markup Language',
      'HyperText Markup Language',
    ],
    correct: 3,
    explanation: 'HTML describes the structure of web pages: headings, paragraphs, links and more.',
  },
  {
    id: 'tech-005',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In most Windows programs, what does the shortcut Ctrl+Z do?',
    options: ['Undo', 'Copy', 'Paste', 'Save'],
    correct: 0,
    explanation: 'Ctrl+C copies, Ctrl+V pastes and Ctrl+S saves; on a Mac, Cmd+Z is undo.',
  },
  {
    id: 'tech-006',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which element is the main material used to make most computer chips?',
    options: ['Copper', 'Silicon', 'Carbon', 'Aluminium'],
    correct: 1,
    explanation: 'Silicon is a semiconductor — and the reason California’s tech hub is called Silicon Valley.',
  },
  {
    id: 'tech-007',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What does “GPS” stand for?',
    options: ['Global Positioning System', 'General Path Service', 'Geographic Point Scanner', 'Global Pathfinding Satellite'],
    correct: 0,
    explanation: 'A GPS receiver works out where it is using timing signals from a network of satellites.',
  },
  {
    id: 'tech-008',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which file extension is the default for a modern Microsoft Excel workbook?',
    options: ['.docx', '.pptx', '.xlsx', '.txt'],
    correct: 2,
    explanation: 'The “x” in .xlsx, .docx and .pptx arrived with the XML-based file formats of Office 2007.',
  },
  {
    id: 'tech-009',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which language is used to control the colours, fonts and layout of web pages?',
    options: ['SQL', 'CSS', 'C++', 'Python'],
    correct: 1,
    explanation: 'CSS stands for Cascading Style Sheets.',
  },
  {
    id: 'tech-010',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'An MP3 file usually contains what kind of media?',
    options: ['Video', 'Spreadsheets', 'Audio', '3D models'],
    correct: 2,
    explanation: 'MP3 shrinks audio files by discarding sounds that most listeners won’t notice.',
  },
  {
    id: 'tech-011',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What does the “e” in “email” stand for?',
    options: ['Express', 'Electronic', 'Easy', 'External'],
    correct: 1,
    explanation: 'Email is short for “electronic mail”.',
  },
  {
    id: 'tech-012',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which of these is an input device?',
    options: ['Monitor', 'Speaker', 'Printer', 'Keyboard'],
    correct: 3,
    explanation: 'Input devices send information into a computer; monitors, speakers and printers send it out.',
  },
  {
    id: 'tech-013',
    category: 'tech',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which company launched the iPod music player in 2001?',
    options: ['Sony', 'Apple', 'Microsoft', 'Samsung'],
    correct: 1,
    explanation: 'Apple promoted the first iPod as putting “1,000 songs in your pocket”.',
  },

  // --- Multiple choice: medium ---
  {
    id: 'tech-014',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which programming language is named after a British comedy group?',
    options: ['Java', 'Ruby', 'Perl', 'Python'],
    correct: 3,
    explanation: 'Creator Guido van Rossum named it after “Monty Python’s Flying Circus”, not the snake.',
  },
  {
    id: 'tech-015',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What does “USB” stand for?',
    options: ['Unified System Board', 'Universal Serial Bus', 'Universal Signal Bridge', 'User Storage Block'],
    correct: 1,
    explanation: 'USB arrived in the mid-1990s to replace a jumble of different computer ports.',
  },
  {
    id: 'tech-016',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What does the “S” in “HTTPS” stand for?',
    options: ['Server', 'Standard', 'Secure', 'Session'],
    correct: 2,
    explanation: 'HTTPS encrypts the connection between your browser and the website.',
  },
  {
    id: 'tech-017',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What was the name of the first artificial satellite, launched in 1957?',
    options: ['Explorer 1', 'Sputnik 1', 'Vostok 1', 'Telstar 1'],
    correct: 1,
    explanation: 'Sputnik 1 was a small metal sphere that broadcast simple radio beeps as it circled Earth.',
  },
  {
    id: 'tech-018',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which company introduced the Walkman portable cassette player in 1979?',
    options: ['Panasonic', 'Philips', 'Toshiba', 'Sony'],
    correct: 3,
    explanation: 'The Walkman turned personal, on-the-go music listening into a worldwide habit.',
  },
  {
    id: 'tech-019',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which inventor was granted the US patent for the telephone?',
    options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Samuel Morse'],
    correct: 1,
    explanation: 'Bell’s patent was granted just days before his first successful call to his assistant, Thomas Watson.',
  },
  {
    id: 'tech-020',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which NASA rover landed on Mars in August 2012?',
    options: ['Spirit', 'Curiosity', 'Perseverance', 'Sojourner'],
    correct: 1,
    explanation: 'Curiosity was lowered onto the surface by a rocket-powered “sky crane”.',
  },
  {
    id: 'tech-021',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The hexadecimal number system is based on which number?',
    options: ['2', '8', '10', '16'],
    correct: 3,
    fixedOrder: true,
    explanation: 'Hexadecimal uses the digits 0–9 plus the letters A–F.',
  },
  {
    id: 'tech-022',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which mathematician proposed a famous test of machine intelligence that is now named after him?',
    options: ['John von Neumann', 'Alan Turing', 'Claude Shannon', 'Charles Babbage'],
    correct: 1,
    explanation: 'Turing described his “imitation game” in a 1950 paper.',
  },
  {
    id: 'tech-023',
    category: 'tech',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The unit of power, the watt, honours an inventor famous for improving which machine?',
    options: ['Telegraph', 'Light bulb', 'Steam engine', 'Printing press'],
    correct: 2,
    explanation: 'In the 18th century, James Watt’s separate condenser made steam engines far more efficient.',
  },

  // --- Multiple choice: hard ---
  {
    id: 'tech-024',
    category: 'tech',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'What was the name of the Apollo 11 lunar module?',
    options: ['Columbia', 'Eagle', 'Falcon', 'Intrepid'],
    correct: 1,
    explanation: '“The Eagle has landed.” The command module that stayed in lunar orbit was called Columbia.',
  },
  {
    id: 'tech-025',
    category: 'tech',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which spacecraft became the first to cross into interstellar space, in 2012?',
    options: ['Pioneer 10', 'Voyager 2', 'Voyager 1', 'New Horizons'],
    correct: 2,
    explanation: 'Launched in 1977, Voyager 1 crossed the heliopause — the edge of the Sun’s bubble of solar wind.',
  },
  {
    id: 'tech-026',
    category: 'tech',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Which engineer sent the first email between networked computers in 1971 and picked the @ sign for addresses?',
    options: ['Vint Cerf', 'Ray Tomlinson', 'Tim Berners-Lee', 'Steve Wozniak'],
    correct: 1,
    explanation: 'Ray Tomlinson used @ to separate the user’s name from the name of their computer.',
  },
  {
    id: 'tech-027',
    category: 'tech',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'Before it was called Google, the search engine project was known by what name?',
    options: ['BackRub', 'PageRank', 'WebCrawler', 'Archie'],
    correct: 0,
    explanation: 'Larry Page and Sergey Brin’s project analysed the “back links” between web pages, hence BackRub.',
  },
  {
    id: 'tech-028',
    category: 'tech',
    difficulty: 'hard',
    type: 'mc',
    prompt:
      'Which 19th-century mathematician published notes on Charles Babbage’s Analytical Engine that are often called the first computer program?',
    options: ['Mary Somerville', 'Grace Hopper', 'Ada Lovelace', 'Emmy Noether'],
    correct: 2,
    explanation: 'Ada Lovelace’s 1843 notes included a method for the machine to calculate Bernoulli numbers.',
  },

  // --- True or false ---
  {
    id: 'tech-029',
    category: 'tech',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Morse code represents letters and numbers with combinations of dots and dashes.',
    correct: true,
    explanation: 'It was created for the electric telegraph; the distress signal SOS is dot-dot-dot, dash-dash-dash, dot-dot-dot.',
  },
  {
    id: 'tech-030',
    category: 'tech',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Binary code uses the digits 0, 1 and 2.',
    correct: false,
    explanation: 'Binary is base 2, so it only uses the digits 0 and 1.',
  },
  {
    id: 'tech-031',
    category: 'tech',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Aircraft flight recorders, nicknamed “black boxes”, are usually painted black.',
    correct: false,
    explanation: 'They are painted bright orange so search teams can spot them among wreckage.',
  },
  {
    id: 'tech-032',
    category: 'tech',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The word “emoji” comes from Japanese.',
    correct: true,
    explanation: 'It combines the Japanese for “picture” (e) and “character” (moji); the likeness to “emotion” is a coincidence.',
  },
  {
    id: 'tech-033',
    category: 'tech',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'Bluetooth technology is named after a medieval Scandinavian king.',
    correct: true,
    explanation: 'The name honours Harald “Bluetooth” Gormsson, a 10th-century king of Denmark.',
  },
  {
    id: 'tech-034',
    category: 'tech',
    difficulty: 'medium',
    type: 'tf',
    prompt: '“The Internet” and “the World Wide Web” are two names for exactly the same thing.',
    correct: false,
    explanation: 'The Internet is the global network; the Web is one service that runs on it, alongside email and more.',
  },
  {
    id: 'tech-035',
    category: 'tech',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'A computer’s RAM keeps its contents after the power is switched off.',
    correct: false,
    explanation: 'RAM is volatile memory; files are saved to storage such as an SSD or hard drive so they survive a shutdown.',
  },
  {
    id: 'tech-036',
    category: 'tech',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'The first prototype of the computer mouse had a wooden shell.',
    correct: true,
    explanation: 'Douglas Engelbart’s team built it in the 1960s, and he showed the mouse to the public in 1968.',
  },

  // --- Type the answer ---
  {
    id: 'tech-037',
    category: 'tech',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What are the tiny dots of colour that make up a digital image or screen called?',
    accept: ['Pixels', 'Pixel'],
    explanation: 'The word is short for “picture element”.',
  },
  {
    id: 'tech-038',
    category: 'tech',
    difficulty: 'easy',
    type: 'text',
    prompt: 'Which brothers flew their powered “Flyer” aircraft at Kitty Hawk, North Carolina, in 1903?',
    accept: [
      'Wright brothers',
      'Wright',
      'Wrights',
      'Orville and Wilbur Wright',
      'Wilbur and Orville Wright',
      'Orville and Wilbur',
      'Wilbur and Orville',
    ],
    explanation: 'Orville Wright piloted the first flight on 17 December 1903; it lasted about 12 seconds.',
  },
  {
    id: 'tech-039',
    category: 'tech',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What name is given to scam messages that pretend to come from a trusted source to trick you into revealing passwords?',
    accept: ['Phishing', 'Phishing scam', 'Phishing attack', 'Phishing email'],
    explanation: 'The spelling plays on “fishing” — scammers cast out bait and hope someone bites.',
  },
  {
    id: 'tech-040',
    category: 'tech',
    difficulty: 'medium',
    type: 'text',
    prompt: 'In programming, what is it called when a function calls itself?',
    accept: ['Recursion', 'Recursive call', 'Recursive', 'Recursive function'],
    explanation: 'A recursive function needs a base case so that it eventually stops calling itself.',
  },
  {
    id: 'tech-041',
    category: 'tech',
    difficulty: 'hard',
    type: 'text',
    prompt: 'Who co-founded Microsoft with Bill Gates in 1975?',
    accept: ['Paul Allen', 'Allen'],
    explanation: 'School friends Gates and Allen started the company in Albuquerque, New Mexico.',
  },

  // --- Closest number ---
  {
    id: 'tech-042',
    category: 'tech',
    difficulty: 'medium',
    type: 'number',
    prompt: 'In what year was the first iPhone released?',
    correct: 2007,
    explanation: 'Steve Jobs unveiled it in January 2007, and it went on sale that June.',
  },
  {
    id: 'tech-043',
    category: 'tech',
    difficulty: 'medium',
    type: 'number',
    prompt: 'In what year was the first SMS text message sent?',
    correct: 1992,
    explanation: 'In December 1992, engineer Neil Papworth sent “Merry Christmas” from a computer to a Vodafone mobile phone in the UK.',
  },
  {
    id: 'tech-044',
    category: 'tech',
    difficulty: 'hard',
    type: 'number',
    prompt: 'How many bits long is an IPv4 address?',
    correct: 32,
    unit: 'bits',
    explanation: 'That allows about 4.3 billion addresses, which is why the much larger IPv6 was created.',
  },
  {
    id: 'tech-045',
    category: 'tech',
    difficulty: 'hard',
    type: 'number',
    prompt: 'In what year was the Hubble Space Telescope launched?',
    correct: 1990,
    explanation: 'It was carried into orbit by the Space Shuttle Discovery in April 1990.',
  },

  // --- Put in order ---
  {
    id: 'tech-046',
    category: 'tech',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Order these units of data from smallest to largest.',
    items: ['Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte'],
    ends: ['Smallest', 'Largest'],
    explanation: 'Each step up is roughly a thousand times bigger than the one before.',
  },
  {
    id: 'tech-047',
    category: 'tech',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Order these inventions from earliest to latest.',
    items: ['Mechanical calculator', 'Steam locomotive', 'Television', 'Smartphone'],
    ends: ['Earliest', 'Latest'],
    explanation:
      'Blaise Pascal built mechanical calculators in the 1640s, Trevithick’s steam locomotive first hauled a train in 1804, TV was demonstrated in the 1920s and the first smartphones came in the 1990s.',
  },
  {
    id: 'tech-048',
    category: 'tech',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Order these computing milestones from earliest to latest.',
    items: ['ENIAC computer', 'Apple Macintosh', 'World Wide Web', 'Wikipedia'],
    ends: ['Earliest', 'Latest'],
    explanation: 'ENIAC was unveiled in 1946, the Macintosh launched in 1984, the Web was proposed in 1989 and Wikipedia began in 2001.',
  },
];
