/**
 * DAStravaganza Trivia starter pack — weird. Original questions written for DASCADE.
 */
import type { StarterQuestion } from './types.ts';

export const WEIRD: StarterQuestion[] = [
  // ---------------------------------------------------------------- multiple choice — easy
  {
    id: 'weird-001',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which bird can hover in midair and even fly backwards?',
    options: ['Hummingbird', 'Pelican', 'Ostrich', 'Swallow'],
    correct: 0,
    explanation: 'Hummingbirds beat their wings in a figure-eight pattern, which lets them hover and fly backwards.',
  },
  {
    id: 'weird-002',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What color is an octopus’s blood?',
    options: ['Green', 'Blue', 'Orange', 'Yellow'],
    correct: 1,
    explanation: 'Octopus blood carries oxygen with copper-based hemocyanin instead of iron-based hemoglobin, which gives it a blue color.',
  },
  {
    id: 'weird-003',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Why is the Eiffel Tower a little taller in summer than in winter?',
    options: ['It is jacked up for tourist season', 'Its antenna is extended', 'Its iron expands in the heat', 'Summer winds stretch it'],
    correct: 2,
    explanation: 'Heat makes the iron expand, so the tower grows by several centimeters on hot days.',
  },
  {
    id: 'weird-004',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'In seahorses, which parent carries the babies and gives birth?',
    options: ['The mother', 'Both, taking turns', 'Neither; the eggs float free', 'The father'],
    correct: 3,
    explanation: 'The female lays her eggs in the male’s pouch, and he carries them until they are born.',
  },
  {
    id: 'weird-005',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'How do dolphins sleep without forgetting to come up for air?',
    options: [
      'Half of the brain sleeps at a time',
      'They sleep on sandy beaches',
      'They hold one breath all night',
      'They never sleep at all',
    ],
    correct: 0,
    explanation: 'Dolphins rest one brain hemisphere at a time, staying alert enough to surface and breathe.',
  },
  {
    id: 'weird-006',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which of these was once an official Olympic event?',
    options: ['Dodgeball', 'Tug of war', 'Hide-and-seek', 'Musical chairs'],
    correct: 1,
    explanation: 'Tug of war was part of the Summer Olympics from 1900 to 1920.',
  },
  {
    id: 'weird-007',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What color is a polar bear’s skin, underneath all that fur?',
    options: ['White', 'Pink', 'Black', 'Yellow'],
    correct: 2,
    explanation: 'Polar bears have black skin; their fur hairs are translucent and only look white.',
  },
  {
    id: 'weird-008',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which of these animals is unable to jump?',
    options: ['Kangaroo', 'Goat', 'Horse', 'Elephant'],
    correct: 3,
    explanation:
      'An elephant’s pillar-like legs lack the springy ankles jumping needs; even at top speed, at least one foot stays on the ground.',
  },
  {
    id: 'weird-009',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'What unusual thing does the platypus do, for a mammal?',
    options: ['Lays eggs', 'Changes color', 'Sleeps upside down', 'Sheds its skin'],
    correct: 0,
    explanation: 'The platypus is a monotreme: an egg-laying mammal, like the echidna.',
  },
  {
    id: 'weird-010',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Why are flamingos pink?',
    options: ['They are born pink', 'Pigments in the food they eat', 'They get sunburned', 'They roll in pink mud'],
    correct: 1,
    explanation: 'Carotenoid pigments in the algae and tiny shrimp they eat tint their feathers; chicks hatch gray.',
  },
  {
    id: 'weird-011',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Before it became a children’s toy, Play-Doh was sold as what?',
    options: ['Window putty', 'Denture adhesive', 'Wallpaper cleaner', 'Bread dough'],
    correct: 2,
    explanation: 'It began as a putty for wiping soot off wallpaper and was relaunched as a toy in the 1950s.',
  },
  {
    id: 'weird-012',
    category: 'weird',
    difficulty: 'easy',
    type: 'mc',
    prompt: 'Which animal can regrow entire lost legs, and even parts of its heart and brain?',
    options: ['Iguana', 'Tree frog', 'Chameleon', 'Axolotl'],
    correct: 3,
    explanation: 'Axolotls, salamanders from Mexico, can regenerate limbs, spinal cord and parts of vital organs.',
  },

  // ---------------------------------------------------------------- multiple choice — medium
  {
    id: 'weird-013',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What is a group of flamingos called?',
    options: ['A flamboyance', 'A parliament', 'A pride', 'A gaggle'],
    correct: 0,
    explanation: 'A flamboyance of flamingos; a parliament is owls, a pride is lions and a gaggle is geese.',
  },
  {
    id: 'weird-014',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Botanically speaking, which of these is a true berry?',
    options: ['Strawberry', 'Banana', 'Raspberry', 'Blackberry'],
    correct: 1,
    explanation: 'Bananas grow from a single flower ovary, making them berries; strawberries and raspberries are not.',
  },
  {
    id: 'weird-015',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Nintendo was founded way back in 1889. What did it originally make?',
    options: ['Umbrellas', 'Kites', 'Playing cards', 'Wooden toys'],
    correct: 2,
    explanation: 'Nintendo started in Kyoto making hanafuda, traditional Japanese playing cards.',
  },
  {
    id: 'weird-016',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'The poet Lord Byron kept which pet at Cambridge University, reportedly because dogs were banned?',
    options: ['A wolf', 'A monkey', 'A crocodile', 'A bear'],
    correct: 3,
    explanation: 'Byron kept a tame bear while he was a student at Trinity College, Cambridge, in the early 1800s.',
  },
  {
    id: 'weird-017',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which animal has fingerprints so similar to a human’s that they are hard to tell apart?',
    options: ['Koala', 'Kangaroo', 'Sloth', 'Raccoon'],
    correct: 0,
    explanation: 'Koala fingerprints evolved separately from ours but have very similar loops and whorls.',
  },
  {
    id: 'weird-018',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which animal can freeze nearly solid over winter, heart stopped, then thaw out alive in spring?',
    options: ['Bullfrog', 'Wood frog', 'Poison dart frog', 'Green iguana'],
    correct: 1,
    explanation: 'Wood frogs flood their cells with sugar as antifreeze while much of the water in their bodies turns to ice.',
  },
  {
    id: 'weird-019',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Hippos ooze a reddish, oily fluid from their skin. What does it do?',
    options: ['Attracts mates', 'Helps them float', 'Works like sunscreen', 'Scares off crocodiles'],
    correct: 2,
    explanation: 'Nicknamed "blood sweat", it is neither blood nor sweat; it absorbs UV light and fights germs.',
  },
  {
    id: 'weird-020',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Scientists have recorded rats making ultrasonic "laughing" chirps when they are what?',
    options: ['Sleeping', 'Hungry', 'Lost', 'Tickled'],
    correct: 3,
    explanation: 'Tickled rats chirp happily and will even chase the hand that tickles them.',
  },
  {
    id: 'weird-021',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which basic taste are cats unable to detect?',
    options: ['Sweet', 'Sour', 'Bitter', 'Umami'],
    correct: 0,
    explanation: 'Cats carry a broken version of the gene needed for the sweet-taste receptor.',
  },
  {
    id: 'weird-022',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'Which animal has eyes that are each bigger than its brain?',
    options: ['Elephant', 'Ostrich', 'Dolphin', 'Chimpanzee'],
    correct: 1,
    explanation: 'An ostrich eye is about 5 cm across, the largest of any land animal, and bigger than its brain.',
  },
  {
    id: 'weird-023',
    category: 'weird',
    difficulty: 'medium',
    type: 'mc',
    prompt: 'What is an "octothorpe"?',
    options: ['The @ symbol', 'The & symbol', 'The # symbol', 'The * symbol'],
    correct: 2,
    explanation:
      'Octothorpe is another name for the # sign (hash, pound or number sign); Bell Labs telephone engineers popularized it in the 1960s.',
  },

  // ---------------------------------------------------------------- multiple choice — hard
  {
    id: 'weird-024',
    category: 'weird',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The first product scanned by a UPC barcode at a store checkout, in 1974, was a pack of what?',
    options: ['Breakfast cereal', 'Batteries', 'Cola', 'Chewing gum'],
    correct: 3,
    explanation: 'A 10-pack of Wrigley’s Juicy Fruit gum was scanned at a supermarket in Troy, Ohio, in June 1974.',
  },
  {
    id: 'weird-025',
    category: 'weird',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'In 1518, the city of Strasbourg was gripped by a strange outbreak of what?',
    options: ['Nonstop dancing', 'Uncontrollable laughing', 'Mass sleepwalking', 'Endless hiccups'],
    correct: 0,
    explanation: 'In the "dancing plague", dozens and perhaps hundreds of people danced for days on end.',
  },
  {
    id: 'weird-026',
    category: 'weird',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The shortest war on record, in 1896, lasted under an hour. Britain fought it against which state?',
    options: ['Madagascar', 'Zanzibar', 'Tonga', 'Fiji'],
    correct: 1,
    explanation: 'The Anglo-Zanzibar War is usually said to have lasted somewhere between 38 and 45 minutes.',
  },
  {
    id: 'weird-027',
    category: 'weird',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'The nonexistent word "dord" appeared in a 1934 dictionary by mistake. What was it said to mean?',
    options: ['A small songbird', 'Boredom', 'Density', 'A wooden door'],
    correct: 2,
    explanation: 'A note reading "D or d" (abbreviations for density) was mistaken for a word and printed as one.',
  },
  {
    id: 'weird-028',
    category: 'weird',
    difficulty: 'hard',
    type: 'mc',
    prompt: 'In 1932, Australian soldiers armed with machine guns were sent to Western Australia to fight which crop-raiding animals?',
    options: ['Rabbits', 'Kangaroos', 'Camels', 'Emus'],
    correct: 3,
    explanation:
      'In the so-called "Great Emu War", the fast, scattering birds proved so hard to hit that the operation was called off within weeks.',
  },

  // ---------------------------------------------------------------- true / false
  {
    id: 'weird-029',
    category: 'weird',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Viking warriors commonly wore horned helmets into battle.',
    correct: false,
    explanation: 'There is no evidence for it; horned Viking helmets were popularized by 19th-century costume designers.',
  },
  {
    id: 'weird-030',
    category: 'weird',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Goldfish can only remember things for about three seconds.',
    correct: false,
    explanation: 'Experiments show goldfish can learn tricks and remember them for months.',
  },
  {
    id: 'weird-031',
    category: 'weird',
    difficulty: 'easy',
    type: 'tf',
    prompt: 'Algae can grow in a sloth’s fur.',
    correct: true,
    explanation: 'Sloths move so little that green algae thrive in their shaggy fur, tinting them green.',
  },
  {
    id: 'weird-032',
    category: 'weird',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The planet Saturn is less dense than water.',
    correct: true,
    explanation: 'Saturn’s average density is about 0.7 grams per cubic centimeter, below water’s 1.0.',
  },
  {
    id: 'weird-033',
    category: 'weird',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The Great Wall of China can be seen with the naked eye from the Moon.',
    correct: false,
    explanation: 'From the Moon, no individual human-made structure can be seen without magnification.',
  },
  {
    id: 'weird-034',
    category: 'weird',
    difficulty: 'medium',
    type: 'tf',
    prompt: 'The University of Oxford is older than the Aztec Empire.',
    correct: true,
    explanation: 'Teaching at Oxford was underway by 1096 — centuries before the Aztec Triple Alliance formed in 1428.',
  },
  {
    id: 'weird-035',
    category: 'weird',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'Pluto has not completed a single orbit of the Sun since it was discovered.',
    correct: true,
    explanation: 'Pluto was found in 1930 and takes about 248 years per orbit, so its first lap since then ends in the 2170s.',
  },
  {
    id: 'weird-036',
    category: 'weird',
    difficulty: 'hard',
    type: 'tf',
    prompt: 'A duck’s quack does not echo.',
    correct: false,
    explanation: 'It does echo; acoustics researchers tested the myth in 2003 and found the echo is just hard to notice.',
  },

  // ---------------------------------------------------------------- type the answer
  {
    id: 'weird-037',
    category: 'weird',
    difficulty: 'easy',
    type: 'text',
    prompt: 'What mythical creature is the national animal of Scotland?',
    accept: ['Unicorn', 'Unicorns'],
    explanation: 'The unicorn has been a symbol of Scotland for centuries and appears on its royal coat of arms.',
  },
  {
    id: 'weird-038',
    category: 'weird',
    difficulty: 'easy',
    type: 'text',
    prompt: 'Which Australian animal produces cube-shaped droppings?',
    accept: ['Wombat', 'Wombats'],
    explanation: 'Wombat intestines shape their poop into cubes, which may help the droppings stay put when wombats mark territory.',
  },
  {
    id: 'weird-039',
    category: 'weird',
    difficulty: 'medium',
    type: 'text',
    prompt: 'What is the name of the vertical groove between the bottom of your nose and your upper lip?',
    accept: ['Philtrum', 'Infranasal depression'],
    explanation: 'Almost everyone has a philtrum; it forms where separate parts of the face join together before birth.',
  },
  {
    id: 'weird-040',
    category: 'weird',
    difficulty: 'medium',
    type: 'text',
    prompt: 'Which microscopic animal, nicknamed the "water bear", has survived exposure to outer space?',
    accept: ['Tardigrade', 'Tardigrades', 'Moss piglet'],
    explanation: 'In 2007, tardigrades flown on a satellite survived the vacuum of space, and some survived its radiation too.',
  },
  {
    id: 'weird-041',
    category: 'weird',
    difficulty: 'hard',
    type: 'text',
    prompt: 'What word names the earthy smell that rises when rain falls on dry ground?',
    accept: ['Petrichor'],
    explanation: 'Two Australian scientists coined "petrichor" in 1964, from the Greek for "stone" and the fluid in the gods’ veins.',
  },

  // ---------------------------------------------------------------- closest number
  {
    id: 'weird-042',
    category: 'weird',
    difficulty: 'easy',
    type: 'number',
    prompt: 'How many vertebrae are in a giraffe’s long neck?',
    correct: 7,
    unit: 'vertebrae',
    explanation: 'Giraffes have seven neck vertebrae, the same number as humans; each one is just much longer.',
  },
  {
    id: 'weird-043',
    category: 'weird',
    difficulty: 'medium',
    type: 'number',
    prompt: 'How many eyes does a honeybee have?',
    correct: 5,
    unit: 'eyes',
    explanation: 'Two large compound eyes, plus three small simple eyes called ocelli on top of the head.',
  },
  {
    id: 'weird-044',
    category: 'weird',
    difficulty: 'medium',
    type: 'number',
    prompt: 'Up to how many degrees can an owl rotate its head?',
    correct: 270,
    unit: 'degrees',
    explanation:
      'Owls have 14 neck vertebrae (twice as many as humans) and specially adapted blood vessels, letting them swivel their heads about 270 degrees.',
  },
  {
    id: 'weird-045',
    category: 'weird',
    difficulty: 'hard',
    type: 'number',
    prompt: 'How many letters are in "pneumonoultramicroscopicsilicovolcanoconiosis", a famously long word for a lung disease?',
    correct: 45,
    unit: 'letters',
    explanation: 'Coined in the 1930s as a deliberately long word, it is one of the longest words in major English dictionaries.',
  },

  // ---------------------------------------------------------------- put in order
  {
    id: 'weird-046',
    category: 'weird',
    difficulty: 'easy',
    type: 'order',
    prompt: 'Put these animals in order by how many legs they have.',
    items: ['Snake', 'Ostrich', 'Ant', 'Lobster'],
    ends: ['Fewest', 'Most'],
    explanation: 'Snake 0, ostrich 2, ant 6, lobster 10 (lobsters are decapods, meaning "ten-footed").',
  },
  {
    id: 'weird-047',
    category: 'weird',
    difficulty: 'medium',
    type: 'order',
    prompt: 'Put these inventions in order, from first to most recent.',
    items: ['First fax machine patent', 'Telephone patent', 'First sliced bread sold', 'Bubble Wrap invented'],
    ends: ['Earliest', 'Latest'],
    explanation: 'Fax (1843), telephone (1876), sliced bread (1928), Bubble Wrap (1957). Yes, the fax came first!',
  },
  {
    id: 'weird-048',
    category: 'weird',
    difficulty: 'hard',
    type: 'order',
    prompt: 'Put these moments in history in order.',
    items: ['Great Pyramid of Giza built', 'Last woolly mammoths die out', 'Death of Cleopatra', 'First Moon landing'],
    ends: ['Earliest', 'Latest'],
    explanation: 'Pyramid (c. 2560 BC), last mammoths on Wrangel Island (about 4,000 years ago), Cleopatra (30 BC), Moon (1969).',
  },
];
