/**
 * DASterpiece built-in prompt pack — original, office-safe writing prompts, grouped by round theme.
 *
 * Style guide for additions: no real people, brands or copyrighted characters; nothing about
 * religion, politics, bodies, drinking or anything you'd hesitate to read aloud at a team lunch.
 * `{player}` is replaced by a random player's name when the prompt is dealt.
 */
import type { MpBuiltInType } from '@dascade/shared/games/masterpiece';

export const PROMPT_PACK: Record<MpBuiltInType, readonly string[]> = {
  caption: [
    'A pigeon in a tiny hard hat inspects a construction site with a clipboard.',
    'A cat sits in the CEO’s chair during the quarterly earnings call.',
    'A golden retriever presents a pie chart made of actual pie.',
    'Three raccoons in one trench coat try to open a bank account.',
    'A snowman at the beach applies sunscreen with great urgency.',
    'The office printer is surrounded by candles, flowers and a framed photo.',
    'A goldfish wears a scuba mask inside its own bowl.',
    'A llama photobombs a very serious team photo.',
    'Two astronauts on the Moon argue over a parking space.',
    'A museum dinosaur skeleton wears a “Hello, my name is” sticker.',
    'A toddler in a tiny business suit firmly shakes hands with a bank manager.',
    'A penguin at the airport holds a one-way ticket to the tropics.',
    'An over-watered houseplant stands in a puddle, looking deeply betrayed.',
    'A knight in full armour waits patiently in a drive-through line.',
    'A squirrel holds one single, perfect nacho up to the sky.',
    'An owl gives a slideshow presentation to a room of sleeping owls.',
    'A crowd gathers around a vending machine where one snack is stuck on the edge.',
    'A robot vacuum wearing a tiny cape is stuck under the couch.',
    'A grandma lands a perfect kickflip in front of stunned teenagers.',
    'A goat stands on the roof of a parked car, looking extremely pleased with itself.',
    'A crab at a job interview holds its résumé in one claw.',
    'A group of pigeons huddle around a single french fry like it’s a campfire.',
    'A hamster runs on its wheel wearing a sweatband and a fitness tracker.',
    'A shark in a tiny party hat floats in the middle of a pool party.',
    'A barista proudly hands over a latte with the customer’s face drawn in the foam. The customer is not smiling.',
    'A mime is trapped in a very real glass box and looks genuinely concerned.',
    'A cow stands alone in the middle of an empty, fancy ballroom.',
    'A dog in sunglasses sits behind the wheel of a parked convertible.',
    'A pirate ship is parked neatly between two lines in a supermarket car park.',
    'A bear in the woods reads the “Do not feed the bears” sign very carefully.',
    'A hot-air balloon shaped like a giant potato drifts over the city.',
    'A seagull steals the microphone from a reporter on live TV.',
    'A tortoise crosses the marathon finish line three days late to a standing ovation.',
    'An alien stands next to a crop circle, leaving a one-star review on its phone.',
    'A single sock sits on top of the dryer, staring at the empty space beside it.',
    'A marble statue of {player} stands in a museum, surrounded by tourists taking selfies.',
    '{player} rides a unicorn into the Monday morning meeting.',
    'A chef presents a single burnt piece of toast on a silver platter.',
    'A giraffe tries very hard to fit into an office elevator.',
    'A lighthouse keeper stands at the top of the lighthouse holding a tiny pocket torch.',
    'A frog sits on a lily pad wearing a tiny crown and a very serious expression.',
    'A family of ducks waits politely at a pedestrian crossing.',
  ],
  finish: [
    'The worst thing to hear from your pilot: “…”',
    'My smart fridge just sent me a notification that says “…”',
    'The real reason the dinosaurs went extinct was…',
    'You know it’s going to be a long meeting when the first slide says “…”',
    'The secret ingredient in Grandma’s famous cookies is…',
    'The new office policy nobody asked for: …',
    'The least reassuring thing a dentist can say: “…”',
    'If my cat could talk, the first thing it would say is “…”',
    'A fortune cookie you would not want to open: “…”',
    'The most suspicious item on a restaurant menu: …',
    'The last thing you want to hear from tech support: “…”',
    'The worst thing to find in your sandwich: …',
    'A sure sign you’ve been working from home too long: …',
    'Scientists finally discovered the Loch Ness Monster is actually…',
    'My autobiography will be titled “…”',
    'Nobody warned me that being an adult would involve so much…',
    'The worst thing to shout in a library: “…”',
    'The robot uprising began when someone asked the smart speaker to…',
    'The fine print on the prize draw ticket says…',
    'My GPS said “Turn left,” and then it said “…”',
    'The surprise twist at the end of the office party was…',
    'My plants started a group chat. The latest message says “…”',
    'The one rule at the haunted house: …',
    'It turns out the Moon is actually made of…',
    'The one thing you should never bring to a job interview: …',
    'The fire alarm went off and {player} saved only one thing: …',
    '{player}’s secret talent is…',
    'The Wi-Fi password at the haunted castle is “…”',
    'Tomorrow’s weather forecast: 80% chance of…',
    'You know you’re at a bad hotel when the welcome gift is…',
    'The worst superhero power: the ability to…',
    'My dog’s diary entry for today reads: “…”',
    'The newest Olympic sport is competitive…',
    'The voicemail from your future self says: “…”',
    'The birthday card from my toaster says “…”',
    'The strangest thing in the office lost-and-found: …',
    'The last words of a mime before retiring: “…”',
    'The only instruction in the flat-pack time machine manual: “…”',
    'The worst icebreaker for a first meeting with a new client: “…”',
    'The out-of-office reply every penguin uses: “…”',
    'The worst thing to name your Wi-Fi network: “…”',
    'The sequel nobody wanted: “…, Part 2”',
  ],
  advice: [
    'Terrible advice for your first day at a new job.',
    'Terrible advice for surviving a bear encounter.',
    'Terrible advice for a first date.',
    'Terrible advice for assembling flat-pack furniture.',
    'Terrible advice for a job interview.',
    'Terrible advice for someone learning to drive.',
    'Terrible advice for keeping houseplants alive.',
    'Terrible advice for public speaking.',
    'Terrible advice for saving money.',
    'Terrible advice for getting a good night’s sleep.',
    'Terrible advice for winning an argument.',
    'Terrible advice for your first camping trip.',
    'Terrible advice for writing a professional email.',
    'Terrible advice for hosting a dinner party.',
    'Terrible advice for meeting your partner’s parents.',
    'Terrible advice for running a marathon.',
    'Terrible advice for a brand-new astronaut.',
    'Terrible advice for a pirate captain.',
    'Terrible advice for a wizard’s apprentice.',
    'Terrible advice for a lifeguard.',
    'Terrible advice for asking your boss for a raise.',
    'Terrible advice for surviving a zombie apocalypse.',
    'Terrible advice for a knight about to fight a dragon.',
    'Terrible advice for training a puppy.',
    'Terrible advice for starting a podcast.',
    'Terrible advice for cooking a holiday dinner.',
    'Terrible advice for a substitute teacher.',
    'Terrible advice for someone about to go skydiving.',
    'Terrible advice for a museum security guard.',
    'Terrible advice for your first video call with the whole company.',
    'Terrible advice for getting through airport security.',
    'Terrible advice for moving to a new city.',
    'Terrible advice for an explorer lost in the jungle.',
    'Terrible advice {player} would give a new intern.',
    'Terrible advice for writing a wedding speech.',
    'Terrible advice for a time traveller visiting the year 1850.',
    'Terrible advice for someone trying to go viral.',
    'Terrible advice for a ghost haunting its first house.',
    'Terrible advice for cleaning the office kitchen.',
    'Terrible advice for a new superhero choosing a costume.',
    'Terrible advice for winning a pie-eating contest.',
    'Terrible advice {player} would give to a robot learning to be human.',
  ],
  definition: [
    'Flumpernickel (noun)',
    'Snorklewhump (verb)',
    'Wobbletonk (noun)',
    'Crumplesnoot (noun)',
    'Blorptastic (adjective)',
    'Zibberflax (noun)',
    'Moopgrindle (verb)',
    'Quonkle (noun)',
    'Frizzlewig (noun)',
    'Plimbersome (adjective)',
    'Snarflebop (noun)',
    'Grumbleflank (noun)',
    'Twizzlecrank (noun)',
    'Doodlebramp (noun)',
    'Fwoompish (adjective)',
    'Scrumblewort (noun)',
    'Hobnoggle (verb)',
    'Jibberwobble (noun)',
    'Kerflapdoodle (noun)',
    'Mumblefritz (noun)',
    'Nibblequake (noun)',
    'Oofletoff (exclamation)',
    'Pudderfluke (noun)',
    'Quibbleshanks (noun)',
    'Razzlecorn (noun)',
    'Shmorgle (verb)',
    'Tumblesnoot (noun)',
    'Vlumptious (adjective)',
    'Whiffleblatt (noun)',
    'Yammerloft (noun)',
    'Zonkerdoodle (noun)',
    'Clonkwaddle (verb)',
    'Dribbleflump (noun)',
    'Fizzlebatch (noun)',
    'Gloopernaut (noun)',
    'Spreadsheetosis (noun)',
    'Replyallanche (noun)',
    'Snackrifice (noun)',
    'Deskcellence (noun)',
    'Calendarkness (noun)',
    'Blunderwhelm (verb)',
    'Mugnesia (noun)',
  ],
  pitch: [
    'Bluetooth socks.',
    'A smart toaster that judges your choice of bread.',
    'Scented Wi-Fi.',
    'An umbrella for your sandwich.',
    'A doorbell for your fridge.',
    'Self-cleaning spaghetti.',
    'A GPS for finding the TV remote.',
    'Waterproof tea bags.',
    'A treadmill for goldfish.',
    'Glow-in-the-dark soup.',
    'A subscription box of single left shoes.',
    'A voice assistant that only answers in riddles.',
    'Inflatable office chairs.',
    'A candle that smells exactly like Monday morning.',
    'An app that tells you when your houseplants are gossiping about you.',
    'Decaf energy drinks.',
    'A hat with a smaller hat built in.',
    'A mug that keeps your coffee perfectly at room temperature.',
    'Powdered water. Just add water.',
    'A calendar with an extra day nobody is allowed to book.',
    'A pillow with a snooze button.',
    'A dishwasher just for socks.',
    'An emotional-support cactus.',
    'A pen that only writes in the past tense.',
    'A solar-powered torch.',
    'Edible sticky notes.',
    'A tiny parachute for your phone.',
    'A rewind button for awkward conversations.',
    'A microwave that asks how your day was.',
    'Stilts for meetings, so people finally take you seriously.',
    'A keyboard with only one key.',
    'A sat-nav that gives directions through interpretive dance.',
    'Bubble-wrap wallpaper.',
    'A lawnmower for carpets.',
    'Artisanal, hand-crafted ice cubes.',
    'Office lighting that changes colour with your mood.',
    'An alarm clock that apologises.',
    'A perfume that smells like {player}.',
    'A dating app for houseplants.',
    'A bicycle for your cat.',
    'Noise-cancelling earmuffs for your inner monologue.',
    'A self-driving shopping trolley with a bad attitude.',
  ],
  explain: [
    'Explain Wi-Fi.',
    'Explain how aeroplanes stay in the air.',
    'Explain photosynthesis.',
    'Explain how the internet works.',
    'Explain why the sky is blue.',
    'Explain taxes.',
    'Explain what a spreadsheet is.',
    'Explain gravity.',
    'Explain how a refrigerator works.',
    'Explain the stock market.',
    'Explain how a microwave heats food.',
    'Explain why cats knock things off tables.',
    'Explain how bees make honey.',
    'Explain the story of Cinderella.',
    'Explain rain.',
    'Explain how to tie a shoelace.',
    'Explain what a password is.',
    'Explain why we have time zones.',
    'Explain what a meeting is to a visiting alien.',
    'Explain electricity.',
    'Explain how magnets work.',
    'Explain the phases of the Moon.',
    'Explain why the chicken crossed the road.',
    'Explain how to make toast.',
    'Explain “the cloud” where files are stored.',
    'Explain email to a medieval knight.',
    'Explain hiccups.',
    'Explain how a lighthouse works.',
    'Explain volcanoes.',
    'Explain what {player} does all day.',
    'Explain recycling.',
    'Explain how traffic lights decide when to change.',
    'Explain dreams.',
    'Explain the office coffee machine.',
    'Explain snow.',
    'Explain why clocks go forward and back.',
    'Explain how fish breathe.',
    'Explain rainbows.',
    'Explain the offside rule.',
    'Explain why toast always lands butter-side down.',
    'Explain how {player} got so good at this game.',
    'Explain what happens to the socks that go missing in the laundry.',
  ],
  hypothetical: [
    'If the office printer could talk, what would its first words be?',
    'If animals could vote, which animal would win the election, and why?',
    'If your pet had a job, what would it be?',
    'If Monday were a person, what would you say to them?',
    'Aliens land and ask to see humanity’s finest achievement. What do you show them?',
    'If your life had a theme song, what would it be called?',
    'You can add one new rule to the office. What is it?',
    'If gravity switched off for one minute every day, what would the new routine be?',
    'If your furniture came to life at night, what would the couch complain about?',
    'If you came with a warning label, what would it say?',
    'If clouds were edible, what flavour would a thunderstorm be?',
    'You’re a ghost haunting an office. What’s your spookiest move?',
    'If you could replace every meeting with one thing, what would it be?',
    'What does your coffee mug do when nobody is looking?',
    'If the post office had a mascot, what would it be?',
    'A genie grants you one wish, but it has to be extremely boring. What do you wish for?',
    'If you were a superhero, what would your oddly specific weakness be?',
    'If a pigeon ran the country, what would its first new law be?',
    'If your car could talk, what would it gossip about?',
    'If your inbox were a zoo, which animal would the reply-all email be?',
    'If {player} became mayor, what would their first new public holiday be?',
    'If {player} were an ice cream flavour, what would it be called?',
    'If the Moon had a customer complaints line, what would people complain about?',
    'If missing socks could talk, what would they say?',
    'You’ve been named Supreme Ruler of Snacks. What’s your first decree?',
    'Time travel is possible, but only to last Tuesday. What do you do?',
    'If your houseplant wrote a review of you, what would it say?',
    'If dogs had a stock market, what would be the hottest stock?',
    'A penguin shows up at your door with a suitcase. What does it want?',
    'If sleeping were an Olympic sport, what would the medal ceremony look like?',
    'If your shadow quit, what would its resignation letter say?',
    'If every sneeze played a sound effect, which one would you want?',
    'You can rename one day of the week. What’s the new name?',
    'If the office elevator had a personality, what would it be like?',
    'If your life were a video game, what would the tutorial say?',
    'If the office plant could give out one award, what would it be?',
    'If you could make one thing in the world slightly smaller, what would it be?',
    'If {player} had a reality show, what would it be about?',
    'A dragon moves in next door. What’s the first neighbourly problem?',
    'If your alarm clock could negotiate, what would it offer you?',
    'If fruits had job titles, what would a banana’s be?',
    'If you could hire a narrator for your life, what would they say right now?',
  ],
  story: [
    'A two-line horror story set in an office.',
    'A two-line love story between two kitchen appliances.',
    'A two-line mystery that begins: “The cookies were gone.”',
    'A two-line adventure starring a very brave hamster.',
    'A two-line story that begins: “The elevator doors opened…”',
    'A two-line fairy tale with a twist ending.',
    'A two-line sci-fi story about a toaster.',
    'A two-line story that ends: “…and that’s why I no longer own a trampoline.”',
    'A two-line story about the last slice of pizza.',
    'A two-line story told by a lost sock.',
    'A two-line thriller about a missing stapler.',
    'A two-line story about a dragon’s first day at school.',
    'A two-line story that begins: “Nobody expected the pigeon to speak.”',
    'A two-line bedtime story for a robot.',
    'A two-line story about a heist at a bakery.',
    'A two-line story set in the only coffee shop on the Moon.',
    'A two-line horror story told by a houseplant.',
    'A two-line story that begins: “The GPS said ‘You have arrived.’ We had not.”',
    'A two-line superhero origin story involving a vending machine.',
    'A two-line story about a wizard who can only cast one very specific spell.',
    'A two-line story that ends: “…and the goat was elected.”',
    'A two-line story about {player}’s legendary holiday.',
    'A two-line story about {player} and a very confused penguin.',
    'A two-line pirate story with a surprising treasure.',
    'A two-line story about the world’s most dramatic sneeze.',
    'A two-line romance between a pen and a sticky note.',
    'A two-line story that begins: “The meeting could have been an email.”',
    'A two-line story about a time traveller who only went back five minutes.',
    'A two-line western set in a shopping centre.',
    'A two-line story about a snowman who moves to the desert.',
    'A two-line story narrated by a very tired alarm clock.',
    'A two-line story that ends: “…and that’s how the cat became CEO.”',
    'A two-line ghost story set at a car wash.',
    'A two-line nature documentary about office workers in their natural habitat.',
    'A two-line space opera about a lost TV remote.',
    'A two-line story that begins: “The robot watched the sunset and said…”',
    'A two-line fable with a very questionable moral.',
    'A two-line story about a detective duck.',
    'A two-line story that begins: “Grandma’s new motorbike arrived today.”',
    'A two-line story about the world’s most competitive game of hide-and-seek.',
    'A two-line story where the villain is a very polite goose.',
    'A two-line story about a printer that finally snaps.',
  ],
  name: [
    'Name a restaurant that only serves breakfast for dinner.',
    'Name a boy band made up entirely of accountants.',
    'Name the world’s least intimidating superhero.',
    'Name a brand-new crisp flavour.',
    'Name a perfume that smells like Monday morning.',
    'Name a dog-walking service for cats.',
    'Name a fitness class for people who hate exercise.',
    'Name the world’s slowest racehorse.',
    'Name a new holiday that everyone would celebrate.',
    'Name a self-help book written by a cat.',
    'Name a heavy-metal band made up of grandmas.',
    'Name a cruise ship you would never board.',
    'Name a dinosaur discovered in an office.',
    'Name the sequel to a movie about a haunted fax machine.',
    'Name a board game that ends friendships.',
    'Name a cologne for pirates.',
    'Name a reality TV show set in a library.',
    'Name a new sport played with office chairs.',
    'Name a robot that only does one chore.',
    'Name the planet where all the lost socks go.',
    'Name a spa for tired robots.',
    'Name a breakfast cereal for adults who have given up.',
    'Name a food truck run by wizards.',
    'Name a secret society for people who love spreadsheets.',
    'Name a candle scent for people who miss the office.',
    'Name a detective agency run by pigeons.',
    'Name a theme park for introverts.',
    'Name the hit single by a band of {player} clones.',
    'Name a video game where {player} is the final boss.',
    'Name a new crayon colour.',
    'Name a sandwich served at a medieval feast.',
    'Name an app nobody needs.',
    'Name a bakery owned by a dragon.',
    'Name a bank for squirrels.',
    'Name a luxury hotel for houseplants.',
    'Name a cooking show hosted by a toddler.',
    'Name the world’s most disappointing magic trick.',
    'Name a new dance move.',
    'Name a dating show for vampires.',
    'Name a kitchen gadget that solves a problem nobody has.',
    'Name a yoga pose for people stuck in meetings.',
    'Name the office’s emergency snack drawer.',
  ],
};

/** Total built-in prompts (for the settings panel). */
export function builtInPromptCount(types: readonly MpBuiltInType[]): number {
  return types.reduce((n, t) => n + (PROMPT_PACK[t]?.length ?? 0), 0);
}

/**
 * Generic "safety" answers a stuck writer can start from (client-side suggestion only; the
 * server treats whatever is submitted as an ordinary answer).
 */
export const SAFETY_ANSWERS: readonly string[] = [
  'Something with a suspicious amount of glitter.',
  'My lawyer has advised me not to answer this one.',
  'A strongly worded note taped to the fridge.',
  'Three pigeons and a very small hat.',
  'Whatever it is, it definitely needs a meeting.',
  'I would simply walk away. Dramatically.',
  'The answer is soup. The answer is always soup.',
  'Honestly? A nap.',
  'An extremely confident goose.',
  'Several interpretive dances, performed at once.',
  'All fun and games until the printer got involved.',
  'Ask me again after lunch.',
];
