/**
 * Forbidden Letter categories — original, office-safe, common-noun (or common-verb/adjective)
 * categories whose answers are ordinary dictionary words. Proper nouns (countries, brands, people)
 * are deliberately avoided because the dictionary has no proper nouns.
 *
 * `members` are the answers DASwords approves automatically (singular forms; plurals are folded:
 * "apples" → "apple"). Any other dictionary-valid answer goes to the host for a quick
 * approve/reject (or is trusted, if the host chose "trust" review). Every member word is checked
 * against the shipped dictionary in the server tests.
 */

export interface ForbiddenCategory {
  id: string;
  label: string;
  hint: string;
  members: readonly string[];
}

const list = (s: string): string[] =>
  s
    .split(',')
    .map((w) => w.trim())
    .filter(Boolean);

export const FORBIDDEN_CATEGORIES: readonly ForbiddenCategory[] = [
  {
    id: 'animals',
    label: 'Animals',
    hint: 'Wild, farm or pet — any animal.',
    members: list(`aardvark, alligator, alpaca, anteater, antelope, armadillo, baboon, badger, bat, bear, beaver, bison, boar, buffalo,
      bull, bunny, calf, camel, cat, cheetah, chimpanzee, chipmunk, cougar, cow, coyote, crocodile, deer, dingo, dog, donkey, dolphin,
      elephant, elk, ferret, fox, frog, gazelle, gecko, gerbil, giraffe, goat, gopher, gorilla, hamster, hare, hedgehog, hippo,
      hippopotamus, horse, hyena, iguana, impala, jackal, jaguar, kangaroo, kitten, koala, lamb, lemur, leopard, lion, lizard, llama,
      lynx, meerkat, mink, mole, mongoose, monkey, moose, mouse, mice, mule, otter, oxen, panda, panther, pig, piglet, platypus,
      polecat, pony, porcupine, possum, opossum, puma, puppy, rabbit, raccoon, ram, rat, reindeer, rhino, rhinoceros, salamander,
      seal, sheep, skunk, sloth, snake, squirrel, stoat, tapir, tiger, toad, tortoise, turtle, walrus, warthog, weasel, whale,
      wolf, wombat, yak, zebra, bobcat, caribou, chinchilla, hound, marmot, ocelot, orangutan, pup, stallion, mare, foal`),
  },
  {
    id: 'birds',
    label: 'Birds',
    hint: 'Anything with feathers.',
    members: list(`albatross, blackbird, bluebird, budgie, buzzard, canary, cardinal, chicken, cockatoo, condor, crane, crow, cuckoo,
      dove, duck, eagle, egret, emu, falcon, finch, flamingo, goose, geese, grouse, gull, seagull, hawk, hen, heron, hummingbird,
      ibis, jay, kestrel, kingfisher, kite, kiwi, lark, macaw, magpie, mockingbird, nightingale, oriole, osprey, ostrich, owl,
      parakeet, parrot, partridge, peacock, pelican, penguin, pheasant, pigeon, puffin, quail, raven, robin, rooster, sandpiper,
      sparrow, starling, stork, swallow, swan, swift, thrush, toucan, turkey, vulture, warbler, woodpecker, wren, chick, duckling,
      gosling, songbird, bluejay, cormorant, lovebird, peahen`),
  },
  {
    id: 'sea',
    label: 'Sea creatures',
    hint: 'Things that live in the ocean.',
    members: list(`anchovy, barracuda, clam, cod, coral, crab, cuttlefish, dolphin, eel, flounder, grouper, haddock, halibut, herring,
      jellyfish, krill, lobster, mackerel, manatee, marlin, minnow, mussel, narwhal, octopus, orca, oyster, plankton, porpoise,
      prawn, ray, stingray, salmon, sardine, scallop, seahorse, seal, shark, shrimp, snapper, sponge, squid, starfish, sturgeon,
      swordfish, trout, tuna, turtle, urchin, walrus, whale, anemone, barnacle, conch, cockle, limpet, mullet, pollock,
      sole, tilapia, bass, catfish, pufferfish, blowfish, sunfish, walleye, plaice, carp, perch, pike`),
  },
  {
    id: 'insects',
    label: 'Bugs & creepy-crawlies',
    hint: 'Insects, spiders, worms and friends.',
    members: list(`ant, aphid, bee, beetle, bumblebee, butterfly, caterpillar, centipede, cicada, cockroach, cricket, dragonfly, earwig,
      firefly, flea, fly, gnat, grasshopper, hornet, housefly, ladybug, ladybird, larva, locust, louse, lice, maggot, mantis,
      midge, millipede, mite, mosquito, moth, scorpion, silkworm, slug, snail, spider, stick insect, termite, tick, wasp, weevil,
      worm, earthworm, bug, bedbug, hoverfly, katydid, tarantula, glowworm, woodlouse, honeybee, bluebottle, cocoon,
      grub, chrysalis`),
  },
  {
    id: 'fruit',
    label: 'Fruit',
    hint: 'Sweet, sour or tropical.',
    members: list(`apple, apricot, avocado, banana, blackberry, blackcurrant, blueberry, boysenberry, cantaloupe, cherry, clementine,
      coconut, cranberry, currant, date, dragonfruit, durian, elderberry, fig, gooseberry, grape, grapefruit, guava, honeydew,
      jackfruit, kiwi, kumquat, lemon, lime, lychee, mandarin, mango, melon, mulberry, nectarine, olive, orange, papaya,
      passionfruit, peach, pear, persimmon, pineapple, plantain, plum, pomegranate, prune, quince, raisin, raspberry, rhubarb,
      satsuma, starfruit, strawberry, tangerine, tomato, watermelon, berry, citrus, sultana, loganberry, huckleberry, damson`),
  },
  {
    id: 'vegetables',
    label: 'Vegetables',
    hint: 'From the garden to the plate.',
    members: list(`artichoke, arugula, asparagus, aubergine, bean, beet, beetroot, broccoli, cabbage, carrot, cauliflower, celery,
      chard, chickpea, chili, chilli, corn, courgette, cucumber, eggplant, endive, fennel, garlic, ginger, kale, leek, lentil,
      lettuce, mushroom, okra, onion, parsley, parsnip, pea, pepper, potato, pumpkin, radish, rutabaga, scallion, shallot,
      spinach, sprout, squash, swede, sweetcorn, turnip, watercress, yam, zucchini, cress, gherkin, pickle, maize, soybean,
      jalapeno, pimento, rocket, spud, legume, kohlrabi, celeriac, radicchio, basil, tomato`),
  },
  {
    id: 'food',
    label: 'Foods & dishes',
    hint: 'Meals, snacks and everything in between.',
    members: list(`bagel, burger, hamburger, burrito, casserole, cheese, chili, chowder, crepe, curry, dumpling, falafel, fries,
      hotdog, hot dog, kebab, lasagna, lasagne, meatball, noodle, nachos, omelette, omelet, pancake, pasta, pie, pizza, porridge,
      pretzel, quiche, ravioli, risotto, salad, sandwich, sausage, soup, spaghetti, steak, stew, sushi, taco, toast, tortilla,
      waffle, rice, bread, chips, crisps, popcorn, cracker, biscuit, muffin, roll, bun, wrap, stir fry, fish, chicken, bacon, ham,
      egg, beef, pork, lamb, tofu, hummus, salsa, gravy, dip, fondue, paella, goulash, pierogi, samosa, dim sum, ramen, pho,
      couscous, quinoa, cornbread, meatloaf, jerky, pickle, sauerkraut, nugget, pastry, cake, scone`),
  },
  {
    id: 'desserts',
    label: 'Desserts & sweets',
    hint: 'Something for the sweet tooth.',
    members: list(`brownie, cake, candy, caramel, cheesecake, chocolate, cookie, cupcake, custard, doughnut, donut, fudge, gelato,
      gingerbread, ice cream, jelly, lollipop, macaroon, marshmallow, meringue, mousse, muffin, nougat, pancake, pie, pudding,
      shortbread, sorbet, sundae, tart, toffee, trifle, truffle, waffle, biscuit, brittle, butterscotch, cobbler, crumble,
      eclair, flan, gumdrop, licorice, liquorice, mint, pastry, praline, ice lolly, sherbet, sponge, strudel, tiramisu, turnover,
      marzipan, jellybean, gum, bonbon, cannoli, churro, parfait, souffle, crepe, scone, honeycomb, fondant, frosting, icing`),
  },
  {
    id: 'drinks',
    label: 'Drinks',
    hint: 'Hot, cold, fizzy or fancy.',
    members: list(`water, juice, milk, tea, coffee, cocoa, lemonade, soda, smoothie, milkshake, shake, espresso, latte, cappuccino,
      mocha, chai, cider, punch, cola, tonic, kombucha, broth, beer, wine, champagne, cocktail, mocktail, eggnog, slushie,
      buttermilk, yogurt, americano, macchiato, hot chocolate, iced tea, orangeade, root beer, ginger ale, sparkling water,
      seltzer, squash, cordial, nectar, frappe, kefir, lassi, sake, whisky, whiskey, rum, gin, vodka, brandy, lager, ale, stout,
      sherry, port, mead`),
  },
  {
    id: 'breakfast',
    label: 'Breakfast foods',
    hint: 'What you might eat before noon.',
    members: list(`bacon, bagel, banana, biscuit, bread, butter, cereal, coffee, croissant, crumpet, doughnut, egg, granola, grits,
      ham, hash brown, honey, jam, juice, marmalade, muesli, muffin, oatmeal, oats, omelette, omelet, pancake, porridge, sausage,
      scone, smoothie, toast, waffle, yogurt, yoghurt, fruit, milk, tea, cornflakes, syrup, fritter, bun, crepe, danish, kipper,
      hashbrown, quiche, avocado, tomato, mushroom, beans, cheese, cream, berry`),
  },
  {
    id: 'kitchen',
    label: 'Things in a kitchen',
    hint: 'Gadgets, utensils and appliances.',
    members: list(`apron, blender, bowl, bread bin, can opener, chopstick, colander, cooker, corkscrew, cup, cupboard, cutting board,
      dishwasher, fork, freezer, fridge, refrigerator, frying pan, grater, grill, jar, jug, kettle, knife, ladle, lid, microwave,
      mixer, mug, napkin, oven, pan, peeler, pitcher, plate, pot, rolling pin, saucepan, saucer, scale, sieve, sink, skillet,
      spatula, spoon, stove, strainer, teapot, timer, toaster, tongs, tray, whisk, wok, cookbook, dish, glass, tumbler, platter,
      thermos, funnel, sponge, towel, oven mitt, coaster, placemat, spice rack, pantry, counter, faucet, tap`),
  },
  {
    id: 'office',
    label: 'Things in an office',
    hint: 'Desk, meeting room or break room.',
    members: list(`binder, calculator, calendar, chair, clipboard, clock, coffee, computer, copier, cubicle, desk, diary, drawer,
      envelope, eraser, file, folder, headset, highlighter, keyboard, lamp, laptop, marker, monitor, mouse, mug, notebook, notepad,
      paper, paperclip, pen, pencil, phone, telephone, photocopier, printer, projector, ruler, scanner, scissors, shredder,
      stapler, staple, sticky note, tablet, tape, whiteboard, whiteboard marker, webcam, badge, lanyard, plant, kettle, fridge,
      microwave, water cooler, filing cabinet, bookshelf, bulletin board, noticeboard, pushpin, thumbtack, rubber band, label,
      memo, agenda, report, spreadsheet, invoice, receipt, stamp, postcard, cabinet, headphones, charger, cable, router`),
  },
  {
    id: 'jobs',
    label: 'Jobs & professions',
    hint: 'What people do for a living.',
    members: list(`accountant, actor, architect, artist, astronaut, athlete, baker, barber, barista, bartender, builder, butcher,
      captain, carpenter, cashier, chef, chemist, cleaner, coach, cook, dancer, dentist, designer, detective, developer, doctor,
      driver, editor, electrician, engineer, farmer, firefighter, fisherman, florist, gardener, guard, hairdresser, janitor,
      journalist, judge, lawyer, librarian, lifeguard, manager, mechanic, midwife, miner, musician, nanny, nurse, optician,
      painter, paramedic, pharmacist, photographer, physicist, pilot, plumber, police officer, politician, porter, postman,
      professor, programmer, receptionist, reporter, sailor, scientist, secretary, singer, soldier, surgeon, tailor, teacher,
      technician, therapist, translator, tutor, vet, veterinarian, waiter, waitress, writer, author, analyst, auditor, banker,
      broker, clerk, consultant, courier, curator, economist, geologist, glazier, grocer, jeweller, jeweler, locksmith, mason,
      model, novelist, poet, potter, ranger, sculptor, surveyor, zookeeper, blacksmith, chauffeur, conductor, diver, gamer,
      illustrator, inventor, principal, publisher, recruiter, referee, roofer, salesman, tiler, trainer, usher, welder`),
  },
  {
    id: 'sports',
    label: 'Sports & games',
    hint: 'Played on a pitch, court, table or track.',
    members: list(`archery, athletics, badminton, baseball, basketball, billiards, bowling, boxing, canoeing, chess, climbing,
      cricket, croquet, curling, cycling, darts, diving, dodgeball, fencing, football, golf, gymnastics, handball, hiking, hockey,
      judo, karate, kayaking, lacrosse, netball, polo, pool, racing, rowing, rugby, running, sailing, skateboarding, skating,
      skiing, snooker, snowboarding, soccer, softball, squash, surfing, swimming, table tennis, taekwondo, tennis, triathlon,
      volleyball, water polo, wrestling, yoga, marathon, sprint, jogging, bobsleigh, luge, biathlon, decathlon,
      pentathlon, rounders, pickleball, kickball, parkour, bouldering, paddleboarding, windsurfing, kitesurfing, rafting, ping pong,
      dominoes, checkers, draughts, bingo, charades, poker, tag`),
  },
  {
    id: 'clothing',
    label: 'Clothing & accessories',
    hint: 'Anything you can wear.',
    members: list(`apron, belt, beanie, bikini, blazer, blouse, boot, bow tie, bracelet, cap, cape, cardigan, coat, dress, earring,
      glove, gown, hat, headband, hoodie, jacket, jeans, jumper, kilt, leggings, mitten, necklace, nightgown, overalls, pajamas,
      pyjamas, poncho, raincoat, ring, robe, sandal, sarong, scarf, shirt, shoe, shorts, skirt, slipper, sneaker, sock, suit,
      sunglasses, sweater, sweatshirt, swimsuit, tie, tights, trainer, trousers, tuxedo, uniform, vest, waistcoat, watch, wig,
      bandana, beret, bonnet, bootie, brooch, buckle, cufflink, dungarees, flipflop, flip flop, fleece, helmet, jersey, kimono,
      loafer, moccasin, parka, pendant, pullover, sash, shawl, stiletto, tank top, turban, visor, wellington, clog, tunic, windbreaker`),
  },
  {
    id: 'instruments',
    label: 'Musical instruments',
    hint: 'Blow it, bang it, pluck it or play it.',
    members: list(`accordion, bagpipes, banjo, bass, bassoon, bell, bongo, bugle, cello, clarinet, cornet, cymbal, didgeridoo, drum,
      fiddle, flute, glockenspiel, gong, guitar, harmonica, harp, harpsichord, horn, kazoo, keyboard, lute, mandolin, maraca,
      marimba, oboe, organ, piano, piccolo, recorder, saxophone, sitar, synthesizer, tambourine, timpani, triangle, trombone,
      trumpet, tuba, ukulele, viola, violin, xylophone, zither, castanet, harmonium, lyre, ocarina, panpipe, sousaphone, tabla,
      bouzouki, balalaika, cowbell, washboard, woodblock, vibraphone, celesta, dulcimer, kalimba`),
  },
  {
    id: 'body',
    label: 'Body parts',
    hint: 'Head to toe (keep it office-friendly).',
    members: list(`ankle, arm, back, beard, belly, bone, brain, brow, calf, cheek, chest, chin, ear, elbow, eye, eyebrow, eyelash,
      eyelid, face, finger, fingernail, fist, foot, feet, forehead, gum, hair, hand, head, heart, heel, hip, jaw, kidney, knee,
      kneecap, knuckle, leg, lip, liver, lung, mouth, muscle, nail, navel, neck, nose, nostril, palm, rib, scalp, shin, shoulder,
      skin, skull, spine, stomach, temple, thigh, throat, thumb, toe, tongue, tooth, teeth, waist, wrist, artery, vein, tendon,
      ligament, pupil, iris, retina, eardrum, earlobe, dimple, freckle, moustache, mustache, sideburn, torso, abdomen, pelvis,
      collarbone, spleen, pancreas, bladder, appendix, tonsil, larynx, windpipe, cartilage, sinus`),
  },
  {
    id: 'vehicles',
    label: 'Vehicles',
    hint: 'Anything that gets you from A to B.',
    members: list(`aeroplane, airplane, ambulance, bicycle, bike, blimp, boat, bulldozer, bus, cab, canoe, car, caravan, cart,
      coach, convertible, crane, ferry, glider, helicopter, hovercraft, jeep, jet, kayak, limousine, lorry, minibus, moped,
      motorbike, motorcycle, raft, rickshaw, rocket, sailboat, scooter, ship, skateboard, sled, sledge, sleigh, snowmobile,
      spaceship, submarine, subway, tank, taxi, tractor, trailer, train, tram, tricycle, trolley, truck, tugboat, unicycle, van,
      wagon, yacht, zeppelin, forklift, gondola, hatchback, pickup, sedan, speedboat, steamboat, streetcar, dinghy,
      catamaran, cruiser, freighter, tanker, airship, balloon, monorail, carriage, chariot, buggy, dumper, excavator, digger`),
  },
  {
    id: 'weather',
    label: 'Weather words',
    hint: 'What’s it doing outside?',
    members: list(`blizzard, breeze, chilly, cloud, cloudy, cold, cyclone, damp, downpour, drizzle, drought, dry, flood, fog, foggy,
      freezing, frost, frosty, gale, gust, hail, heat, heatwave, humid, hurricane, ice, icy, lightning, mist, misty, monsoon,
      overcast, rain, rainbow, rainy, sleet, slush, smog, snow, snowflake, snowy, storm, stormy, sun, sunny, sunshine, thunder,
      thunderstorm, tornado, twister, typhoon, warm, wet, wind, windy, dew, puddle, hot, scorching, sweltering, balmy, muggy,
      clear, bright, gloomy, drizzly, blustery, squall, whirlwind, temperature, forecast, climate, avalanche, flurry, haze, hazy`),
  },
  {
    id: 'colours',
    label: 'Colours',
    hint: 'Shades, tints and hues.',
    members: list(`amber, aqua, azure, beige, black, blue, bronze, brown, burgundy, charcoal, cherry, chocolate, coral, cream,
      crimson, cyan, emerald, fuchsia, gold, golden, gray, grey, green, indigo, ivory, jade, khaki, lavender, lemon, lilac, lime,
      magenta, maroon, mauve, mint, mustard, navy, ochre, olive, orange, peach, pink, plum, purple, red, rose, ruby, rust,
      saffron, salmon, sapphire, scarlet, silver, tan, taupe, teal, turquoise, ultramarine, vermilion, violet, white, yellow,
      apricot, auburn, blonde, cobalt, copper, ebony, magnolia, pearl, periwinkle, sepia, sky blue, tangerine, cerise, chartreuse`),
  },
  {
    id: 'feelings',
    label: 'Feelings & emotions',
    hint: 'How are you feeling right now?',
    members: list(`afraid, amazed, amused, angry, annoyed, anxious, ashamed, bored, brave, calm, cheerful, confident, confused,
      content, curious, delighted, disappointed, eager, embarrassed, excited, fear, frustrated, glad, gloomy, grateful, grumpy,
      guilty, happy, hopeful, hurt, impatient, jealous, joy, joyful, lonely, love, mad, miserable, nervous, overjoyed, proud,
      relaxed, relieved, sad, scared, shy, sleepy, sorry, stressed, surprised, tense, thankful, thrilled, tired, upset, worried,
      bliss, cranky, dread, ecstatic, elated, envy, furious, giddy, gleeful, grief, hope, irritated, jolly, keen, merry,
      moody, nostalgic, optimistic, peaceful, pleased, puzzled, rage, satisfied, serene, sulky, sympathy, terrified, uneasy`),
  },
  {
    id: 'home',
    label: 'Furniture & things at home',
    hint: 'Look around your living room.',
    members: list(`armchair, bed, bench, bookcase, bookshelf, cabinet, carpet, chair, chandelier, chest, clock, closet, couch,
      cot, crib, cupboard, curtain, cushion, desk, drawer, dresser, duvet, futon, hammock, lamp, mattress, mirror, ottoman,
      pillow, quilt, rug, shelf, sideboard, sofa, stool, table, television, wardrobe, blanket, blind, doormat, fireplace, radiator,
      vase, picture, painting, poster, candle, coaster, footstool, beanbag, recliner, bunk bed, headboard, nightstand, heater, fan,
      radio, speaker, sheet, towel, basket, frame, houseplant, plant, window, door, stairs, banister, doorbell, letterbox`),
  },
  {
    id: 'tools',
    label: 'Tools',
    hint: 'Workshop, shed or toolbox.',
    members: list(`axe, awl, chisel, clamp, crowbar, drill, file, hacksaw, hammer, hatchet, hoe, ladder, level, mallet, pliers,
      rake, sander, saw, scissors, screwdriver, shears, shovel, sledgehammer, spade, spanner, stapler, tape measure, trowel,
      vice, vise, wheelbarrow, wrench, pickaxe, pitchfork, plane, ruler, knife, torch, flashlight, glue gun, nail, screw, bolt,
      nut, washer, rivet, sandpaper, paintbrush, roller, scraper, jigsaw, chainsaw, lathe, anvil, tongs, tweezers, multimeter,
      soldering iron, funnel, bucket, hose, sprinkler, mower, lawnmower, compass, protractor`),
  },
  {
    id: 'beach',
    label: 'Things at the beach',
    hint: 'Sun, sand and sea.',
    members: list(`bucket, crab, deckchair, dune, flipflop, lifeguard, lighthouse, ocean, pebble, pier, rock, sand, sandcastle,
      sea, seagull, seashell, shell, shore, spade, sunbathe, sunburn, sunglasses, sunscreen, sunshade, surfboard, swimsuit, tide,
      towel, umbrella, wave, starfish, seaweed, boardwalk, cooler, kite, parasol, picnic, rockpool, snorkel, surf,
      paddle, dolphin, jellyfish, boat, yacht, harbour, harbor, cove, bay, cliff, coast, beachball, ice cream, driftwood, hat,
      sandal, bikini, trunks, goggles, flag, lagoon, reef, sunset`),
  },
  {
    id: 'space',
    label: 'Space & the night sky',
    hint: 'Look up!',
    members: list(`alien, asteroid, astronaut, astronomer, atmosphere, comet, constellation, cosmos, crater, eclipse, galaxy,
      gravity, meteor, meteorite, moon, nebula, orbit, planet, quasar, rocket, satellite, shuttle, sky, spaceship, spacecraft,
      star, sun, supernova, telescope, universe, void, wormhole, black hole, dwarf, giant, moonbeam, starlight, sunrise,
      sunset, twilight, dusk, dawn, horizon, cloud, aurora, lunar, solar, rover, probe, capsule, launchpad, cosmonaut, observatory,
      stargazer, planetarium, spacesuit, helmet, module, lander, pulsar, starship, shooting star`),
  },
  {
    id: 'plants',
    label: 'Plants, trees & flowers',
    hint: 'Anything that grows.',
    members: list(`acorn, bamboo, begonia, birch, blossom, bluebell, bush, buttercup, cactus, carnation, cedar, clover, cypress,
      daffodil, daisy, dandelion, elm, fern, fir, flower, geranium, grass, hedge, heather, holly, hyacinth, iris, ivy, jasmine,
      lavender, lilac, lily, lotus, magnolia, maple, marigold, moss, mushroom, oak, orchid, palm, pansy, peony, petunia, pine,
      poppy, rose, sequoia, shrub, snowdrop, sunflower, thistle, tulip, violet, weed, willow, wisteria, yew, beech, ash, poplar,
      spruce, redwood, sycamore, chestnut, hawthorn, bonsai, seedling, sapling, vine, herb, basil, mint, rosemary, thyme, sage,
      cattail, crocus, dahlia, freesia, gardenia, hibiscus, honeysuckle, primrose, snapdragon, zinnia, algae, lichen, reed`),
  },
  {
    id: 'classroom',
    label: 'Things in a classroom',
    hint: 'Back to school.',
    members: list(`backpack, bag, bell, blackboard, board, book, bookcase, calculator, calendar, chair, chalk, clock, compass,
      computer, crayon, desk, dictionary, easel, eraser, exam, folder, globe, glue, highlighter, homework, lesson, locker, map,
      marker, notebook, paint, paper, pen, pencil, pencil case, poster, projector, protractor, pupil, quiz, register, ruler,
      scissors, sharpener, shelf, student, teacher, test, textbook, timetable, whiteboard, worksheet, atlas, binder, flashcard,
      laptop, tablet, microscope, periodic table, rubber, stapler, tape, trophy, uniform, jotter, workbook, lunchbox, sticker`),
  },
  {
    id: 'tech',
    label: 'Tech & computer words',
    hint: 'Things you’d find in IT.',
    members: list(`app, algorithm, backup, bandwidth, battery, browser, bug, byte, cable, camera, charger, chip, cloud,
      code, computer, console, cookie, cursor, data, database, desktop, download, drive, email, emoji, file, firewall, folder,
      gadget, hardware, headphones, icon, internet, keyboard, laptop, link, login, malware, memory, microchip, modem, monitor,
      mouse, network, offline, online, password, pixel, printer, processor, program, router, screen, server, smartphone,
      software, speaker, spreadsheet, tablet, touchscreen, update, upload, username, virus, webcam, website, wifi, window, widget,
      blog, podcast, hashtag, emulator, joystick, controller, headset, microphone, laser, robot, drone, satellite, megabyte,
      gigabyte, terabyte, kilobyte, bit, binary, cache, compiler, debug, encryption, hacker, inbox, keyword, spam, stream`),
  },
  {
    id: 'town',
    label: 'Places in a town',
    hint: 'Where would you go?',
    members: list(`airport, bakery, bank, barber, bookshop, bookstore, bridge, butcher, cafe, castle, cathedral, church, cinema,
      college, court, factory, farm, fire station, garage, gym, harbour, harbor, hospital, hotel, house, library, mall, market,
      mosque, motel, museum, office, park, pharmacy, playground, police station, pool, post office, prison, pub, restaurant,
      school, shop, stadium, station, store, supermarket, synagogue, temple, theatre, theater, tower, university, warehouse, zoo,
      arcade, bistro, boutique, bowling alley, bus stop, canteen, chapel, clinic, courthouse, deli, diner, garden, gallery,
      laundrette, laundromat, marina, newsagent, nightclub, pier, plaza, square, studio, subway, town hall, workshop`),
  },
  {
    id: 'farm',
    label: 'On the farm',
    hint: 'Old MacDonald had a…',
    members: list(`barn, bull, calf, chick, chicken, combine, corn, cow, crop, dog, donkey, duck, egg, farmer, fence, field, foal,
      gate, goat, goose, hay, haystack, hen, horse, lamb, llama, milk, mud, orchard, pig, piglet, plough, plow, pony, rooster,
      scarecrow, seed, sheep, shed, silo, stable, straw, tractor, trough, turkey, wheat, barley, oats, pasture, meadow, paddock,
      pen, sty, pigsty, coop, henhouse, hayloft, harvest, wool, cheese, butter, cream, alpaca, bale, bucket, pitchfork, wheelbarrow,
      sheepdog, kid, ram, ewe, sow, boar, steer, heifer, stallion, mare`),
  },
  {
    id: 'camping',
    label: 'Camping & outdoors',
    hint: 'Pack your bag for the woods.',
    members: list(`axe, backpack, binoculars, blanket, boot, campfire, canoe, compass, cooler, firewood, flashlight, hammock,
      hatchet, hike, kettle, knife, lantern, map, marshmallow, match, mosquito, pillow, rope, rucksack, sleeping bag, stove, tent,
      tarp, torch, trail, whistle, canteen, flask, fishing rod, forest, lake, log, mountain, river, stream, waterfall, woods,
      campsite, caravan, cabin, picnic, sunscreen, poncho, raincoat, helmet, kayak, paddle, raft, sausage, stars, owl, bear,
      firefly, tick, fleece, beanie, glove, sock, thermos, trowel, tripod, camera`),
  },
  {
    id: 'shapes',
    label: 'Shapes',
    hint: 'Draw it with a pencil and ruler.',
    members: list(`circle, square, triangle, rectangle, oval, ellipse, diamond, rhombus, pentagon, hexagon, heptagon, octagon,
      nonagon, decagon, polygon, star, heart, crescent, cube, sphere, cylinder, cone, pyramid, prism, cuboid, parallelogram,
      trapezium, trapezoid, kite, arrow, cross, spiral, arc, semicircle, ring, line, point, dot, curve, helix, torus,
      tetrahedron, octahedron, dodecahedron, icosahedron, quadrilateral, chevron, zigzag, wedge, blob, squiggle, loop`),
  },
  {
    id: 'materials',
    label: 'Materials',
    hint: 'What is it made of?',
    members: list(`aluminium, aluminum, brass, brick, bronze, canvas, cardboard, cement, ceramic, chalk, clay, concrete, copper,
      cork, cotton, denim, diamond, fabric, felt, fibreglass, fiberglass, glass, gold, granite, gravel, iron, ivory, lace, lead,
      leather, linen, marble, metal, nylon, paper, plaster, plastic, polyester, porcelain, rubber, sand, satin, silk, silver,
      slate, steel, stone, suede, timber, tin, titanium, velvet, vinyl, wax, wood, wool, zinc, bamboo, crystal, foam, foil,
      graphite, hemp, jute, latex, mahogany, oak, pewter, resin, sandstone, spandex, straw, tweed, wicker, carbon`),
  },
  {
    id: 'toys',
    label: 'Toys & games',
    hint: 'Found in a toy box.',
    members: list(`ball, balloon, block, boomerang, bubble, car, doll, dollhouse, domino, drum, flying disc, jigsaw, kite, marble,
      puppet, puzzle, rattle, robot, rocking horse, scooter, skateboard, slinky, spinner, teddy, teddy bear, top, train, trampoline,
      tricycle, yoyo, dice, cards, chess, checkers, crayon, bicycle, bike, swing, slide, seesaw, sandbox, pogo stick,
      skipping rope, hula hoop, kaleidoscope, playdough, action figure, figurine, stuffed animal, plush, whistle, water pistol,
      tambourine, xylophone, rubber duck, sticker, bingo, board game, video game, console, joystick, blocks, abacus`),
  },
  {
    id: 'cooking',
    label: 'Cooking verbs',
    hint: 'Things you do in a kitchen.',
    members: list(`bake, barbecue, baste, beat, blanch, blend, boil, braise, bread, broil, brown, char, chill, chop, cook, cool,
      core, cream, crush, cube, cut, deglaze, dice, drain, drizzle, dust, flip, fold, freeze, fry, garnish, glaze, grate, grill,
      grind, heat, julienne, knead, marinate, mash, measure, melt, mince, mix, peel, pickle, pinch, poach, pour, preheat, puree,
      reduce, rinse, roast, roll, saute, scramble, season, sear, serve, shred, sift, simmer, skewer, slice, smoke, soak, spread,
      sprinkle, squeeze, steam, stew, stir, strain, stuff, taste, thaw, toast, toss, whip, whisk, zest, microwave, defrost`),
  },
  {
    id: 'kind',
    label: 'Nice things to call a coworker',
    hint: 'Compliments only!',
    members: list(`amazing, awesome, bold, brave, bright, brilliant, calm, capable, careful, caring, charming, cheerful, clever,
      confident, cool, creative, curious, dedicated, dependable, determined, diligent, eager, energetic, fair, friendly, funny,
      generous, genius, gentle, genuine, gracious, great, hardworking, helpful, honest, humble, inspiring, inventive, kind, loyal,
      lovely, modest, motivated, nice, organised, organized, patient, polite, positive, punctual, reliable, resourceful,
      respectful, sharp, sincere, smart, supportive, talented, thoughtful, thorough, trustworthy, upbeat, warm, wise, witty,
      wonderful, legend, star, hero, champion, ace, gem, rockstar, superstar, visionary, whiz, wizard, marvellous, marvelous,
      fantastic, fabulous, splendid, stellar, radiant, sunny, jolly, earnest, focused, adaptable, approachable, articulate`),
  },
  {
    id: 'garden',
    label: 'In the garden',
    hint: 'Out the back door.',
    members: list(`bench, bird, birdbath, birdhouse, bush, compost, daisy, fence, flower, flowerbed, fountain, gate, gnome, grass,
      greenhouse, hedge, hose, lawn, leaf, mower, lawnmower, patio, path, plant, pond, pot, rake, rose, seed, shed, shovel, snail,
      soil, spade, sprinkler, swing, tree, trellis, trowel, tulip, vegetable, watering can, weed, wheelbarrow, worm, barbecue,
      decking, hammock, lantern, mulch, pergola, pebble, rockery, sundial, sunflower, trampoline, vine, bee, butterfly, ladybug,
      squirrel, fork, gloves, bulb, sapling, orchard, allotment, conservatory, doghouse, kennel`),
  },
  {
    id: 'bathroom',
    label: 'In the bathroom',
    hint: 'Scrub-a-dub.',
    members: list(`bath, bathtub, bathrobe, basin, brush, cabinet, comb, conditioner, cotton, deodorant, drain, faucet, floss,
      hairbrush, hairdryer, lotion, mirror, mouthwash, perfume, plunger, razor, rug, scale, shampoo, shower, shower cap, sink,
      soap, sponge, tap, tile, toilet, toilet paper, toothbrush, toothpaste, towel, tweezers, washcloth, bubble bath, bath mat,
      candle, cologne, curler, flannel, laundry basket, loofah, moisturiser, moisturizer, nail file, plaster, radiator, sunscreen,
      tissue, bin, tub, hook, rail, extractor fan, medicine, bandage, cream, gel, mousse, lipstick, mascara, makeup`),
  },
  {
    id: 'moves',
    label: 'Ways to move',
    hint: 'Verbs — run, hop, glide…',
    members: list(`amble, bounce, bound, canter, cartwheel, charge, climb, crawl, creep, cycle, dance, dart, dash, dive, drift,
      drive, flap, float, fly, gallop, glide, hike, hobble, hop, hover, hurry, jog, jump, leap, limp, lunge, march, meander,
      paddle, parade, plod, prance, prowl, race, ramble, roll, row, run, rush, sail, saunter, scamper, scoot, scramble, scurry,
      scuttle, shuffle, sidestep, skate, skip, slide, slink, slither, sneak, somersault, speed, spin, sprint, stagger, stomp,
      stride, stroll, strut, stumble, surf, swagger, sway, swim, swing, tiptoe, toddle, trek, trot, trudge, tumble, twirl, twist,
      waddle, walk, wander, whirl, wiggle, wobble, zigzag, zoom, swoop, soar, stretch, wriggle, clamber, vault, tramp, hustle`),
  },
  {
    id: 'containers',
    label: 'Containers',
    hint: 'Things that hold other things.',
    members: list(`bag, barrel, basket, bin, bottle, bowl, box, bucket, can, canister, carton, case, cask, chest, crate, cup, drum,
      envelope, flask, glass, hamper, jar, jug, kettle, locker, mug, pail, pan, parcel, pitcher, pocket, pot, pouch, purse,
      sack, safe, satchel, suitcase, tank, teapot, thermos, tin, trunk, tub, tube, urn, vase, vial, wallet, briefcase, backpack,
      rucksack, handbag, holdall, jerrycan, lunchbox, packet, pod, quiver, sheath, silo, skip, tote, tray, trough,
      vat, beaker, casket, coffer, keg, punnet, scabbard, tankard, thimble, tumbler, wineglass`),
  },
];

export function forbiddenCategory(id: string): ForbiddenCategory | undefined {
  return FORBIDDEN_CATEGORIES.find((c) => c.id === id);
}
