/**
 * DASwords dictionary: fast, in-memory, server-side word lookups.
 *
 * The shipped list (apps/game-server/src/rooms/words/data/dascade-words.txt) is generated by
 * scripts/words/build-dictionary.ts from two permissively licensed sources:
 *  - ENABLE2K (public domain) — the classic word-game list, all inflections included;
 *  - SCOWL (Kevin Atkinson, permissive licence) levels 10–50 — everyday modern and British spellings
 *    that ENABLE lacks ("email", "blog", "colour"), and word-frequency tiers.
 * Every word is lowercase a–z, 3–15 letters, with the office-safe blocklist removed.
 *
 * Tiers (used for puzzle seeds, "missed word" lists and rarity bonuses):
 *   1 everyday — SCOWL ≤ 35 (well-known words: good anagram seeds / chain words)
 *   2 familiar — SCOWL 40–50
 *   3 rare     — ENABLE only (valid, but obscure: "qat", "zax")
 *
 * Text format: `[1]`, `[2]`, `[3]` section markers, one word per line, `#` comments.
 * Lookups are a Map (O(1)); prefix queries binary-search one sorted array, so a whole 5×5
 * board solves in milliseconds without a memory-hungry object trie.
 */
import { isBlockedWord } from './blocklist.ts';

export type WordTier = 1 | 2 | 3;

export const MIN_WORD_LENGTH = 3;
export const MAX_WORD_LENGTH = 15;

/** Lowercases, folds accents/full-width forms and keeps only a–z ("Café!" → "cafe"). */
export function normalizeWord(raw: string): string {
  return raw
    .normalize('NFKD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

/** Like normalizeWord but keeps single spaces between words (for multi-word answers). */
export function normalizePhrase(raw: string): string {
  return raw
    .normalize('NFKD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[-_/]+/g, ' ')
    .replace(/[^a-z\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

export class WordDictionary {
  private readonly tiers: Map<string, WordTier>;
  private readonly sorted: string[];
  private byLength: Map<number, string[]> | null = null;

  private constructor(tiers: Map<string, WordTier>) {
    this.tiers = tiers;
    this.sorted = [...tiers.keys()].sort();
  }

  /** Builds a dictionary from (word, tier) pairs. Invalid shapes and blocked words are dropped. */
  static fromEntries(entries: Iterable<readonly [string, WordTier]>): WordDictionary {
    const tiers = new Map<string, WordTier>();
    for (const [raw, tier] of entries) {
      const word = raw.trim().toLowerCase();
      if (!/^[a-z]+$/.test(word) || word.length < MIN_WORD_LENGTH || word.length > MAX_WORD_LENGTH) continue;
      if (isBlockedWord(word)) continue;
      const prev = tiers.get(word);
      if (prev === undefined || tier < prev) tiers.set(word, tier);
    }
    return new WordDictionary(tiers);
  }

  /** Convenience for tests: every word in `words` (tier 3 unless listed in `common`, tier 1). */
  static fromWords(words: Iterable<string>, common: Iterable<string> = []): WordDictionary {
    const commonSet = new Set(common);
    const entries: [string, WordTier][] = [];
    for (const w of words) entries.push([w, commonSet.has(w) ? 1 : 3]);
    for (const w of commonSet) entries.push([w, 1]);
    return WordDictionary.fromEntries(entries);
  }

  /** Parses the shipped text format (see file header). */
  static fromText(text: string): WordDictionary {
    const entries: [string, WordTier][] = [];
    let tier: WordTier = 3;
    for (const line of text.split('\n')) {
      const w = line.trim();
      if (!w || w.startsWith('#')) continue;
      if (w === '[1]' || w === '[2]' || w === '[3]') {
        tier = Number(w[1]) as WordTier;
        continue;
      }
      entries.push([w, tier]);
    }
    return WordDictionary.fromEntries(entries);
  }

  get size(): number {
    return this.sorted.length;
  }

  /** Whether `word` (already normalized, lowercase a–z) is an accepted DASwords word. */
  has(word: string): boolean {
    return this.tiers.has(word);
  }

  /** 0 when the word is not in the dictionary. */
  tier(word: string): WordTier | 0 {
    return this.tiers.get(word) ?? 0;
  }

  /** Everyday word (tier 1): suitable as a puzzle seed or a "missed word" suggestion. */
  isCommon(word: string): boolean {
    return this.tiers.get(word) === 1;
  }

  /** Index range [start, end) of the words starting with `prefix` in sorted order. */
  prefixRange(prefix: string): [number, number] {
    const start = lowerBound(this.sorted, prefix);
    // Every string with this prefix sorts before prefix + '{' ('{' follows 'z' in ASCII).
    const end = lowerBound(this.sorted, prefix + '{', start);
    return [start, end];
  }

  hasPrefix(prefix: string): boolean {
    const i = lowerBound(this.sorted, prefix);
    const w = this.sorted[i];
    return w !== undefined && w.startsWith(prefix);
  }

  /** Words starting with `prefix` (sorted), optionally filtered. */
  wordsWithPrefix(prefix: string, filter?: (word: string) => boolean): string[] {
    const [a, b] = this.prefixRange(prefix);
    const out: string[] = [];
    for (let i = a; i < b; i++) {
      const w = this.sorted[i] as string;
      if (!filter || filter(w)) out.push(w);
    }
    return out;
  }

  /** All words, sorted. */
  all(): readonly string[] {
    return this.sorted;
  }

  /** Words with exactly `length` letters (sorted; cached). */
  ofLength(length: number): readonly string[] {
    if (!this.byLength) {
      const map = new Map<number, string[]>();
      for (const w of this.sorted) {
        let list = map.get(w.length);
        if (!list) {
          list = [];
          map.set(w.length, list);
        }
        list.push(w);
      }
      this.byLength = map;
    }
    return this.byLength.get(length) ?? [];
  }
}

function lowerBound(arr: readonly string[], target: string, from = 0): number {
  let lo = from;
  let hi = arr.length;
  while (lo < hi) {
    const mid = (lo + hi) >>> 1;
    if ((arr[mid] as string) < target) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}
