/**
 * DAS Survey question packs — original, workplace-safe content written for DASCADE.
 *
 * Guidelines the content follows: light, inclusive, low-stakes questions a whole office can
 * answer; no politics, religion, health, money, relationships, age, appearance or anything
 * someone might not want a colleague to guess (small rooms can infer from totals); no brands
 * or copyrighted characters.
 *
 *  - majority: "which would you…" questions with 2–4 options.
 *  - rank:     "pick your favourite…" questions with 3–5 options (the room's votes form the order).
 *  - percent:  mostly yes/no questions; players guess the share of the TARGET option (index 0).
 */
import type { SurveyPackId, SurveyQuestion } from '@dascade/shared/games/survey';

type Q = SurveyQuestion;
const YES_NO = ['Yes', 'No'];

const m = (pack: SurveyPackId, n: number, prompt: string, options: string[]): Q => ({
  id: `${pack}-m-${n}`,
  mode: 'majority',
  prompt,
  options,
  pack,
});
const r = (pack: SurveyPackId, n: number, prompt: string, options: string[]): Q => ({
  id: `${pack}-r-${n}`,
  mode: 'rank',
  prompt,
  options,
  pack,
});
const p = (pack: SurveyPackId, n: number, prompt: string, options: string[] = YES_NO, target = 0): Q => ({
  id: `${pack}-p-${n}`,
  mode: 'percent',
  prompt,
  options,
  target,
  pack,
});

const office: Q[] = [
  m('office', 1, 'Which would you rather have every week?', ['A meeting-free Monday', 'A meeting-free Friday']),
  m('office', 2, 'Pick your ideal desk setup.', ['Standing desk', 'Big comfy chair', 'Beanbag corner', 'Wherever the Wi-Fi is best']),
  m('office', 3, 'When is the best time for a team lunch?', ['11:30, beat the rush', '12:30, the classic', '1:30, late and relaxed']),
  m('office', 4, 'How do you get a quick answer from a colleague?', ['Chat message', 'Walk over', 'Quick call', 'Email']),
  m('office', 5, 'Would you rather give the presentation or take the notes?', ['Give the presentation', 'Take the notes']),
  m('office', 6, 'Which office perk would you pick?', ['Free snacks', 'A nap pod', 'A game room', 'More plants and daylight']),
  m('office', 7, 'What is your inbox strategy?', ['Inbox zero', 'Thousands unread', 'Folders for everything', 'Just search for it']),
  m('office', 8, 'Camera on or off for a routine call?', ['Camera on', 'Camera off', 'Depends on the day']),
  m('office', 9, 'What is the perfect meeting length?', ['15 minutes', '25 minutes', '45 minutes', 'It should have been an email']),
  m('office', 10, 'Would you rather sit by the window or next to the coffee machine?', ['By the window', 'Next to the coffee']),
  m('office', 11, 'Pick the ideal team celebration.', ['Pizza party', 'Escape room', 'Board game night', 'Long lunch out']),
  m('office', 12, 'Where do you do your best thinking?', ['At my desk', 'On a walk', 'In the shower', 'Late at night']),
  r('office', 1, 'Pick your favourite meeting snack.', ['Cookies', 'Fruit', 'Pastries', 'Crisps', 'Chocolate']),
  r('office', 2, 'Which office chore would you volunteer for?', [
    'Watering the plants',
    'Restocking snacks',
    'Tidying the supply cupboard',
    'Cleaning the fridge',
    'Planning birthdays',
  ]),
  r('office', 3, 'What is your favourite day of the work week?', ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
  r('office', 4, 'Pick the best theme for meeting room names.', ['Planets', 'Famous inventors', 'Cities', 'Snacks', 'Board games']),
  r('office', 5, 'What is the most useful office supply?', [
    'Sticky notes',
    'Whiteboard marker',
    'Stapler',
    'Highlighter',
    'A really good pen',
  ]),
  r('office', 6, 'What is your favourite kind of break?', [
    'Coffee run',
    'Quick walk',
    'Chat with a colleague',
    'Scroll my phone',
    'Stretch',
  ]),
  r('office', 7, 'Pick the best team-building activity.', ['Cooking class', 'Trivia night', 'Volunteering day', 'Sports day', 'Karaoke']),
  r('office', 8, 'What is the ideal office temperature?', ['Arctic', 'Cool', 'Just right', 'Toasty']),
  p('office', 1, 'Have you ever hit “reply all” by accident?'),
  p('office', 2, 'Is there a plant on or near your desk?'),
  p('office', 3, 'Have you ever talked for a while on a call before realising you were muted?'),
  p('office', 4, 'Do you eat lunch at your desk most days?'),
  p('office', 5, 'Have you ever sent a message to the wrong chat?'),
  p('office', 6, 'Do you still write to-do lists on paper?'),
  p('office', 7, 'Have you ever nodded along to an acronym you didn’t know?'),
  p('office', 8, 'Do you do your best focused work in the morning?'),
  p('office', 9, 'Do you keep snacks in your desk drawer?'),
  p('office', 10, 'Would you take a four-day week with longer days?'),
  p('office', 11, 'Do you use a second screen?'),
  p('office', 12, 'Have you ever worn slippers on a video call?'),
];

const food: Q[] = [
  m('food', 1, 'Pineapple on pizza?', ['Absolutely', 'Never']),
  m('food', 2, 'Coffee or tea?', ['Coffee', 'Tea', 'Neither', 'Both, please']),
  m('food', 3, 'Which breakfast wins?', ['Pancakes', 'Eggs on toast', 'Cereal', 'I skip breakfast']),
  m('food', 4, 'What is the best pizza crust?', ['Thin and crispy', 'Deep dish', 'Stuffed crust', 'Classic hand-tossed']),
  m('food', 5, 'For a year, would you rather give up chocolate or cheese?', ['Give up chocolate', 'Give up cheese']),
  m('food', 6, 'Pick your fries.', ['Skinny fries', 'Curly fries', 'Waffle fries', 'Chunky wedges']),
  m('food', 7, 'Ice cream: cone or cup?', ['Cone', 'Cup']),
  m('food', 8, 'Pick your sandwich bread.', ['Sourdough', 'Baguette', 'A wrap', 'Plain sliced']),
  m('food', 9, 'Sweet or savoury snacks?', ['Sweet', 'Savoury', 'Both at once']),
  m('food', 10, 'Cereal first or milk first?', ['Cereal first', 'Milk first', 'No milk at all']),
  m('food', 11, 'What is the best way to eat a potato?', ['Mashed', 'Roasted', 'Baked', 'As fries']),
  m('food', 12, 'Soup or salad?', ['Soup', 'Salad']),
  r('food', 1, 'Pick your favourite pizza topping.', ['Pepperoni', 'Mushrooms', 'Extra cheese', 'Peppers', 'Olives']),
  r('food', 2, 'Pick your favourite dessert.', ['Cake', 'Ice cream', 'Pie', 'Cookies', 'Brownies']),
  r('food', 3, 'What is the best condiment?', ['Ketchup', 'Mustard', 'Mayonnaise', 'Hot sauce', 'Barbecue sauce']),
  r('food', 4, 'Pick your favourite fruit.', ['Strawberries', 'Mango', 'Apples', 'Bananas', 'Grapes']),
  r('food', 5, 'Which takeaway night wins?', ['Pizza', 'Curry', 'Tacos', 'Sushi', 'Burgers']),
  r('food', 6, 'Pick your favourite morning drink.', ['Coffee', 'Tea', 'Orange juice', 'A smoothie', 'Water']),
  r('food', 7, 'What is the best movie snack?', ['Popcorn', 'Nachos', 'Sweets', 'Chocolate']),
  r('food', 8, 'How do you like your eggs?', ['Scrambled', 'Fried', 'Boiled', 'Poached', 'As an omelette']),
  p('food', 1, 'Do you put ketchup on your eggs?'),
  p('food', 2, 'Have you ever ordered dessert before your main course?'),
  p('food', 3, 'Do you enjoy really spicy food?'),
  p('food', 4, 'Can you cook at least one dish without a recipe?'),
  p('food', 5, 'Do you drink more than two cups of coffee on a typical day?'),
  p('food', 6, 'Have you ever had cereal for dinner?'),
  p('food', 7, 'Do you eat the crusts of your sandwich?'),
  p('food', 8, 'Do you like olives?'),
  p('food', 9, 'Have you ever baked your own bread?'),
  p('food', 10, 'Do you snack while you work?'),
  p('food', 11, 'Would you happily eat the same lunch every day?'),
  p('food', 12, 'Do you enjoy cold leftover pizza?'),
];

const weekend: Q[] = [
  m('weekend', 1, 'Early bird or night owl?', ['Early bird', 'Night owl', 'Permanently sleepy']),
  m('weekend', 2, 'What is your ideal Saturday morning?', ['Sleep in', 'A workout', 'A big breakfast', 'Errands done early']),
  m('weekend', 3, 'Read the book or watch the film?', ['Read the book', 'Watch the film']),
  m('weekend', 4, 'What is the perfect rainy-day activity?', ['Movie marathon', 'Board games', 'Baking', 'A long nap']),
  m('weekend', 5, 'Would you rather go to a concert or a comedy show?', ['A concert', 'A comedy show']),
  m('weekend', 6, 'What is your go-to exercise?', ['Walking', 'The gym', 'Yoga', 'Does taking the stairs count?']),
  m('weekend', 7, 'Board games: competitive or cooperative?', ['Competitive', 'Cooperative']),
  m('weekend', 8, 'Would you rather have a spotless home or a free afternoon?', ['A spotless home', 'A free afternoon']),
  m('weekend', 9, 'What is the best season?', ['Spring', 'Summer', 'Autumn', 'Winter']),
  m('weekend', 10, 'How do you handle your alarm?', ['Up on the first ring', 'One snooze', 'Many snoozes', 'I don’t need one']),
  m('weekend', 11, 'Cats or dogs?', ['Cats', 'Dogs', 'Both', 'Neither, fish!']),
  m('weekend', 12, 'At a party, would you rather sing karaoke or dance?', ['Sing karaoke', 'Dance', 'Cheer from a safe distance']),
  r('weekend', 1, 'Pick your favourite way to spend a Sunday.', [
    'Outdoors',
    'Seeing friends',
    'Gaming',
    'Cooking',
    'Doing nothing at all',
  ]),
  r('weekend', 2, 'Pick the best kind of game night.', ['Card games', 'Board games', 'Video games', 'Quiz night', 'Charades']),
  r('weekend', 3, 'Pick your favourite movie genre.', ['Comedy', 'Action', 'Sci-fi', 'Horror', 'Animation']),
  r('weekend', 4, 'Which hobby would you pick up?', ['Painting', 'Gardening', 'An instrument', 'Photography', 'Knitting']),
  r('weekend', 5, 'Pick your favourite weather.', ['Sunny and warm', 'Crisp and cool', 'Snowy', 'Rainy and cosy']),
  r('weekend', 6, 'Which pet would you choose?', ['Dog', 'Cat', 'Fish', 'Rabbit', 'Parrot']),
  r('weekend', 7, 'What do you listen to most?', ['Podcasts', 'Music', 'Audiobooks', 'Radio', 'Blissful silence']),
  r('weekend', 8, 'Pick your favourite time of day.', ['Early morning', 'Late morning', 'Afternoon', 'Evening', 'Late night']),
  p('weekend', 1, 'Do you make your bed every morning?'),
  p('weekend', 2, 'Have you ever watched a whole series in one weekend?'),
  p('weekend', 3, 'Do you play a musical instrument?'),
  p('weekend', 4, 'Have you ever run in an organised race of any distance?'),
  p('weekend', 5, 'Do you read before going to sleep?'),
  p('weekend', 6, 'Do you have a houseplant that is thriving right now?'),
  p('weekend', 7, 'Can you whistle?'),
  p('weekend', 8, 'Have you ever built flat-pack furniture with no spare screws left over?'),
  p('weekend', 9, 'Do you still have a toy from your childhood?'),
  p('weekend', 10, 'Can you juggle three balls?'),
  p('weekend', 11, 'Do you talk to your pets or plants?'),
  p('weekend', 12, 'Have you ever learned a dance from a video?'),
];

const tech: Q[] = [
  m('tech', 1, 'When do you charge your phone?', ['Keep it near 100%', 'Overnight', 'When it hits 5%', 'Whenever I find a charger']),
  m('tech', 2, 'Light mode or dark mode?', ['Light mode', 'Dark mode', 'Automatic']),
  m('tech', 3, 'How many browser tabs do you usually have open?', ['Under 5', '5 to 15', '16 to 50', 'Please don’t ask']),
  m('tech', 4, 'Would you rather have a week of phone battery or a perfect camera?', ['A week of battery', 'A perfect camera']),
  m('tech', 5, 'Keyboard shortcuts or mouse?', ['Shortcuts all day', 'Mouse and menus', 'A bit of both']),
  m('tech', 6, 'How do you handle notifications?', ['All on', 'Only the important ones', 'All off']),
  m('tech', 7, 'How do you listen to music on the go?', ['Over-ear headphones', 'Earbuds', 'Phone speaker', 'I enjoy the silence']),
  m('tech', 8, 'Would you rather lose your phone or your keys for a day?', ['My phone', 'My keys']),
  m('tech', 9, 'How do you take notes?', ['Paper notebook', 'Notes app', 'Sticky notes', 'I remember everything (I don’t)']),
  m('tech', 10, 'For one week, would you rather use only a tablet or only a laptop?', ['Only a tablet', 'Only a laptop']),
  m('tech', 11, 'How often do you use emoji?', ['Constantly', 'Sometimes', 'Only the thumbs up', 'Never']),
  m('tech', 12, 'Would you rather have a robot that cooks or one that cleans?', ['A robot that cooks', 'A robot that cleans']),
  r('tech', 1, 'Pick the most useful invention.', ['The internet', 'Washing machine', 'Smartphone', 'Refrigerator', 'Light bulb']),
  r('tech', 2, 'Which kind of app could you not live without?', ['Messaging', 'Maps', 'Music', 'Photos', 'Games']),
  r('tech', 3, 'Which gadget would you keep?', ['Phone', 'Laptop', 'Headphones', 'Smartwatch', 'Games console']),
  r('tech', 4, 'Pick the most annoying tech problem.', [
    'Slow Wi-Fi',
    'Dead battery',
    'Forgotten password',
    'An update at the worst time',
    'Tangled cables',
  ]),
  r('tech', 5, 'Where do you prefer to watch a film?', ['Cinema screen', 'Big TV', 'Laptop', 'Phone']),
  r('tech', 6, 'How do you prefer to keep in touch with friends?', ['Text', 'Voice notes', 'Video call', 'Phone call', 'Memes only']),
  r('tech', 7, 'Which future tech do you want most?', ['Teleporters', 'Flying cars', 'Robot helpers', 'Holograms', 'Self-cleaning homes']),
  r('tech', 8, 'Pick the most important phone feature.', ['Battery life', 'Camera', 'Screen', 'Storage', 'Speed']),
  p('tech', 1, 'Do you have more than 20 browser tabs open right now?'),
  p('tech', 2, 'Has “turn it off and on again” ever fixed something for you?'),
  p('tech', 3, 'Do you read the terms and conditions before accepting them?'),
  p('tech', 4, 'Is your phone screen cracked right now?'),
  p('tech', 5, 'Have you ever built your own computer?'),
  p('tech', 6, 'Do you have more than 1,000 unread emails?'),
  p('tech', 7, 'Do you wear a smartwatch or fitness tracker?'),
  p('tech', 8, 'Have you ever given your Wi-Fi network a funny name?'),
  p('tech', 9, 'Do you still own a CD or DVD?'),
  p('tech', 10, 'Have you ever written a line of code?'),
  p('tech', 11, 'Do you talk to a voice assistant regularly?'),
  p('tech', 12, 'Is your phone on silent most of the time?'),
];

const whatif: Q[] = [
  m('whatif', 1, 'Which superpower would you choose?', ['Flight', 'Invisibility', 'Teleportation', 'Time travel']),
  m('whatif', 2, 'Would you rather talk to animals or speak every language?', ['Talk to animals', 'Speak every language']),
  m('whatif', 3, 'Would you rather explore outer space or the deep ocean?', ['Outer space', 'The deep ocean']),
  m('whatif', 4, 'Would you rather live without music or without films?', ['Without music', 'Without films']),
  m('whatif', 5, 'If you could only keep one: sunrise or sunset?', ['Sunrise', 'Sunset']),
  m('whatif', 6, 'Would you rather pause time or rewind ten seconds?', ['Pause time', 'Rewind ten seconds']),
  m('whatif', 7, 'Would you rather have a personal chef or a personal driver?', ['A personal chef', 'A personal driver']),
  m('whatif', 8, 'What is your zombie apocalypse plan?', [
    'Fortify the house',
    'Head for the hills',
    'Lead the survivors',
    'Befriend the zombies',
  ]),
  m('whatif', 9, 'Would you rather always be ten minutes early or ten minutes late?', ['Always early', 'Always late']),
  m('whatif', 10, 'Would you rather be the funniest or the smartest person in the room?', ['The funniest', 'The smartest']),
  m('whatif', 11, 'You can instantly master one skill. Which?', ['Cooking', 'An instrument', 'A new language', 'Drawing']),
  m('whatif', 12, 'Would you rather live in a treehouse or on a houseboat?', ['A treehouse', 'A houseboat']),
  r('whatif', 1, 'Pick the best superpower.', ['Flight', 'Invisibility', 'Super strength', 'Mind reading', 'Teleportation']),
  r('whatif', 2, 'Which mythical creature would you keep as a pet?', ['Dragon', 'Unicorn', 'Phoenix', 'Griffin', 'Sea serpent']),
  r('whatif', 3, 'Which era would you visit with a time machine?', [
    'The dinosaur age',
    'Ancient Egypt',
    'Medieval times',
    'The 1980s',
    'The far future',
  ]),
  r('whatif', 4, 'Where would you build your secret base?', [
    'Inside a volcano',
    'Under the sea',
    'On the Moon',
    'In a mountain cave',
    'In the treetops',
  ]),
  r('whatif', 5, 'If you were a kitchen utensil, which would you be?', ['Spatula', 'Whisk', 'Ladle', 'Tongs', 'Pizza cutter']),
  r('whatif', 6, 'Which animal would you swap lives with for a day?', ['Cat', 'Eagle', 'Dolphin', 'Sloth', 'Octopus']),
  r('whatif', 7, 'Pick the most useful robot.', [
    'Laundry folder',
    'Dish washer',
    'Dog walker',
    'Grocery shopper',
    'Coffee-making alarm clock',
  ]),
  r('whatif', 8, 'Pick your personal theme music.', ['Rock anthem', 'Epic orchestra', 'Smooth jazz', 'Pop banger', 'Lift music']),
  p('whatif', 1, 'Would you travel to space if you had the chance?'),
  p('whatif', 2, 'Would you eat a cooked insect in exchange for a free holiday?'),
  p('whatif', 3, 'Would you swap lives with a pet for a day?'),
  p('whatif', 4, 'Would you want to read minds, even if you could never switch it off?'),
  p('whatif', 5, 'Would you live in a real castle if you were given one?'),
  p('whatif', 6, 'Which would you rather do?', ['See the future', 'Change the past']),
  p('whatif', 7, 'Would you give up your phone for a month in exchange for a dream holiday?'),
  p('whatif', 8, 'Would you ride in a flying car on its very first day?'),
  p('whatif', 9, 'Would you ride a friendly dragon if one offered?'),
  p('whatif', 10, 'Would you take the power of flight if you could only fly at walking speed?'),
  p('whatif', 11, 'Which would you rather be?', ['A wizard', 'A superhero']),
  p('whatif', 12, 'Would you want a robot double to attend your meetings?'),
];

const travel: Q[] = [
  m('travel', 1, 'Window or aisle seat?', ['Window', 'Aisle', 'Middle, bravely']),
  m('travel', 2, 'Beach, mountains or city?', ['Beach', 'Mountains', 'City break']),
  m('travel', 3, 'How do you pack?', ['Carry-on only', 'Big suitcase', 'Whatever fits in my pockets']),
  m('travel', 4, 'Plan every detail or go with the flow?', ['Plan every detail', 'Go with the flow']),
  m('travel', 5, 'Road trip or train journey?', ['Road trip', 'Train journey']),
  m('travel', 6, 'Where would you rather stay?', ['Hotel', 'Holiday rental', 'Camping', 'With friends']),
  m('travel', 7, 'At the airport you are usually…', ['Hours early', 'Right on time', 'Sprinting to the gate']),
  m('travel', 8, 'What souvenir do you bring home?', ['Fridge magnets', 'Local snacks', 'Photos only', 'Nothing at all']),
  m('travel', 9, 'What is your ideal commute?', ['Walk', 'Bike', 'Public transport', 'Car']),
  m('travel', 10, 'A new country every year or a favourite place you return to?', [
    'A new country every year',
    'My favourite place, again',
  ]),
  m('travel', 11, 'Would you rather see the Northern Lights or a total solar eclipse?', ['The Northern Lights', 'A total solar eclipse']),
  m('travel', 12, 'What is your holiday pace?', ['Relax by the pool', 'Explore all day', 'A mix of both']),
  r('travel', 1, 'Pick the best holiday activity.', ['Sightseeing', 'Beach time', 'Hiking', 'Food tours', 'Museums']),
  r('travel', 2, 'Pick your favourite way to travel.', ['Plane', 'Train', 'Car', 'Boat', 'Bike']),
  r('travel', 3, 'Where would you most like to stay?', ['Hotel', 'Cabin', 'Tent', 'Castle', 'Treehouse']),
  r('travel', 4, 'What is the most important thing to pack?', ['Phone charger', 'Sunglasses', 'Snacks', 'A good book', 'Comfy shoes']),
  r('travel', 5, 'Pick your dream destination.', ['Tropical island', 'Big city', 'Snowy mountains', 'Desert', 'Countryside']),
  r('travel', 6, 'What is the best part of a trip?', ['Planning it', 'The journey', 'Arriving', 'The food', 'Coming home']),
  r('travel', 7, 'Pick the best road trip snack.', ['Crisps', 'Sweets', 'Sandwiches', 'Fruit', 'Nuts']),
  r('travel', 8, 'Pick your favourite view.', ['Ocean', 'Mountains', 'City skyline', 'Forest', 'Starry sky']),
  p('travel', 1, 'Have you ever missed a flight or a train?'),
  p('travel', 2, 'Have you visited more than five countries?'),
  p('travel', 3, 'Can you sleep on a plane?'),
  p('travel', 4, 'Have you ever gone camping?'),
  p('travel', 5, 'Do you unpack as soon as you arrive?'),
  p('travel', 6, 'Have you ever got lost even with a map app?'),
  p('travel', 7, 'Do you enjoy travelling alone?'),
  p('travel', 8, 'Have you ever travelled somewhere just for the food?'),
  p('travel', 9, 'Do you keep a travel bucket list?'),
  p('travel', 10, 'Have you ever taken an overnight train?'),
  p('travel', 11, 'Do you send postcards when you travel?'),
  p('travel', 12, 'Do you learn a few words of the local language before a trip?'),
];

export const SURVEY_PACKS: Record<SurveyPackId, readonly SurveyQuestion[]> = { office, food, weekend, tech, whatif, travel };

/** Every built-in question. */
export const ALL_SURVEY_QUESTIONS: readonly SurveyQuestion[] = Object.values(SURVEY_PACKS).flat();
