/** 10×10 pixel glyphs for the arsenal (PixelArt rows; letters map to the UI palette). */
import type { WeaponId } from '@dascade/shared/games/tanks';

export const WEAPON_ART: Record<WeaponId, readonly string[]> = {
  shell: [
    '..........',
    '..........',
    '.nnwwwy...',
    '.nnwwwyy..',
    '.nnwwwyyy.',
    '.nnwwwyy..',
    '.nnwwwy...',
    '..........',
    '..........',
    '..........',
  ],
  heavy: [
    '...oooo...',
    '..oyyyoo..',
    '.oyyooooo.',
    '.oyoooooo.',
    '.oooooooo.',
    '.oooooooo.',
    '..oooooo..',
    '...oooo...',
    '...n..n...',
    '..nn..nn..',
  ],
  cluster: [
    '....pp....',
    '...pwwp...',
    '....pp....',
    '.pp....pp.',
    'pwwp..pwwp',
    '.pp....pp.',
    '....pp....',
    '...pwwp...',
    '....pp....',
    '..........',
  ],
  airburst: [
    '....c.....',
    '.c..c..c..',
    '..c.c.c...',
    '...cwc....',
    'cccwwwccc.',
    '...cwc....',
    '..c.c.c...',
    '.c..c..c..',
    '....c.....',
    '..........',
  ],
  driller: [
    '..gggggg..',
    '..gwgggg..',
    '..gggggg..',
    '...gwgg...',
    '...gggg...',
    '....gg....',
    '....gg....',
    '....g.....',
    '..........',
    '..........',
  ],
  dirt: [
    '..........',
    '..........',
    '..........',
    '....bb....',
    '...bbbb...',
    '..bbsbbb..',
    '.bbbbbsbb.',
    'bbbbbbbbbb',
    'bbsbbbbbbb',
    '..........',
  ],
};
